### ISSUE TITLE
Reusing sentry file from other sources

### ISSUE THREAD

**Issue by Billyraa** [seishun/node-steam#106]
This is not exactly a bug, but rather a question which I believe is relevant and a possible feature sugestion. Sorry if this question is unreasonable, I'm not familiar with sentry files.

Is it possible to reuse a sentry from SteamBot or otherwise use what is used by the Steam Client (ssfn*?) and Steamommunity.com (cookies?) to generate a node-steam shaSentryfile to authenticate as a non-restricted machine in order to bypass the unreasonable 7 day period of trade offer restriction?

**Comment by ronjunelopez** [comment]
what does shaSentryFIle stored? is it the web session and login key?
