### ISSUE TITLE
Which ports does node-steam use?

### ISSUE THREAD

**Issue by maikeldus** [seishun/node-steam#108]
Which minimal set of ports i need to open for node-steam to function? I have found this page: https://support.steampowered.com/kb_article.php?ref=8571-GLVN-8711 but i'm not sure which are really required from the Steam Client set?

**Comment by scholtzm** [comment]
You don't need to open any port.

**Comment by maikeldus** [comment]
Yes you do. I´ve got a very strict setup with iptables on my VPS and with this firewall enabled i cannot login with node-steam.

**Comment by 129383** [comment]
UDP 4380-4379 (all outbound) is what you are looking for.
4380 is for authentication with steam servers and other steam services (e.g. friend status, announcements etc.)
4379 Is either text or voice chat
same with 3478 so you might want to open up that one too if the above setup doesn't work.

**Comment by maikeldus** [comment]
I tried your suggestion but this didn't worked. I debugged my VPS with wireshark and for authentication you only need to reach tcp port 27019 on some valve server.

# iptables -A OUTPUT -p tcp --dport 27019 -m state --state NEW,ESTABLISHED -j ACCEPT
# iptables -A INPUT -p tcp --sport 27019 -m state --state ESTABLISHED -j ACCEPT
These IPtables rules are not tested with other functionality (like chat, etc).
