### ISSUE TITLE
Possible to use password hash instead of plaintext password?

### ISSUE THREAD

**Issue by Pugsworth** [seishun/node-steam#111]
I've looked around in examples and the source code and couldn't find any functionality for this.
I don't like the idea that I have to store the account information as plain text.

Is this possible at all to do?

**Comment by seishun** [comment]
Steam doesn't use hashes. With the "save password" option, Steam client stores and uses a random login_key instead of your password.

How would storing a hash instead of a plaintext password help, anyway? If someone gains access to your files, they will just use the hash.
