### ISSUE TITLE
Failing to install using npm.

### ISSUE THREAD

**Issue by JakeCooper** [seishun/node-steam#112]
Hey, I'm relatively new to Node, and I'm looking to pull this package. Everytime I enter npm install steam into the commandline, I get a massive amount of errors.

Here's a pastebin of my npm-debug.log file (http://pastebin.com/JuhRNapN).

Any Ideas? I'm on windows BTW.

**Comment by seishun** [comment]
The version on npm is currently outdated and doesn't work on node.js v0.12. Your best bet would be to install from git instead:

```
npm install git+https://github.com/seishun/node-steam.git
```

Then go to the module directory and run `npm install` (without arguments).

**Comment by JakeCooper** [comment]
Just downloaded the zip from Github and threw it in my modules folder. Tried to run NPM install and got this:

http://pastebin.com/PGV86Rv6

Tried it your way, got this:

http://pastebin.com/9rZaWjJU

Any ideas?

**Comment by Starfox64** [comment]
You need to install a command line svn client, https://sliksvn.com/download/ works fine.

**Comment by JakeCooper** [comment]
Ya I thought that was the problem reading over it, wasn't sure what client to grab. That works, however now when I try and run the tester file, it says that node can't find module 'steam'. Any ideas?

**Comment by Starfox64** [comment]
Go to **WindowsSessionName/node_modules** and check if the steam folder is there.

**Comment by JakeCooper** [comment]
Yup its in there.

**Comment by Starfox64** [comment]
Well if I were you i'd just reinstall it from scratch, it might fix it.
```
npm uninstall steam
npm install git://github.com/seishun/node-steam.git
cd node_modules
npm install
```

**Comment by JakeCooper** [comment]
http://pastebin.com/ZHA4BHh5

That's what I get when I try to uninstall it :S.

**Comment by Starfox64** [comment]
I do believe EBUSY means it's being used by something, close the file explorer if you are browsing the module with it.

**Comment by JakeCooper** [comment]
nevermind, got it working. Sublime didn't save my changes to the username and password :/. Thank you so much!
