### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by youbaka** [seishun/node-steam#113]
Node 0.12.0
Ubuntu 14.10 x64

root@test2:~# node test
/root/node_modules/steam/lib/steam_client.js:18
th.join(__dirname, '../resources/protobufs/dota/steammessages.proto')).build()
                                                                      ^
TypeError: Cannot read property 'build' of null
    at Object.<anonymous> (/root/node_modules/steam/lib/steam_client.js:18:108)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/test.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by seishun** [comment]
Did you run `npm install` in the module directory?

**Comment by youbaka** [comment]
Yes

**Comment by seishun** [comment]
Can you run it again and show the output?

**Comment by youbaka** [comment]
Wow, i got error

root@test2:~/node_modules# npm install
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.16.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /root/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

npm ERR! package.json ENOENT, open '/root/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

**Comment by seishun** [comment]
You have to run it inside node-steam's directory.

**Comment by youbaka** [comment]
Oh yes, i forgot to specify directory.
But i have only 'steam', not 'node-steam'. I installed module from git (npm install seishun/node-steam), maybe it's the reason.

root@test2:~/node_modules/steam# npm install
npm WARN cannot run in wd steam@0.6.7 svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/Protobufs resources/protobufs && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/SteamLanguage resources/steam_language (wd=/root/node_modules/steam)

**Comment by youbaka** [comment]
svn already installed

**Comment by seishun** [comment]
As a workaround you can use `npm install --unsafe-perm`, but in the long term you shouldn't run npm as root.

**Comment by youbaka** [comment]
It works! Thank you a lot for help <3
