### ISSUE TITLE
Getting an offline friend's name

### ISSUE THREAD

**Issue by Starfox64** [seishun/node-steam#114]
Hello,
When I want to get a friend's name I use the users object, the issue is that the users object doesn't contains friends that are offline. How can I get the name of an offline friend?

**Comment by yebudar** [comment]
What do you mean 'get the name'? How are you referencing the friend, by some kind of ID or by a string? This might help you: [node-steam-api](https://www.npmjs.com/package/steam-api), look for the 'ResolveVanityUrl' function. From that you can get a string with a user's name from an ID.

**Comment by Starfox64** [comment]
I was having issues with this code https://github.com/Starfox64/FoxedBot/blob/master/foxedbot.js/config/commands.js#L44 where sometimes SteamID64 in the friends array aren't available in the users array and it seemed to be happening with users who are offline (unless they were connected while the bot was running)

**Comment by yebudar** [comment]
Quoting the docs, the users array shows 'information about users you have encountered'. I'm not entirely sure but is it possible that this means that users you played games recently with are displayed here? So if someone is a friend but you have never played a game with them then they will not appear. The docs are quite vague, doing a bit of guesswork here.

**Comment by seishun** [comment]
This functionality doesn't currently exist. I'm thinking about how to better implement it.
