### ISSUE TITLE
Error on npm install steam

### ISSUE THREAD

**Issue by RakouskyS** [seishun/node-steam#118]
Installing this in its own folder, I get these error messages. Full npm-debug.log on http://pastebin.com/Pw2KSjrK

>1366 verbose stack Error: ursa@0.8.2 install: `node-gyp configure && node-gyp build && node install.js`
1366 verbose stack Exit status 1
1366 verbose stack     at EventEmitter.<anonymous> (C:\Users\sandro\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:213:16)
1366 verbose stack     at EventEmitter.emit (events.js:110:17)
1366 verbose stack     at ChildProcess.<anonymous> (C:\Users\sandro\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:14:12)
1366 verbose stack     at ChildProcess.emit (events.js:110:17)
1366 verbose stack     at maybeClose (child_process.js:1008:16)
1366 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
1367 verbose pkgid ursa@0.8.2
1368 verbose cwd C:\Users\sandro\steamb
1369 error Windows_NT 6.3.9600
1370 error argv "node" "C:\\Users\\sandro\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "steam"
1371 error node v0.12.0
1372 error npm  v2.5.1
1373 error code ELIFECYCLE
1374 error ursa@0.8.2 install: `node-gyp configure && node-gyp build && node install.js`
1374 error Exit status 1
1375 error Failed at the ursa@0.8.2 install script 'node-gyp configure && node-gyp build && node install.js'.
1375 error This is most likely a problem with the ursa package,
1375 error not with npm itself.
1375 error Tell the author that this fails on your system:
1375 error     node-gyp configure && node-gyp build && node install.js
1375 error You can get their info via:
>1375 error     npm owner ls ursa
>1375 error There is likely additional logging output above.
>1376 verbose exit [ 1, true ]
>1377 verbose unbuild node_modules\steam\node_modules\ursa
>1378 info preuninstall ursa@0.8.2
>1379 info uninstall ursa@0.8.2
>1380 verbose unbuild rmStuff ursa@0.8.2 from C:\Users\sandro\steamb\node_modules
1381 verbose unbuild rmStuff in C:\Users\sandro\steamb\node_modules\steam\node_modules
1382 info postuninstall ursa@0.8.2
1383 verbose gentlyRm vacuuming C:\Users\sandro\steamb\node_modules\steam\node_modules\ursa
1384 silly gentlyRm purging C:\Users\sandro\steamb\node_modules\steam\node_modules\ursa
1385 silly gentlyRm quitting because other entries in C:\Users\sandro\steamb\node_modules\steam\node_modules
1386 verbose unbuild node_modules\steam
1387 info preuninstall steam@0.6.7
1388 info uninstall steam@0.6.7
1389 verbose unbuild rmStuff steam@0.6.7 from C:\Users\sandro\steamb\node_modules
1390 info postuninstall steam@0.6.7
1391 verbose gentlyRm vacuuming C:\Users\sandro\steamb\node_modules\steam
1392 silly gentlyRm purging C:\Users\sandro\steamb\node_modules\steam
1393 silly gentlyRm removing C:\Users\sandro\steamb\node_modules
1394 silly gentlyRm finished vacuuming up to C:\Users\sandro\steamb

How can I go about fixing this? 

edit: fixxed, im an idiot

**Comment by RakouskyS** [comment]
Also, getting errors when installing ursa: http://pastebin.com/6H01Tv1F

**Comment by seishun** [comment]
See [this](https://github.com/seishun/node-steam/issues/112#issuecomment-74240275).
