### ISSUE TITLE
Bots trade requests time out.

### ISSUE THREAD

**Issue by JakeCooper** [seishun/node-steam#119]
Hey, so I've got bot trading working, only problem is that the trade requests seem to time out. Every time i enter trade with the bot, it just sits at 'Waiting for <Botname>' and then times out.

http://i.imgur.com/4ou5CsW.png

Not sure if this is an issue or something I'm doing wrong.

**Comment by scholtzm** [comment]
That timeout happens when your bot doesn't poll the trade.

You need to use [steam-trade](https://github.com/seishun/node-steam-trade) for that.

**Comment by seishun** [comment]
The above answer is correct.

**Comment by JakeCooper** [comment]
Sorry, how would I go about polling the trade?

This is what I have for my sessionStart listener after I initiate the trade using bot.trade(steamID).

bot.on('sessionStart', function(steamID){
	steamTrade.open(steamID, function(){
		console.log("trade successfully started");
	});
});
