### ISSUE TITLE
Wait for a listener to be called before proceeding with a function

### ISSUE THREAD

**Issue by JakeCooper** [seishun/node-steam#122]
Hey, so I'm trying to run a couple functions, one being buildABot and the other requestItems, which takes a parameter of steamOfferObj returned by buildABot. (RequestItems: http://pastebin.com/jsJ4fhwG, BuildABot: http://pastebin.com/FQ2arcVe).

However, since I call them like this:

var offerObj = new buildABot('username', 'password');
requestItems(offerObj, '76561198009923867', itemID);

The offerObj seems to be null when requestItems is called. Is there any way to prevent this?

**Comment by scholtzm** [comment]
The code you provided contains username and password.

**Comment by JakeCooper** [comment]
Wow I suck, good catch!

**Comment by seishun** [comment]
Closing since this is not a library issue. Generic questions about asynchronous programming should be asked in e.g. #Node.js channel.
