### ISSUE TITLE
chatRooms does not properly store IDs of multi-user chats

### ISSUE THREAD

**Issue by Exxion** [seishun/node-steam#125]
As expected, information on group chat rooms is stored under bot.chatRooms[*Chat ID*]. However, information on multi-user chats not associated with Steam groups is stored under bot.chatRooms["0"]. Presumably, this would cause problems if multiple multi-user chats were joined at once, but I haven't had a chance to check.
These multi-user chat rooms do have IDs, as confirmed by information contained within message events. The bot can send messages to these IDs and the messages work as expected. The only problem is with the ID they are stored as in bot.chatRooms.

**Comment by seishun** [comment]
Yet another bug caused by the switch to ProtoBuf.js. Should be trivial to fix.
