### ISSUE TITLE
Automated Web<->Steam trading

### ISSUE THREAD

**Issue by itsDramo** [seishun/node-steam#128]
Hello,
I know the issue system isn't for that but I was unable to find a better way to contact with you guys.
I have my own shop where you can buy CS:GO items and I would like to automate the entire process. But I am not capable of doing it on my own (at the moment), and I would like to have it ASAP. I need to pull itemnames/item ID's from database, check steam trade URLs and send orders to customers.
I am able to pay for this (money/items).
Is someone willing to help me with this? Looking at the functions of Node Steam Bot, It isnt so much to do.
You can contact me at hiimdramo@gmail.com.

**Comment by andrewda** [comment]
Try purchasing one from http://reddit.com/r/SteamBot or http://reddit.com/r/NodeSteam
