### ISSUE TITLE
Loading multiple inventories

### ISSUE THREAD

**Issue by dragonbanshee** [seishun/node-steam#132]
I am trying to load both a TF2 and a CS:GO inventory, but once it's loaded it seems to unload itself.

My loadInventory code(s):
```javascript
steamTrade.loadInventory(440, 2, function(inv) {
	myTF2Keys = inv.filter(function(item) {
		return item.name === 'Mann Co. Supply Crate Key';
	});
	myMetal = inv.filter(function(item) {
		return item.name === 'Refined Metal';
	});
});
steamTrade.loadInventory(730, 2, function(inv) {
	myCSGOKeys = inv.filter(function(item) {
		return item.type === 'Base Grade Key';
	});
});
bot.sendMessage(steamID, 'I currently have ' + myTF2Keys.length + ' TF2 keys, ' + myCSGOKeys.length + ' CS:GO keys, and ' + myMetal.length + ' refined metal.');		
```

When the message is sent at the end, they all show 0, even though I threw a console log after the ```myMetal = inv.filter``` function and the ```myCSGOKeys = inv.filter``` function, and they both said 3.

**Comment by dragonbanshee** [comment]
I found a workaround for this issue. I defined 3 variables, all with the value of the length of its array. For example, `myMetalNumber` is equal to `myMetal.length`.

**Comment by jabbink** [comment]
Currently mobile, but it seems that you use the asynchronous loadInventory call twice, to then send the chat message before being sure the loadInventory calls are actually done.

**Comment by scholtzm** [comment]
As @jabbink has already pointed out, the `loadInventory` functions are async therefore this won't work. You should probably read some articles about asynchronous programming before creating another "it somehow works" solution. :+1:
