### ISSUE TITLE
Feature Request: Account Flags

### ISSUE THREAD

**Issue by roflmuffin** [seishun/node-steam#133]
It would be useful to be able to get the account flags associated with a bot's account. They are received during the EMsg.ClientLogOnResponse handler but are never passed anywhere into the bot.

This sort of information would be useful for checking if an account is Limited, Vacced, Requires Email Validation etc.

You can find the relevant EAccountFlags enum in SteamKit here: https://github.com/SteamRE/SteamKit/blob/191242128eadb290e2d8fbf3da4928dfd319cf6f/Resources/SteamLanguage/enums.steamd#L78

Sorry if there is currently a way to do this easily, if so just let me know and close.

**Comment by Alex7Kom** [comment]
+1

**Comment by seishun** [comment]
I think it would be better to pass the whole CMsgClientLogonResponse object, similarly to SteamKit2. I should probably write a generic description of how protobuf messages are passed to the user and get rid of the type list in the documentation for the ['user' event](https://github.com/seishun/node-steam#user).

**Comment by seishun** [comment]
Could you take a look at the [protobuf-doc](https://github.com/seishun/node-steam/tree/protobuf-doc) branch and give your feedback?

**Comment by seishun** [comment]
@roflmuffin 
Could you take a look at the [protobuf-doc](https://github.com/seishun/node-steam/tree/protobuf-doc) branch and give your feedback?

**Comment by roflmuffin** [comment]
Looks great thanks seishun.

**Comment by seishun** [comment]
Branch merged, thanks for the feedback.
