### ISSUE TITLE
Crash on this line: this.steamID = header.proto.steamid.toString();

### ISSUE THREAD

**Issue by mantux5** [seishun/node-steam#136]
I'm not really sure when this happens, but it happens and crashes my bots

```javascript
/var/steam/node_modules/steam/lib/steam_client.js:94
      this.steamID = header.proto.steamid.toString();
                                         ^
TypeError: Cannot read property 'toString' of null
    at SteamClient._netMsgReceived (/var/steam/node_modules/steam/lib/steam_client.js:94:42)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/var/steam/node_modules/steam/lib/connection.js:50:8)
    at Connection._readPacket (/var/steam/node_modules/steam/lib/connection.js:53:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)
    at Connection.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```

**Comment by seishun** [comment]
Interesting. Can you add the following:

```js
if (!header.proto.steamid) {
console.log(header);
console.log(data);
}
```

above the offending line? This will provide extra information next time it happens.

**Comment by mantux5** [comment]
Actually I simply edited the steam_client.js file to discard invalid data and that's it. I don't know if it makes some serious problems like that, but bots haven't crashed for some time and had no problems with processing.

**Comment by seishun** [comment]
Well, I would have liked to find out what's causing this. But feel free to close the issue if it's resolved for you.

**Comment by mantux5** [comment]
I would love to help you, but bots were constantly down and people do not like it :/

**Comment by seishun** [comment]
You could still add logging to your invalid data check.

**Comment by mantux5** [comment]
Oh, yeah :) I forgot about it. Next time when I will restart the bots and if I won't forget, I'll add those lines.

**Comment by izy521** [comment]
Could you post what your changes to the script were to get it to continue running?

Also, here's the log seishun: 
```
{ msg: -2147482891,
  headerLength: 4,
  proto: 
   { steamid: null,
     clientSessionid: 1272195,
     routingAppid: null,
     jobidSource: { low: -1, high: -1, unsigned: true },
     jobidTarget: { low: -1, high: -1, unsigned: true },
     targetJobName: null,
     seqNum: null,
     eresult: 2,
     errorMessage: null,
     ip: null,
     authAccountFlags: null,
     tokenSource: null,
     adminSpoofingUser: null,
     transportError: 1,
     messageid: { low: -1, high: -1, unsigned: true },
     publisherGroupId: null,
     sysid: null,
     traceTag: null } }
{ buffer: <Buffer f5 02 00 80 04 00 00 00 10 83 d3 4d 08 02>,
  offset: 12,
  markedOffset: -1,
  limit: 14,
  littleEndian: true,
  noAssert: false }
```

**Comment by izy521** [comment]
I should say, after a random number of disconnects, it does stay connected. This line is simply getting the bot's Steam ID? If so could I just use an if-else to set it manually?

**Comment by seishun** [comment]
@izy521
You're getting a ClientLoggedOff packet with `EResult.Fail`. From my experience, this happens when you do something Steam doesn't understand, for example try to send a message while not logged on. Would you mind posting your code reduced to just event handlers and method calls?

**Comment by izy521** [comment]
Oh, actually that makes a ton of sense. I have my main bot running on a pretty shoddy VPS and using someone else's server as a backup if the VPS goes down. They're connected via websockets, so I assume it's an issue when mine logs in and the backup logs out.

**Comment by seishun** [comment]
The line that was causing the crash no longer exists, so closing this for now.
