### ISSUE TITLE
MsgClientOGSBeginSessionResponse empty sessionId

### ISSUE THREAD

**Issue by Maxpain177** [seishun/node-steam#137]
I use this module for create, start lobby, then start server. When bot connecting to server, he sends MsgClientOGSBeginSession message:
````
{ AccountId: '76561198140868400',
  AccountType: 1,
  AppId: 570,
  TimeStarted: 1428338878 }
````
, but MsgClientOGSBeginSessionResponse contains empty sessionId:
````
{ low: 0, high: 0, unsigned: true }
````
... i do not know what to do

**Comment by seishun** [comment]
Not a library issue. Steam protocol questions can be discussed in #opensteamworks on irc.gamesurge.net.
