### ISSUE TITLE
I've successfully logged in and placed the auth code.

### ISSUE THREAD

**Issue by ThemePlugger** [seishun/node-steam#138]
Just to confirm that I need to wait for 7 days for the Steam Guard to take effect with my server right? Anyways, already saved the hashed sentry file. After that, I'll be able to create trade offers and accept them via server?

Thanks.

**Comment by jabbink** [comment]
Yes, and this isn't a `node-steam` issue.

**Comment by ThemePlugger** [comment]
@jabbink Yeah, sorry about that. I've no way to verify my inquiries by asking it here. Thanks for answering this one. I really appreciate it! :+1: :)

**Comment by jabbink** [comment]
Also more information about [Trade restrictions](https://support.steampowered.com/kb_article.php?ref=1047-edfm-2932).
