### ISSUE TITLE
avatarHash as String

### ISSUE THREAD

**Issue by riordanp** [seishun/node-steam#142]
I have the avatarHash field of a user as a Buffer object but would like to use it as a string. I have tried to use the toString method of the buffer (https://nodejs.org/api/buffer.html) but do not get the expected 20 character SHA-1 hash from either the ascii or utf8 encoding options. What is the correct way to convert this value to a string?

Thanks

**Comment by seishun** [comment]
There is no "correct" way. If you want a hex string as used in avatar URLs, use `toString('hex')`.

**Comment by iamcsharper** [comment]
And how to get URL of image by avatar_hash? Please.

**Comment by riordanp** [comment]
You can use `var hash = friend.avatarHash.toString('hex');` one your friend object to get a string representation of the hash and then build a url like so:
````
function getAvatarURL(hash) {
    var tag = hash.substr(0, 2);
    var url = "http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/" + tag + "/" + hash + "_full.jpg";
    if(hash == "0000000000000000000000000000000000000000"){
      return "http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/fe/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg"
    } else {
      return url;
    }
}
````

This will give the URL of the full size avatar or the default avatar if the user hasn't set one.

**Comment by iamcsharper** [comment]
@riordanp thanks!
