### ISSUE TITLE
Possible to get gamelist?

### ISSUE THREAD

**Issue by benjick** [seishun/node-steam#147]
Hi 

Is it possible to get a list of owned/installed games with this module?

Currently doing a hacky way of using the GetOwnedGames from the Web API and scanning for manifest-files but it doesn't work so well if the profile is not public

**Comment by seishun** [comment]
See [#40 (comment)](https://github.com/seishun/node-steam/issues/40#issuecomment-148388895). Currently, you can do this using ['message'/send](https://github.com/seishun/node-steam#messagesend) - [SteamKit2's handler](https://github.com/SteamRE/SteamKit/blob/10e5b78cc315ec230611c7d5c3082f2703e7ed9a/SteamKit2/SteamKit2/Steam/Handlers/SteamApps/SteamApps.cs#L529) might be a useful reference.
