### ISSUE TITLE
Is it possible to use the ssfn file from a Steam login on a PC as sentry file?

### ISSUE THREAD

**Issue by AardvarkMike** [seishun/node-steam#148]
is it the same thing or will I need to generate a new one with the bot?

I've googled this until my little finger tips turned blue, to no avail - please don't flame me too hard if the answer is obvious :)

**Comment by scholtzm** [comment]
Should be possible if you generate SHA-1 of it.

**Comment by AardvarkMike** [comment]
Hmmm, that doesn't seem to work - it still sends a new auth code. 

I'm trying to avoid having to trade-lock the account for 7 days. Any suggestions?

**Comment by AardvarkMike** [comment]
Ok, so for anyone else with this issue, my problem was I was giving it an Ascii SHA1 hash rather than the binary hash it expects.

I'm reading my ssfn files like so;
    var sha = require('crypto').createHash('sha1');
    sha.update(fs.readFileSync('mikes.ssfn'));
    var sentry = new Buffer(sha.digest(), 'binary');

then passing 'sentry' to shaSentryfile.

**Comment by seishun** [comment]
`sha.digest()` already returns a buffer, no need to construct another buffer from it.

Is the issue resolved?

**Comment by AardvarkMike** [comment]
That sha.digest() line was lifted directly from node-steam's user.js :o

But yes, the issue is resolved.

**Comment by seishun** [comment]
That line is really old.
