### ISSUE TITLE
Get a new webSessionId

### ISSUE THREAD

**Issue by Zexuz** [seishun/node-steam#149]
Hi, this is not a error but I don't know where else to post this.

How do i call steam.on('webSessionID' and get the sessionID manualy?

Or can i check is the sessionId and webCookie is valid? 

steam.on('webSessionID', function (sessionID) {
    steam.webLogOn(function (newCookie) {
        offers.setup({
            sessionID: sessionID,
            webCookie: newCookie
        });
    });
});

Regards.

**Comment by seishun** [comment]
There's no way to do that.

However, from what I've heard, it doesn't actually matter what sessionID you're using as long as it's the same in the cookie and the request form. So you can probably disregard the 'webSessionID' event entirely and use your own randomly generated sessionID. I'm planning to rework webLogOn in the future.
