### ISSUE TITLE
Invalid password when using SSFN file

### ISSUE THREAD

**Issue by KarlJakober** [seishun/node-steam#155]
Hi, ive copied my ssfn file over, due to wanting to skip the 7 day trade restriction. there are multiple examples of people getting this to work in the past, but I have not been able to reproduce their success..

```
var sha = require('crypto').createHash('sha1');
sha.update(fs.readFileSync('ssfn/' + 'accountName + '.ssfn'));
sha = new Buffer(sha.digest(), 'binary');
bot.logOn({ accountName:username, password:password, shaSentryfile:sha });

```
This returns the following
```
{ [Error: Logon fail: 5] cause: 'logonFail', eresult: 5 }
```
which seems to be an invalid password (it works fine when i use the sentry file provided by node steam, but it has a 7 day trade restriction)

My only thought is its because there have been multiple accounts logged on via this computer, but only one ssfn file is generated by the steam client.

Hopefully you will have an idea!

**Comment by seishun** [comment]
No idea, but maybe someone else knows. Since this is not a library issue, you should ask in #opensteamworks on irc.gamesurge.net, or start a discussion in the [SteamRE group](http://steamcommunity.com/groups/SteamRE).

**Comment by KarlJakober** [comment]
thank you!

**Comment by Netifriik** [comment]
Same problem. @KarlJakober did you find a fix?

**Comment by scholtzm** [comment]
@Netifriik Steam creates 2 SSFN files. One is a decoy and the other one is the actual SSFN file which is used by Steam. On Windows, you will need to enable "Display hidden files" in your window explorer settings in order to see the file.

**Comment by Netifriik** [comment]
@scholtzm Thank you!!!! I was trying to get that decoy ssfn to work for like 3 days straight. The other ssfn file worked perfectly.

**Comment by Adurome** [comment]
@scholtzm Do you know how to make 2 files show on a Mac book pro? I go into the steam file and sadly there is only one there...
