### ISSUE TITLE
Join on server

### ISSUE THREAD

**Issue by Pitu-pl** [seishun/node-steam#156]
Is it possible to join on server?

I tried using:
bot.on('servers', function(servers) {
  fs.writeFile('servers', JSON.stringify(servers));
});

My servers variable
var  servers = [{host: '185.49.15.7', port: 27015}];

But bot dont connect.

**Comment by jabbink** [comment]
This van "join" (read: connect to) Steam servers. It cannot connect to game servers.

**Comment by seishun** [comment]
Connecting to game servers is outside the scope of this library.
