### ISSUE TITLE
tradeResult event do not trigger

### ISSUE THREAD

**Issue by vince0401** [seishun/node-steam#158]
I need to track the offer accepted by the other partner but the tradeResult event which is suppose to trigger when the partner accept the offer sent, do not work.

m._sc.on('tradeResult', function(tradeId, status, steamId){
  c.logger.log('info', 'TradeID: %s, Status: %s, SteamID: %s', tradeId, status, steamId);
});

m._sc is the steam client object. Other events like tradeOffers do work on the same object (m._sc).

Please suggest.

**Comment by seishun** [comment]
tradeResult is for regular trade requests, not trade offers.

**Comment by vince0401** [comment]
"Listen for this event if you are the one sending a trade request."

I sent a trade offer to some other person. When this other person receives the trade request and accept the trade, will this tradeResult event won't fire in this case.

I want to track if a user accepted the trade i sent or not. Can it be done with node-steam? Please reply...

I did not understand when you said "regular trade requests, not trade offers". Kindly clarify...

**Comment by Alex7Kom** [comment]
Trade request is when you invite other user to real time trade (i.e. 'Invite to Trade' in user menu in Steam Friends).

**Comment by Efreak** [comment]
@vince0401 Try checking out [node-steam-trade-offers](https://github.com/Alex7Kom/node-steam-tradeoffers)
