### ISSUE TITLE
How can you save received Messages (on .txt)

### ISSUE THREAD

**Issue by FrozGR** [seishun/node-steam#160]
Is there any way that i can save the messages that the script receives while running on a BOTNAME.txt so i can check them later?

Something like:

[timestamp] username: message
[timestamp] username: message
[timestamp] username: message
[timestamp] username: message
 
So i can check back later on that BOTNAME.txt and see who sent me and what message.

**Comment by seishun** [comment]
Sure, but you'll have to write your own code for that. See ['friendMsg' event](https://github.com/seishun/node-steam#friendmsg).
