### ISSUE TITLE
Both addFriend() and sendMessage() methods returning undefined unless executed as a result of a successful event listen.

### ISSUE THREAD

**Issue by chrisnankervis** [seishun/node-steam#161]
I've been tinkering with your module tonight and I've run into an issue.

I've tried using a block of code found in `example.js` and have had successful results but as soon as I take the `sendMessage()` method out of the `'message'` event listener, the method fails to do what it was intended and instead returns `undefined` when the result is logged into the console.

I should also confirm that the account I'm trying to send the message to is friends with the account I'm using for authentication via the module.

```
var Steam = require('steam');
var bot = new Steam.SteamClient();

bot.logOn({
    accountName: 'username',
    password: 'password'
});

bot.on('loggedOn', function() {
    bot.setPersonaState(Steam.EPersonaState.Online);
    bot.sendMessage('STEAM_0:1:2345678', 'testing', Steam.EChatEntryType.ChatMsg);
});
```

I'm hoping to set up a bot that can interpret requests from a separate web application and execute a method as a result, is something like this possible with your module or am I out of luck?

I appreciate you taking the time to investigate my issue.

**Comment by seishun** [comment]
That's not how you pass a SteamID. It should be a number in decimal, e.g. `'76561197988007571'`.

Neither of these methods has a return value so `undefined` is expected.

**Comment by chrisnankervis** [comment]
Thanks for the explanation regarding the return values of the methods, that makes sense.

I'm pretty sure I was using the decimal value of the SteamID in my example, even though I included the incorrect one in my example above. I'll try again tonight and see how I go, thanks for your help.

**Comment by chrisnankervis** [comment]
Turns out the way I was passing the SteamID wasn't correct, silly mistake. Thank you!
