### ISSUE TITLE
'tradeProposed' event does not fire

### ISSUE THREAD

**Issue by dolanmiu** [seishun/node-steam#163]
the 'tradeOffers' event fires.

I am using steam guard.

I am using a sentry file to log in.

Account successfully logs in with no errors.

However, the 'tradeProposed' event never fires.

I am trading via Trade URL. Here is the trade URL I am using:

https://steamcommunity.com/tradeoffer/new/?partner=232811557&token=FKUQ9UR_

What is wrong?

**Comment by scholtzm** [comment]
`tradeProposed` is for "live" trades.

**Comment by seishun** [comment]
What @scholtzm said.
