### ISSUE TITLE
Add Ability to Change Game Server & Rich Presence

### ISSUE THREAD

**Issue by thesupremecommander** [seishun/node-steam#164]
Pretty much what the title says.

**Comment by seishun** [comment]
What do you mean by changing game server?

**Comment by thesupremecommander** [comment]
The game server reported by Steam as the one the player is in.

Admittedly, I'm more interested in changing rich presence.

**Comment by seishun** [comment]
Regarding rich presence, see [#257 (comment)](https://github.com/seishun/node-steam/issues/257#issuecomment-143432085).

As for reporting game server, I have no idea how that works. Would you be interested in using NetHook2 to find out which messages are being sent?

**Comment by TrueCarry** [comment]
@seishun, changed some code. https://github.com/seishun/node-steam/pull/274

**Comment by seishun** [comment]
Essential RP support was added in de4c02e9c986be47d329e18627b8c280a7d11434.
