### ISSUE TITLE
ssfn to sentry file

### ISSUE THREAD

**Issue by Yashko** [seishun/node-steam#166]
hello guys,  i have ssfn, how i can convert it to sentry?
i found some issues here about this problem but no one solution helps for me
i tried to sha1 this file but its doesnt help (login fail error 5)
please help me, show some code to convert ssfn to sentry?

**Comment by scholtzm** [comment]
https://github.com/seishun/node-steam/issues/148

**Comment by Yashko** [comment]
>i tried to sha1 this file but its doesnt help (login fail error 5)

**Comment by seishun** [comment]
It means InvalidPassword, so you're likely passing an invalid password.
