### ISSUE TITLE
Not sending 'Access from new device' email on logon event failure without sentry code

### ISSUE THREAD

**Issue by Committing** [seishun/node-steam#167]
Everything works almost perfectly. When I run login on a steam guard account without the sentry file it will error saying no sentry file which is great. Apart from it does not send off an email on the failure.

I have to logon on my phone or incognito on steamcommunity.com to get the steam access code email and then pass the code into the application and it all works.

Do I have to run another command to get the steam access code sent?

My login code is very simple:

Thank you

**Comment by seishun** [comment]
What `authCode` does it set when logging in without sentry?

**Comment by Committing** [comment]
..

**Comment by seishun** [comment]
You said you're not receiving a Steam Guard email. How are you calling `logOn` when trying to trigger it?

**Comment by Committing** [comment]
Yes, I understand what you mean now.

I just pass a blank value. (authCode: '')

**Comment by seishun** [comment]
AFAIK Steam doesn't send a Steam Guard email when trying to log in with a wrong authCode.

**Comment by Committing** [comment]
Ah! I will try without now. Will update with another post when I have done so. Thanks for your super quick responses!

**Comment by Committing** [comment]
That was it!

Thanks so much. You should get yourself a little donation button. ;)
