### ISSUE TITLE
The undefined chatter.

### ISSUE THREAD

**Issue by TheKkubas** [seishun/node-steam#168]
Hello. I started creating a bot with a steam-node and I saw the bug.
Always when my bot got a message the chatter's name value is "undefined".
I used example code and my code.

**Comment by seishun** [comment]
How are you accessing "the chatter's name value"? Is it a chat message or a private message?

**Comment by TheKkubas** [comment]
A private Steam message.

**Comment by seishun** [comment]
How are you accessing "the chatter's name value"?

**Comment by TheKkubas** [comment]
In example code we have a function for replying a messages.
```javascript
bot.on('message', function(source, message, type, chatter) {
  // respond to both chat room and private messages
  console.log('Received message: ' + message + ' from ' + chatter);
  if (message == 'ping') {
    bot.sendMessage(source, 'pong', Steam.EChatEntryType.ChatMsg); // ChatMsg by default
  }
```
and I got on log: Received message Hi from undefined

**Comment by seishun** [comment]
https://github.com/seishun/node-steam#message

>In case of a friend message, the fourth argument will be undefined.

Use the first argument for friend (private) messages.

**Comment by jabbink** [comment]
Reading the docs would help.

From docs:

    'message'

    Same arguments as the above two, captures both events. In case of a friend message, the fourth argument will be undefined.

Also `source` is what you're looking for...

**Comment by TheKkubas** [comment]
But 'source' give me a steamID64 not nickname of a guy.

**Comment by seishun** [comment]
The fourth argument isn't a nickname either, it's "SteamID of the chatter". Use [`users`](https://github.com/seishun/node-steam#users) to get users' nicknames.

**Comment by TheKkubas** [comment]
OK
