### ISSUE TITLE
Can't join to the group chat.

### ISSUE THREAD

**Issue by TheKkubas** [seishun/node-steam#169]
When my bot got an invite it writes this on console but don't joining in.
I use this function:
```javascript
  bot.on('chatInvite', function(chatRoomID, chatRoomName, patronID) {
  console.log('Got an invite to ' + chatRoomName + ' from ' + bot.users[patronID].playerName);
  bot.joinChat(chatRoomID); // autojoin on invite
});
```

**Comment by seishun** [comment]
Then your bot is either a limited account or is banned from the chat. Log into its account using a regular Steam client and try to join the chat.

**Comment by TheKkubas** [comment]
Ok... I must spend 5$ on steam to do it. Sorry for that issue.
