### ISSUE TITLE
Cant run the script.

### ISSUE THREAD

**Issue by darknegative** [seishun/node-steam#170]
Hello. So I'm trying to install Node-Steam on my pc but its not works.

I have node.js v.0.12.5
Python 27
Windows 7 Pro 64bit
Net. Framework 4.5

And when i run the example (I edited the username and password) this happens.

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\DNA>cd desktop

C:\Users\DNA\Desktop>mkdir sapila

C:\Users\DNA\Desktop>cd sapila

C:\Users\DNA\Desktop\sapila>npm install steam
steam@0.6.8 node_modules\steam
├── buffer-crc32@0.2.5
├── adm-zip@0.4.7
├── bytebuffer@4.0.0 (bufferview@1.0.1, long@2.2.5)
└── protobufjs@4.0.0 (ascli@1.0.0, glob@5.0.12, yargs@3.14.0)

C:\Users\DNA\Desktop\sapila>cd steam
The system cannot find the path specified.

C:\Users\DNA\Desktop\sapila>cd C:\Users\DNA\Desktop\sapila\node_modules\steam

C:\Users\DNA\Desktop\sapila\node_modules\steam>node example.js

C:\Users\DNA\Desktop\sapila\node_modules\steam>node -v
v0.12.5

when i do node example.js nothing happens

the PATH is set like that

C:\Program Files\nodejs;C:\Users\DNA\AppData\Roaming\npm;C:\Python27\

Any idea whats happening? Thanks

**Comment by seishun** [comment]
Does the command exit immediately or did you terminate it with Ctrl+C?

**Comment by darknegative** [comment]
Its exit immediately

**Comment by scholtzm** [comment]
Possibly a problem with prepublish?

https://github.com/seishun/node-steam#installation

**Comment by darknegative** [comment]
I did it and nothing change. Any other ideas? Thanks!

**Comment by seishun** [comment]
Have you tried running other scripts with node, debugging example.js, running node-steam methods inside REPL?

**Comment by darknegative** [comment]
Hello i tried a Normal script (from a tutorial http://howtonode.org/hello-node) and it worked fine.

The problem is when i run the script i do node example.js and its not do anything. For example

C:\Users\DNA\Desktop\sapila\node_modules\steam>node example.js (I press enter and after 1 sec it skip it)
C:\Users\DNA\Desktop\sapila\node_modules\steam>

I tried to install it on linux but with no luck.

**Comment by seishun** [comment]
Reduce the script you're using to something minimal. If it still doesn't work, paste it here.

**Comment by darknegative** [comment]
I finally make it to work on linux.

![y3glvzs](https://cloud.githubusercontent.com/assets/4589051/8477594/e8f5f33e-20d3-11e5-8599-4aca8021dcf3.png)

Now 1 more question before i close my issue (so i dont have to post another one)

On the bot i see that 


web authentication 403, retrying
web authentication 403, retrying
web authentication 403, retrying
web authentication 403, retrying
web authentication 403, retrying
web authentication 403, retrying
web authentication 403, retrying

and its keep spamming. What is that mean? And do i have to fix it?

**Comment by seishun** [comment]
Can you show how you're calling webLogOn?

**Comment by darknegative** [comment]
steam.webLogOn(function(newCookie) {

**Comment by jabbink** [comment]
Do you call this after you receive the `webSessionID` event?

**Comment by seishun** [comment]
Just post your entire code.

**Comment by darknegative** [comment]
@jabbink Yes

steam.on('webSessionID', function(sessionID) {
	globalSessionID = sessionID;
	steam.webLogOn(function(newCookie) {
		offers.setup({
			sessionID: sessionID,
			webCookie: newCookie
		}, function(err) {
			if (err) {
				throw err;
			}
			setInterval(CheckTimer,1000);
		});

**Comment by jabbink** [comment]
Does the error come every second?

If so, it might be your CheckTimer function.

**Comment by darknegative** [comment]
@jabbink 

function CheckTimer() {
	if(locked == true) return;
	locked = true;
	if(recheck == true) {
		recheck = false;
		checkoffers(1);
	}

**Comment by darknegative** [comment]
Anyway main problem solved issue can close now
