### ISSUE TITLE
trade offers

### ISSUE THREAD

**Issue by youssefdetovernickr** [seishun/node-steam#171]
It's more a question than an 'issue', however I can't seem to find how to actually interact with trade offers.. I can see that whenever there's a trade offer (done with a link, so not live) the count changes on the tradeOffer callback, however there's no way to tell it to accept or decline?

**Comment by scholtzm** [comment]
You'll have to use something like https://github.com/Alex7Kom/node-steam-tradeoffers

Trade offers are not part of this library other than the notification.

**Comment by youssefdetovernickr** [comment]
Ah thanks ..
