### ISSUE TITLE
Request: events for groupchat officer actions

### ISSUE THREAD

**Issue by Efreak** [seishun/node-steam#172]
There's no events set up for [the following actions](http://i.imgur.com/5NcVKtO.png):
- Chat gets locked/unlocked
- Chat gets moderated/unmoderated

Any chance of these getting added?

**Comment by seishun** [comment]
Blocked by SteamRE/SteamKit#133.

**Comment by scholtzm** [comment]
They added it pretty darn quickly ... https://github.com/SteamRE/SteamKit/commit/899d6d238ffd5df1d71acf8e63ec9f9e73f09d65

**Comment by seishun** [comment]
Yes, but they don't handle the payload, which means I'll have to figure it out.

**Comment by seishun** [comment]
Added in 1b0cfb2e70d30d49de7b6510cec20255c33d39ca.
