### ISSUE TITLE
issue with logging in

### ISSUE THREAD

**Issue by bogdanakh** [seishun/node-steam#173]
so i got an jackpot site and i got some issue i need to fix i got the bot but i don't know to how edit the config for it to connect to mysql 

var admin = 'id for bot';

var logOnOptions = {
	accountName: 'id',
	password: 'pw'
};
var GameTime = 120;

////

var authCode = 'КОД СТИМГУАРДА'; 

var globalSessionID;

if (require('fs').existsSync('sentry_'+logOnOptions['accountName']+'.hash')) {
	logOnOptions['shaSentryfile'] = require('fs').readFileSync('sentry_'+logOnOptions['accountName']+'.hash');
} else if (authCode != '') {
	logOnOptions['authCode'] = authCode;
}

var sitename;

sitename = "site link";
var Steam = require('steam');
var SteamTradeOffers = require('steam-tradeoffers');
var mysql      = require('mysql');
var request = require("request");
var steamuserinfo = require('steam-userinfo');

steamuserinfo.setup("AF7F2B96A5F996273A91F93BE8D3DDD5");

var mysqlInfo;
mysqlInfo = {
  host     : 'Хост базы дынных ',
  user     : 'Пользователь БД',
  password : 'Пароль БД',
  database : 'Имя базы',
  charset  : 'utf8_general_ci'
};

And also i need to edit  

ssfntosentry file
and i have no idea what to do

**Comment by jabbink** [comment]
[Read here about how to login](https://github.com/seishun/node-steam#logonlogondetails)

Then Google how to use MySQL with Node.js

**Comment by bogdanakh** [comment]
I read that and still didn't understand.

**Comment by jabbink** [comment]
In short: these GitHub Issues pages are no place to ask for programming help.

How to login is explained very well [here](https://github.com/seishun/node-steam#logonlogondetails) (I got it working the first try with the help of the README).

The MySQL thing even has nothing to do with this so it's completely in the wrong place.

**Comment by bogdanakh** [comment]
i keep getting this error each time i want to login 
C:\Users\Bogdan\Desktop\gege>node tradebot.js
connected
encrypt request
handshake complete
logon fail: 65, sessionID: 1782791
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Logon fail: 65
    at SteamClient.handlers.(anonymous function) (C:\Users\Bogdan\Desktop\gege\n
ode_modules\steam\lib\handlers\user.js:178:11)
    at SteamClient._netMsgReceived (C:\Users\Bogdan\Desktop\gege\node_modules\st
eam\lib\steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (C:\Users\Bogdan\Desktop\gege\n
ode_modules\steam\lib\steam_client.js:192:10)
    at SteamClient._netMsgReceived (C:\Users\Bogdan\Desktop\gege\node_modules\st
eam\lib\steam_client.js:106:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (C:\Users\Bogdan\Desktop\gege\node_modules\steam\l
ib\connection.js:50:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)

C:\Users\Bogdan\Desktop\gege>pause
Press any key to continue . . .

**Comment by jabbink** [comment]
Login error `65` afaik means your Steam Guard code is incorrect.

**Comment by bogdanakh** [comment]
I  need to login trough .hash if i don't want steamguard  but what do i rename my hash to? username to my steamid? sentry_steamid.hash

**Comment by bogdanakh** [comment]
I didn't get any guard code on my email.

**Comment by jabbink** [comment]
Is Steam Guard enabled on that account?

**Comment by bogdanakh** [comment]
yes

**Comment by bogdanakh** [comment]
i need to have it disabled?

**Comment by jabbink** [comment]
If you disable it, you won't be able to trade. If it is activated you should get the code in your email. If you don't: again, this is the wrong place and you should contact Steam Support.

**Comment by bogdanakh** [comment]
node import-ssfn.js bogdanholben C:\Users\Bogdan\Desktop\gege\ssfn\ssfn2445454598091469817

pause

**Comment by bogdanakh** [comment]
sentry_bogdanholben.hash is the folders name is it wrong or? i need help jabbink to login  its so close.

**Comment by jabbink** [comment]
I am not familiar with the `import-ssfn.js` (no idea if it is even from this repo).

The last time I set up accounts with node-steam I just logged in with a new/no sentry file and authorized it as a new device (con: you can't trade for 7 days).

**Comment by seishun** [comment]
What @jabbink said

>In short: these GitHub Issues pages are no place to ask for programming help.
