### ISSUE TITLE
Row (0) denies trade offer 

### ISSUE THREAD

**Issue by bogdanakh** [seishun/node-steam#176]
Hello boys so when i log in everything seem to work untill someone sends trade offer then my bot shows this error. http://gyazo.com/e0370221e70456f6f7b56e7405402cac
the section is under the cmd i have no idea what to do. also my phpmyadmin database. http://gyazo.com/e78505f8bf67f069a71645d5ed878918

**Comment by jabbink** [comment]
Again, this is a MySQL problem, not `node-steam`, because obviously the variable `row` in the callback from your MySQL connector is `undefined`, as the error states.

Maybe, just for debugging, quickly add a `if (err) throw err;` before line 337.

**Comment by seishun** [comment]
This is not a MySQL help desk.
