### ISSUE TITLE
Accept trade offer

### ISSUE THREAD

**Issue by zyznos321** [seishun/node-steam#180]
Is respondToTrade function still working? I have this code but it don't accept my pending offer.
What is wrong in this code?

bot.on('loggedOn', function() {
  console.log('Logged in!');
  bot.setPersonaState(Steam.EPersonaState.Online); // to display your bot's status as "Online"
  console.log(bot.sentry);
  bot.respondToTrade(567436217, true);
});

**Comment by srabouin** [comment]
Trades don't exist anymore afaik, everything is trade offers - you should use something like https://github.com/Alex7Kom/node-steam-tradeoffers

**Comment by zyznos321** [comment]
Thx

**Comment by seishun** [comment]
> bot.respondToTrade(567436217, true);

Where did you get that number? respondToTrade is for regular trades, not trade offers.
