### ISSUE TITLE
Socket timed out.

### ISSUE THREAD

**Issue by halipso** [seishun/node-steam#183]
I'm trying to login with my account, but got this problem.

socket timed out
socket closed
connecting to 72.165.61.187:27018
socket timed out
socket closed
connecting to 72.165.61.175:27017
socket timed out
socket closed
connecting to 146.66.152.14:27017
socket timed out

It's going on with different ip's.

node: v0.12.7

**Comment by srabouin** [comment]
Welcome to Steam. Steam is dead. Long live Steam.

**Comment by seishun** [comment]
Either your machine has an internet connection problem, or Steam is down.
