### ISSUE TITLE
SteamGuard?

### ISSUE THREAD

**Issue by Hohstapler** [seishun/node-steam#184]
I might be blind, but I don't really find where should I write the SteamGuard code I get from Steam by email.
Can somebody help me about that, please?

**Comment by seishun** [comment]
Set `auth_code` to it. See https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon.

**Comment by Hohstapler** [comment]
For some reason it gives me an error:

Error: .CMsgClientLogon#auth_code is not a field: undefined

This is the part of my code:

var bot = new Steam.SteamClient();
bot.logOn({
  accountName: 'neskezemun',
  password: 'nn29ll9o',
  auth_code: 'PM48B'
});

**Comment by seishun** [comment]
You're using an old version of node-steam. If you would like to continue using it, its [documentation](https://github.com/seishun/node-steam/tree/d92b12e0aa63cde3fa5433a93eafefb752f875cf#logonlogondetails) describes Steam Guard in detail.

**Comment by Hohstapler** [comment]
Soo, where can I find a new one?

Sorry for being annoying, but I am really giving my best to make this work.

**Comment by seishun** [comment]
I published 1.0.0 on npm 36 minutes ago, so you can just reinstall.

**Comment by Hohstapler** [comment]
Finally, it works now.

Thank you a lot and I wish you the best of luck with your future projects.

**Comment by danydasda** [comment]
Please tell me what you did
