### ISSUE TITLE
Chatter = Undefined

### ISSUE THREAD

**Issue by Hohstapler** [seishun/node-steam#185]
I have a question about     steamFriend.on('message')  
I figured out that Source is an actual SteamID of chatter, but why when we use chatter property of function it always says 'Undefined' in console.log ?

**Comment by seishun** [comment]
The 'message' event is meant for use cases where you want to respond in the same way to both chat messages and friend messages. In the former case, `source` is the chat room and `chatter` is the chatter. In the latter case, defining `chatter` would be meaningless since there is no chat.

**Comment by Hohstapler** [comment]
So, is there a way I can get a chatter nickname in console.log too?

**Comment by seishun** [comment]
Yes, by using the [personaStates](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#personastates) object.

```js
steamFriends.personaStates[chatter || source].player_name
```

**Comment by Hohstapler** [comment]
Thanks a lot, that solved my problem.
