### ISSUE TITLE
socket.io with node-steam?

### ISSUE THREAD

**Issue by PokeRwOw** [seishun/node-steam#186]
Hi!

I experienced some issue using socket.io with node-steam & node-steam-tradeoffers and I want to know if someone already used this.

My problem come really from socketio, if i delete this It's working. In my main.js firstly, i'm connecting the bot to steam. After that there is a socket for the trade but It's completly ignore, whereas if I connect and make the trade inside the socket It's working. So i'm missing something ?

io.sockets.on('connection', function (socket) {  
    socket.on('addItems', function (steamId, itemId) {
      console.log('ok');

    var admin = 'xxxxxxxxxx'; // put your partner steamid here so the bot can send you trade offers

    bot.on('webSessionID', function(sessionID) {
    bot.webLogOn(function(newCookie){
    offers.setup({
      sessionID: sessionID,
      webCookie: newCookie
    }, function(err) {
      if (err) {
        throw err;
      }
      console.log("SteamWEB connect.");

        // if there is such an item, making an offer with it
          offers.makeOffer ({
            partnerSteamId: admin,
            itemsFromMe: [
              {
                appid: 730,
                contextid: 2,
                amount: 1,
                assetid: "2368034537"
              }
            ],
            itemsFromThem: [],
            message: 'This is test'
          }, function(err, response){
            if (err) {
              throw err;
            }
            console.log(response);
          });
       });
      });
    });

       }); 
    });

So before i'm connecting the bot and It's working, after the console.log work in the socket but the whole code after is ignore... Why ?

Thanks per advance!

EDIT : The complete code with socket.io not working http://pastebin.com/fgZf32p1

**Comment by seishun** [comment]
The issue tracker is not a help desk.
