### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by EduardChernikh** [seishun/node-steam#189]
Hi guys.

Yesterday, I tried to make a simple steam-bot using your nodejs module. I just copied your code from the readme. And after the launch there was an error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Disconnected
    at SteamClient._disconnected (/home/ubuntu/workspace/node_modules/steam/lib/steam_client.js:196:24)
    at Connection.emit (events.js:107:17)
    at TCP.close (net.js:485:12)

Here is code:
var Steam = require('steam');

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: 'rretard',
    password: 'password'
  });
});

steamClient.on('logOnResponse', function(e) {
  console.log(e);
}); 

Can you help me? Thanks.

**Comment by seishun** [comment]
example.js is not a complete solution, you should read the docs too.

>Connection closed by the server. Only emitted if the encryption handshake is complete, otherwise it will reconnect automatically. loggedOn is now false.

If you look at your 'logOnResponse' output you'll probably see why the logon failed, probably Steam Guard related.

**Comment by lparamonov** [comment]
EduardChernikh, have you found a solution?
