### ISSUE TITLE
Two factor auth?

### ISSUE THREAD

**Issue by Maxorq** [seishun/node-steam#190]
can't find anything about it, is it supported in any form?

**Comment by scholtzm** [comment]
Yes, it's possible.

https://github.com/seishun/node-steam/tree/master/lib/handlers/user#logonlogondetails
https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L90

I have it implemented [here](https://github.com/scholtzm/vapor/blob/develop/lib/handlers/logOnResponse.js#L71).

**Comment by seishun** [comment]
Assuming @scholtzm is correct, then it's already supported. You're welcome to add information about it to the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs).

**Comment by scholtzm** [comment]
@seishun Forgot about the wiki. Added. :+1:

**Comment by TrueCarry** [comment]
Trying to login with two factor, after successful authorization trying one again without code, steam saying I need code. Sentry file doesn't work for two factor or I'm doing something work?

**Comment by scholtzm** [comment]
"Use the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon), Luke."
