### ISSUE TITLE
 Immediately disconnect after connection

### ISSUE THREAD

**Issue by GrushinEgor** [seishun/node-steam#191]
Log:
2015-07-21T00:18:54.797Z - info: Steam client connecting...
2015-07-21T00:19:26.755Z - info: Steam client connected
2015-07-21T00:19:26.755Z - info: Steam user loggin on...
2015-07-21T00:19:31.487Z - info: Steam client disconnected

Code:

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamFriends = new Steam.SteamFriends(steamClient);
logger.info("Steam client connecting...");
steamClient.connect();
steamClient.on('connected', function() {
    logger.info("Steam client connected");
    logger.info("Steam user loggin on...");
    steamUser.logOn({
        account_name: account_name,
        password: password
    });
});

steamClient.on('error', function(e) {
    logger.info("Steam client disconnected");
    // logger.info('Question a steam guard code');
    // rl.question('Steam Guard Code: ', function(code) {
    //     logger.info("Steam client connecting...");
    //     steamClient.connect();
    //     logger.info('Try logging on again');
    //     steamUser.logOn({
    //         account_name: account_name,
    //         password: password,
    //         auth_code : code
    //     });
    // });
    
});

**Comment by GrushinEgor** [comment]
Added this code:
var readline   = require('readline');

var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});
steamClient.on('logOnResponse', function(logonResp) {

    logger.info("Log on result: " + logonResp.eresult);
    debugger;

    if(logonResp.eresult == Steam.EResult.AccountLogonDenied ){
       logger.info('Question a steam guard code');
       rl.question('Steam Guard Code: ', function(code) {
        logger.info("Steam client connecting...");
        steamClient.connect();
        logger.info('Try logging on again');
        steamUser.logOn({
            account_name: account_name,
            password: password,
            auth_code : code
        });
    }); 
   }

   if (logonResp.eresult == Steam.EResult.OK) {
       logger.info('Log on!');
    steamFriends.setPersonaState(Steam.EPersonaState.Online); // to display your bot's status as "Online"
    steamFriends.setPersonaName('Wimmness'); // to change its nickname
}
});

Now I get this log:

**Comment by scholtzm** [comment]
If you attempt to log in with incorrect password, missing auth code/sentry file etc., you will get automatically disconnected from Steam network.

You can prevent the `error` event by calling `client.disconnect()` if `logOnResponse.eresult !== OK`.

**Comment by seishun** [comment]
Well he's already handling 'error' so disconnecting manually won't change much. There is nothing you can do about the Steam server disconnecting you, it's how it works. You have to reconnect to log in with correct credentials.

**Comment by GrushinEgor** [comment]
steamClient.on('connected', function() {
    logger.info("Steam client connected");
    logger.info("Steam user loggin on...");

    steamUser.logOn({
        account_name: account_name,
        password: password
    });
});

steamClient.on('logOnResponse', function(logonResp) {

    logger.info("Log on result: " + logonResp.eresult);
    if (logonResp.eresult == Steam.EResult.OK) {
        logger.info('Log on!');
        steamFriends.setPersonaState(Steam.EPersonaState.Online); // to display your bot's status as "Online"
        steamFriends.setPersonaName('Wimmness'); // to change its nickname
    }else{
        logger.info("Disconnect from steam");
        steamClient.disconnect();
    }
    
    if(logonResp.eresult == Steam.EResult.AccountLogonDenied){
        logger.info('Question a steam guard code');
        rl.question('Steam Guard code: ', function(answer){
            logger.info('Answer: a steam guard code is' + answer);
            logger.info("Steam client connecting...");
            steamClient.connect();
            logger.info('Try logging on again');
            steamUser.logOn({
                account_name: account_name,
                password: password,
                auth_code: answer
            });
        });
    }
});


LogOn method executed from 'connected' (without auth_code) event always, even after logon with auth_code. How can I change my code, to fix this problems?

**Comment by GrushinEgor** [comment]
Made it like this:
steamClient.on('connected', function() {
    logger.info("Steam client connected");
    if (auth_code == undefined){
        logger.info('Steam user logging on...');
        steamUser.logOn({
            account_name: account_name,
            password: password
        });
    }else{
        logger.info('Steam user logging on with auth code...');
        steamUser.logOn({
            account_name: account_name,
            password: password,
            auth_code: auth_code
        });
    }
});
