### ISSUE TITLE
Illegal buffer error when log on with sentryFile

### ISSUE THREAD

**Issue by GrushinEgor** [seishun/node-steam#192]
Getting Illegal buffer error when logging on with sentryFile. Why?
![asda](https://cloud.githubusercontent.com/assets/6255315/8801354/0d97b992-2fcb-11e5-9903-c8fa1d96be9c.png)

**Comment by scholtzm** [comment]
Are you handling `updateMachineAuth` event correctly?

Also, this is an issue tracker. You should post your questions here: https://github.com/steam-forward/node-steam-forum/issues

**Comment by GrushinEgor** [comment]
steamUser.on('updateMachineAuth', function(newSentryHash){
    logger.info('Accept SentryHash.');
    sentryHash = newSentryHash;
    fs.writeFile('sentryfile.' + account_name + '.hash', JSON.stringify(sentryHash),function(err) {
        if(err){
            logger.error('Doesnt saved because ' + err);
        } else {
            logger.info('Saved sentry file hash as "sentryfile"');
        }
    });
})

**Comment by scholtzm** [comment]
You might want to [read the docs](https://github.com/seishun/node-steam/tree/master/lib/handlers/user#updatemachineauth) again.

**Comment by GrushinEgor** [comment]
I see nothing in it that can help me

**Comment by GrushinEgor** [comment]
"Call callback with a CMsgClientUpdateMachineAuthResponse object to accept this sentry update."

Can you tell me, what I gonna do?

**Comment by GrushinEgor** [comment]
Without Json stringify I got just [object Object]

**Comment by seishun** [comment]
https://github.com/SteamRE/SteamKit/blob/6aa47f764c796a1373a047cd30540c206943fcae/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L73

>	optional bytes sha_sentryfile = 83;

https://github.com/seishun/node-steam/blob/9ce470efa9c84ce9ce216a890059c96cb65604f3/README.md#protobufs

>bytes fields: Buffer objects

`sha_sentryfile` must be a Buffer object, but you're using the result of a `JSON.parse` call, which is not a Buffer.

Please read the docs and the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs).

**Comment by GrushinEgor** [comment]
Screenshot in top of thread proofs that I'm using Buffer object(reading a 'bytes' property)

**Comment by seishun** [comment]
After converting it to JSON and back it's no longer a Buffer.

**Comment by GrushinEgor** [comment]
Alright, Tell me, please, HOW I must save input parameter on event 'updateMachineAuth'?

**Comment by scholtzm** [comment]
This is how I handle it:
[event](https://github.com/scholtzm/vapor/blob/master/lib/handlers/updateMachineAuth.js)
[logOn](https://github.com/scholtzm/vapor/blob/master/lib/handlers/connected.js)

**Comment by GrushinEgor** [comment]
Now it's works. Thanks! There is no information about crypto on official documentation..

**Comment by scholtzm** [comment]
It's mentioned in the wiki: https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon

**Comment by mk-pmb** [comment]
Unfortunately, the example links in your comment from Jul 21, 2015 are 404 now.
