### ISSUE TITLE
Partner inventory

### ISSUE THREAD

**Issue by mirko-lazarevic** [seishun/node-steam#194]
Hi, 
is it possible to get partner's inventory?

**Comment by scholtzm** [comment]
Yes it's possible, but not directly with node-steam.

You will either have to write your own code or use a third party module.

**Comment by Alex-Nabu** [comment]
https://github.com/seishun/node-steam-trade

https://github.com/Alex7Kom/node-steam-tradeoffers

**Comment by seishun** [comment]
Not a node-steam question.
