### ISSUE TITLE
Bot isn't online in steam

### ISSUE THREAD

**Issue by MajorErection** [seishun/node-steam#199]
Okay so I finally managed to get my bot to not give out any errors, but after the bot starts, I can't do anything since the bot isn't showing up as online on steam. Here is my code, 

 console.log("Logging in to Steam...")

         var steamClient = new Steam.SteamClient();
         var steamTrade = new SteamTrade();
         var steamUser = new Steam.SteamUser(steamClient);

    steamClient.connect();

    steamClient.on('sentry', function (sentryhash) {
    require('fs').writeFile('sentryfile', sentryHash, function (err) {
        if (err) {
            console.log(err);
        } else {
            console.log('Saved sentry file hash as "sentryfile"');
            }
        });
    });

    steamUser.logOn({
        account_name: config.steam.accountName,
        password: config.steam.password,
        sha_sentryfile: fs.readFileSync('sentryfile'),
    });

**Comment by andrewda** [comment]
You're going to need to use the `logOnResponse` event.

    steamClient.on('logOnResponse', function(logonResp) {
        if (logonResp.eresult == Steam.EResult.OK) {
            console.log('Logged in!');
            steamFriends.setPersonaState(Steam.EPersonaState.Online); // to display your bot's status as "Online"
        }
    });

**Comment by seishun** [comment]
What @andrewda said. And there is no 'sentry' event FYI.

**Comment by MajorErection** [comment]
@seishun I followed #20 for saving the sentry. Is it not applicable anymore?

**Comment by seishun** [comment]
No, it's for pre-1.0.0. See https://github.com/seishun/node-steam/releases/tag/v1.0.0

**Comment by MajorErection** [comment]
What should I do to fix it? Just replace 'sentry' with 'updateMachineAuth'? I'm sorry but I have no idea how the sentryfile works at all. I don't mean to be annoying.

**Comment by seishun** [comment]
All of that is described in the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs). Store `bytes`, call `callback` with SHA1 of `bytes`, log on with SHA1 of `bytes`.

**Comment by MajorErection** [comment]
I still don't know what to do but it's alright I'll try figure it out.. Thanks anyways

**Comment by scholtzm** [comment]
I provided an example here: https://github.com/seishun/node-steam/issues/192#issuecomment-123434938

**Comment by MajorErection** [comment]
@scholtzm I appreciate your help but I guess I'm too dumb to figure out what to do :/ Thanks a lot anyways

**Comment by andrewda** [comment]
This should be all you need to create your sentry.
    steamUser.on('updateMachineAuth', function(sentry, callback) {
        fs.writeFileSync('sentry', sentry.bytes);
        callback({ sha_file: getSHA1(sentry.bytes) });
    });

    function getSHA1(bytes) {
        var shasum = crypto.createHash('sha1');
        shasum.end(bytes);
        return shasum.read();
    }
