### ISSUE TITLE
How to save sentry

### ISSUE THREAD

**Issue by trevorstarick** [seishun/node-steam#20]
I can't find any clear documentation on how to save the sentry file after logging in. Am I missing something or has that feature been removed?

**Comment by doged** [comment]
this sentryfile is a bunch of special characters.. that doesnt seem right.. when i pull using a diff js i get a long string of numbers and letters.. which is correct?

**Comment by scholtzm** [comment]
It's a random blob of data, it's not supposed to be human-readable.

You can interpret the data in many ways and it will "look" different, obviously.
