### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by gngeorgiev** [seishun/node-steam#201]
Can I login with a proxy?

**Comment by scholtzm** [comment]
https://github.com/seishun/node-steam/issues/140

**Comment by seishun** [comment]
Can you explain why you need to use proxy?

**Comment by gngeorgiev** [comment]
Because I need to login from more than one account from a single machine.

**Comment by seishun** [comment]
You can do that without a proxy.

**Comment by gngeorgiev** [comment]
Yes, but I do not want to risk the accounts as I have heard that steam is not very happy about such cases.

**Comment by seishun** [comment]
I've never heard of that. Also, using proxies explicitly violates the Steam Subscriber Agreement, so I'd be more worried about that.
