### ISSUE TITLE
Not reading sentry data

### ISSUE THREAD

**Issue by dragonbanshee** [seishun/node-steam#203]
I'm having some issues reading the sentry data for my bots. I am reading it the same way as before 1.0.0, but it isn't working anymore. 

Here's my code for writing the sentry:
```javascript
prototype._onUpdateMachineAuth = function (res) {
    fs.writeFileSync(this.sentryfile, res); //this.sentryfile is the name of the 
}
```

And for logging in/reading the sentry:
```javascript
prototype.logOn = function () {
    var that = this;
    that.logger.debug('Logging in bot ' + that.username);
    try {
        if (that.guardCode) {
            that.steamUser.logOn({
                account_name: that.username,
                password: that.password,
                auth_code: that.guardCode,
                sha_sentryfile: (fs.existsSync(that.sentryfile) ? fs.readFileSync(that.sentryfile) : undefined)
            });
        }
        else {
            that.steamUser.logOn({
                account_name: that.username,
                password: that.password,
                sha_sentryfile: (fs.existsSync(that.sentryfile) ? fs.readFileSync(that.sentryfile) : undefined)
            });
        }
    }
	catch (err) {
        that.logger.error('Error: ' + err.stack);
    }
}
```

Any help would be appreciated, as logging in with steamguard every single time is annoying. Thanks.

**Comment by scholtzm** [comment]
The docs are pretty clear on this: https://github.com/seishun/node-steam/tree/master/lib/handlers/user#updatemachineauth

You need to "accept" the sentry file and you also need to manually calculate the SHA-1.

I have posted an example in the comment here: https://github.com/seishun/node-steam/issues/192#issuecomment-123434938

**Comment by seishun** [comment]
Can you explain what's not clear from the [docs](https://github.com/seishun/node-steam/tree/master/lib/handlers/user) and the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs)?
