### ISSUE TITLE
Bot gets stuck after  console.log("Steam Client Connected")

### ISSUE THREAD

**Issue by MajorErection** [seishun/node-steam#204]
So after following #199 I updated my code and now after  console.log("Steam Client Connected") my bot does nothing for a minute or so then disconnects. Am I missing anything?

 console.log("Steam Client Connecting")

         var steamClient = new Steam.SteamClient();
         var steamTrade = new SteamTrade();
         var steamUser = new Steam.SteamUser(steamClient);

         steamClient.connect();

    console.log("Steam Client Connected")

    steamUser.on('updateMachineAuth', function(sentry, callback) {
        fs.writeFileSync('sentryfile', sentry.bytes, function (err) {
            if (err) {
                return console.log(err);
            }

            console.log("The file was saved!");
        });

        callback({ sha_file: getSHA1(sentry.bytes) });
    });

    function getSHA1(bytes) {
        var shasum = crypto.createHash('sha1');
        shasum.end(bytes);
        return shasum.read();

**Comment by seishun** [comment]
Did you read the documentation for [connect](https://github.com/seishun/node-steam#connect), ['connected'](https://github.com/seishun/node-steam#connected-1) and the [example code](https://github.com/seishun/node-steam/blob/master/example.js)?

**Comment by scholtzm** [comment]
> Am I missing anything?

- You are not handling `connected` event.
- You are not logging in.

Also `writeFileSync` does not accept callback argument.

**Comment by MajorErection** [comment]
Sorry here's the whole thing

         var steamClient = new Steam.SteamClient();
         var steamTrade = new SteamTrade();
         var steamUser = new Steam.SteamUser(steamClient);

         steamClient.connect();

    console.log("Steam Client Connected")

    steamUser.on('updateMachineAuth', function(sentry, callback) {
        fs.writeFileSync('sentryfile', sentry.bytes );

        callback({ sha_file: getSHA1(sentry.bytes) });
    });

    function getSHA1(bytes) {
        var shasum = crypto.createHash('sha1');
        shasum.end(bytes);
        return shasum.read();

      console.log("Steam User Connecting")

        steamClient.on('connected', function () {
            steamUser.logOn({
                account_name: config.steam.accountName,
                password: config.steam.password,
                sha_sentryfile: fs.readFileSync('sentryfile'),
            });
        });

        steamClient.on('logOnResponse', function (logonResp) {
            if (logonResp.eresult == Steam.EResult.OK) {
                console.log("Steam User Connected")
                steamFriends.setPersonaState(Steam.EPersonaState.Online); 
            }
        });

**Comment by seishun** [comment]
Are you really adding a handler for 'connected' inside getSHA1?

**Comment by MajorErection** [comment]
I fixed it I guess..but now it gets an error an disconnects immediately

    var steamClient = new Steam.SteamClient();
    var steamTrade = new SteamTrade();
    var steamUser = new Steam.SteamUser(steamClient);

   steamClient.connect();

    console.log("Steam Client Connected")

    steamUser.on('updateMachineAuth', function(sentry, callback) {
      fs.writeFileSync('sentryfile', sentry.bytes );

        callback({ sha_file: getSHA1(sentry.bytes) });
    });

    function getSHA1(bytes) {
        var shasum = crypto.createHash('sha1');
        shasum.end(bytes);
        return shasum.read(); };
        
     console.log("Steam User Connecting")

     steamClient.on('connected', function () {
         steamUser.logOn({
             account_name: config.steam.accountName,
             password: config.steam.password,
             sha_sentryfile: fs.readFileSync('sentryfile'),
        });
     });
                steamClient.on('logOnResponse', function (logonResp) {
                    if (logonResp.eresult == Steam.EResult.OK) {
                        console.log("Steam User Connected")
                        steamFriends.setPersonaState(Steam.EPersonaState.Online); 
                    }
                });

**Comment by seishun** [comment]
That's normal, you get disconnected if logon failed. Check your `logonResp.eresult` value.

**Comment by MajorErection** [comment]
What do you mean? Sorry I'm so needy :/

**Comment by seishun** [comment]
If the `eresult` field is not equal to `EResult.OK`, then the logon wasn't successful. The value of `eresult` should tell you what went wrong.

**Comment by andrewda** [comment]
steamClient.on('logOnResponse', function (logonResp) {
        console.log(logonResp.eresult);
        if (logonResp.eresult == Steam.EResult.OK) {
            console.log("Steam User Connected")
            steamFriends.setPersonaState(Steam.EPersonaState.Online); 
        }
    });

**Comment by MajorErection** [comment]
Okay, I solved that and my bot is on but when I send a trade request my bot still has the 7 day ban, is there no way to bypass that?

**Comment by scholtzm** [comment]
Unless you re-use older sentry file, no.

**Comment by MajorErection** [comment]
Is there a place I can someone else's old sentryfile?

**Comment by seishun** [comment]
Steam Guard restrictions are outside the scope of this library, please discuss them elsewhere (e.g. [SteamRE group](http://steamcommunity.com/groups/SteamRE) or #opensteamworks on irc.gamesurge.net).
