### ISSUE TITLE
Log in with Open ID?

### ISSUE THREAD

**Issue by krazyjakee** [seishun/node-steam#206]
I want to create a browser based chat client for steam and I don't want users to enter a username/password every time.

I have OpenID [(Steam Sign in)](http://steamcommunity.com/dev).
How can I authenticate with node-steam using only stored authentication using openid?

**Comment by scholtzm** [comment]
OpenID only returns user's SteamID, nothing else.

You won't be able to send messages on other users behalf.

**Comment by krazyjakee** [comment]
No auth token or anything that can be used?

**Comment by scholtzm** [comment]
It literally only gives you the ID and nothing else.

**Comment by krazyjakee** [comment]
@scholtzm thanks dude.
I will find a different approach as I don't think people will want to type their password into a form on my website :+1:
