### ISSUE TITLE
Is sentry removed?

### ISSUE THREAD

**Issue by dolanmiu** [seishun/node-steam#209]
In version 1.x.x, you had sentry file (shaSentryfile), and authcode in logOn, however, it seems like you removed it in version 2. 

Does this mean we do not need to use sentry files in 2.x?

I only see account_name (previously accountName) and password for the logOn parameters.

I cannot move onto version 2 without these things. I really cannot be bothered to enter my steam guard code every time.

I hope you understand.

**Comment by graceda** [comment]
at last i was searching for this, but i found out that the developer changed the method for "sentry", for more info you can read it here https://github.com/seishun/node-steam/releases/tag/v1.0.0.

**Comment by graceda** [comment]
#192 read this too.

**Comment by dolanmiu** [comment]
Interesting, but I want a logOn which TAKES in sentry and authcode paramters? Not as an event.

Otherwise there will be a lot of refactoring, and our company has spent a lot of hours on this, and it would be a shame if we had to rewrite all this section, and do all the regression tests etc. My boss won't be happy that's for sure.

i don't see what value version 2.0 brings apart from breaking everyone's code

**Comment by scholtzm** [comment]
Read: https://github.com/seishun/node-steam/issues/203

> i don't see what value version 2.0 brings apart from breaking everyone's code

You don't have to update from 0.6.8. It will work just time for the time being.

**Comment by dolanmiu** [comment]
Yes 1.0, my bad, I was thinking of node-tradeoffers, which is at 2.0, which I am also having problems with. But will deal with node-steam first

**Comment by seishun** [comment]
I find it pleasantly surprising that someone is using this library for enterprise software.

Nothing was "removed" from `logOn` - instead, it was reworded to take a [CMsgClientLogon](https://github.com/SteamRE/SteamKit/blob/6aa47f764c796a1373a047cd30540c206943fcae/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L45-L91) object. You can set any fields you want from there, including `sha_sentryfile`. Some fields are described [here](https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon).
