### ISSUE TITLE
Steam Error: undefined

### ISSUE THREAD

**Issue by WeeSkilz** [seishun/node-steam#210]
I'm having an issue as follows

root@vultr:/home# node app.js
connected
error:  Error: Disconnected
    at SteamClient._disconnected (/home/node_modules/steam/lib/steam_client.js:196:24)
    at Connection.emit (events.js:107:17)
    at TCP.close (net.js:485:12)
error: Steam Error: undefined

Was wondering what's causing an error without a code?

**Comment by seishun** [comment]
> error: Steam Error: undefined

That's something coming from your own code. And there is no code in ['error'](https://github.com/seishun/node-steam#error).
