### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by zhuharev** [seishun/node-steam#213]
I try run example(`node example.js`) and recieve error:

    var cryptedSessionKey = crypto.publicEncrypt(publicKey, sessionKey);
    TypeError: Object #<Object> has no method 'publicEncrypt'

**Comment by andrewda** [comment]
You're need to be using Node.js v0.12.0 or higher for node-steam to work. To easily upgrade to Node v0.12.0:

```
npm install nvm
nvm install v0.12.0
```

**Comment by scholtzm** [comment]
@andrewda Just fyi, the npm version is outdated - v0.0.3 in npm vs. v0.25.4 in the [repo](https://github.com/creationix/nvm). Definitely use the repo version.

**Comment by zhuharev** [comment]
@andrewda, @scholtzm thanks for the help
