### ISSUE TITLE
No license field.

### ISSUE THREAD

**Issue by illum1nate** [seishun/node-steam#217]
D:\Projects\node-steam [master +0 ~1 -0]> npm install steam
npm WARN package.json steam@1.1.0 No license field.
npm WARN install Refusing to install steam as a dependency of itself

I wrote in Git Shell.

**Comment by scholtzm** [comment]
I reported this to @seishun ages ago :grinning:

Also, if you want to install dependencies, you should only run `npm install`, not `npm install steam`.

**Comment by illum1nate** [comment]
I have problem again(((
Error: Disconnected
    at SteamClient._disconnected (D:\Projects\steam_bot\node_modules\steam\lib\steam_client.js:196:24)
    at Connection.emit (events.js:107:17)
    at TCP.close (net.js:485:12)


what does it mean?

**Comment by scholtzm** [comment]
Read the docs: https://github.com/seishun/node-steam#error

**Comment by baimurzin** [comment]
@illum1nate It seems you should pass the auth_code from email or sentry file.

**Comment by seishun** [comment]
Closing since the issue wasn't related to the missing field. But I guess I should add it at some point.
