### ISSUE TITLE
requestFriendData not working

### ISSUE THREAD

**Issue by TrueCarry** [seishun/node-steam#218]
Return contains only steamid, name, avatar hash and last logon/logoff dates. Tried all status codes, nothing helps.

**Comment by seishun** [comment]
The library just gives you whatever it receives from Steam. As far as I remember, that's all the data you can get when requesting data manually.

**Comment by TrueCarry** [comment]
So there's no way to know which friends are online?

**Comment by seishun** [comment]
AFAIK information about online friends is sent by Steam automatically upon logging on. It should contain `persona_state`.
