### ISSUE TITLE
Protobuf error

### ISSUE THREAD

**Issue by TrueCarry** [seishun/node-steam#222]
I'm trying to make node-csgo compatible with node-steam>1.0. If steam installed separately everything works, but if it installed in node-csgo node_modules directory error occuring:
```bash
/home/gittest/node-csgo/node_modules/protobufjs/dist/ProtoBuf.js:2949
    clone[i] = cloneRaw(value, binaryAsBase64, longsAsStrings, field.type, fie
                                                                    ^
TypeError: Cannot read property 'type' of undefined
    at cloneRaw (/home/gittest/node-csgo/node_modules/protobufjs/dist/ProtoBuf.js:2949:97)
    at cloneRaw (/home/gittest/node-csgo/node_modules/protobufjs/dist/ProtoBuf.js:2949:44)
    at MessagePrototype.toRaw (/home/gittest/node-csgo/node_modules/protobufjs/dist/ProtoBuf.js:2964:28)
    at Object.Steam._processProto (/home/gittest/node-csgo/node_modules/steam/lib/steam_client.js:21:17)
    at SteamClient._netMsgReceived (/home/gittest/node-csgo/node_modules/steam/lib/steam_client.js:151:26)
    at SteamClient.handlers.(anonymous function) (/home/gittest/node-csgo/node_modules/steam/lib/steam_client.js:270:10)
    at SteamClient._netMsgReceived (/home/gittest/node-csgo/node_modules/steam/lib/steam_client.js:168:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/home/gittest/node-csgo/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:104:17)
```
I tried removing steam folder, switch directory to /home/gittest/, run npm install node-steam and then run example.js, it works. Also I've tried to run command npm install protobufjs in /home/gittest/node-csgo/node_modules/steam/ and it also worked nice.

**Comment by TrueCarry** [comment]
Also
```bash 
npm install steam
npm install
```
works too.

**Comment by seishun** [comment]
Looks like dcodeIO/ProtoBuf.js#310. Why are you installing node-steam into the node-csgo directory though?

**Comment by TrueCarry** [comment]
I'm not installing it directly, just running npm install. Dependencies:
```json"
dependencies": {
  	"steam": "1.1.0",
	"protobufjs": "*",
    "deferred": "*",
    "bignumber.js": "^2.0.7"
  }
```

**Comment by seishun** [comment]
Does node-csgo depend on node-steam just for the example? You shouldn't do that.

**Comment by TrueCarry** [comment]
node-csgo depends node-steam for steam methods. Like logon. Also dependencies likes this works.
```json 
"dependencies": {
	"steam": "1.1.0",
    "protobufjs": "*",
    "deferred": "*",
    "bignumber.js": "^2.0.7",
	"bytebuffer": ">=3.5.5"
  }
```

**Comment by seishun** [comment]
node-csgo doesn't call any node-steam methods anywhere outside of example.js. If you want to specify that node-csgo is meant to be used _with_ node-steam, then add it to `peerDependencies`.

Any dependency configuration will work as long as ByteBuffer used by node-steam is physically the same module as ByteBuffer used by ProtoBuf.js used by node-steam. Otherwise ProtoBuf.js doesn't recognize the Long object. I assume that's a bug.

**Comment by TrueCarry** [comment]
Well node csgo using GC from steam
```javascript
this._gc.send({msg:CSGO.ECSGOCMsg.k_EMsgGCCStrike15_v2_MatchmakingClient2GCHello, proto: {}},
+      payload.toBuffer());
```
All messages are send through node-steam. Current version of node-csgo have node-steam as peerDependency, but since it will not work without node-steam connection to steam and game coordinator I think it should be dependency.

**Comment by seishun** [comment]
It uses the GameCoordinator object provided by the user, it doesn't create it itself. It doesn't need `steam` inside its `node_modules`, so it shouldn't be a dependency.

**Comment by TrueCarry** [comment]
Ok, done. Thank you for help.

**Comment by paralin** [comment]
I'm having this problem from within a project that uses node-steam.

**Comment by paralin** [comment]
I've linked node-steam in via `npm link` because I'm working on developing it, though.

**Comment by TrueCarry** [comment]
@paralin, add 
```
"bytebuffer": ">=3.5.5"
```
To your dependencies, it should help.

**Comment by seishun** [comment]
node-steam master and node-steam-resources now both use ByteBuffer.js 4.1, where this problem was fixed.
