### ISSUE TITLE
Listen for sent offer status changes

### ISSUE THREAD

**Issue by voyik** [seishun/node-steam#223]
Hello, how can i listen event on status changes of tradeoffer wich i sent to other steamid or get numbers of sended tradeoffers?

```javascript
			offers.getOffers({
				get_received_offers: 0,
				active_only: 0,
				get_sent_offers: 1
			},
```
this code dont work for me... and i can't understand why (

**Comment by seishun** [comment]
What's `offers.getOffers`? I think you're posting in the wrong repo.

**Comment by voyik** [comment]
sorry, i mean 
```javascript
steamUser.on('tradeOffers', function(number) {
	console.log( 'new trades:' + number );
});
```

**Comment by pmk010** [comment]
That event fires when the number of pending incoming trade offers changes, not outgoing trade offers.

**Comment by voyik** [comment]
ok) thank u.   

i think i need to make an array with outgoing trade offers id  and with setInterval  get statuses of this trade offers ...  is that right ?
