### ISSUE TITLE
SteamGuard authcode broke connection

### ISSUE THREAD

**Issue by Okalmus** [seishun/node-steam#225]
I got error :

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Disconnected
    at SteamClient._disconnected (/var/www/node/node_modules/steam/lib/steam_client.js:196:24)
    at Connection.emit (events.js:107:17)
    at TCP.close (net.js:485:12)

when using auth_code parameter with the correct authcode then call steamUser.logOn ,
logOnOptions.auth_code = authCode;
steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn(logOnOptions);
});

Seems that this bug comes from your api, i'm using original Alex7Kom's trade script (https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/offerbot.js)
and all is working good without SteamGuard activated

**Comment by seishun** [comment]
https://github.com/seishun/node-steam#error

As for why Steam disconnected you, likely due to failed logon. See 'logOnResponse'.

**Comment by Okalmus** [comment]
Error 63 all times, even with the good auth code
