### ISSUE TITLE
my gc recieved header.msg 24, what's that?

### ISSUE THREAD

**Issue by TJRoger** [seishun/node-steam#226]
I cannot receive any response for `EDOTAGCMsg.k_EMsgGCFindSourceTVGames`, message `CMsgFindSourceTVGames` and `EDOTAGCMsg.k_EMsgClientToGCFindTopSourceTVGames` ,message `CMsgClientToGCFindTopSourceTVGames`

**Comment by seishun** [comment]
The library just passes data as-is. Unless you think the response is actually received and not handled correctly by the library, this is not a question for the issue tracker. You can discuss the Steam protocol in the [SteamRE group](http://steamcommunity.com/groups/SteamRE) or in #opensteamworks on irc.gamesurge.net.

**Comment by TJRoger** [comment]
@seishun I received the gc message by listening to the gc of this node-steam, but It's not in my handlers which shouldn't arrived to me. This is my code listen for it
```
this._gc.on('message', function(header, body, callback) {
        debuglog('received gc message: '+header.msg);
        debuglog(body,'body');
        if (header.msg in self._handlers){
            debuglog('received dota2 message: '+header.msg);
            handlers[header.msg].call(this, body, callback);
        }else {
            this.emit('unhandled', header, body, callback);
        }
    }.bind(this));
```
this is the console message:
```
received gc message: 24
body: 
<Buffer 12 8c ce 01 08 01 12 2a 08 8a bb ff b4 06 10 ca 9b be 29 18 cc 80 80 80 08 20 9b 2a 38 04 48 06 62 09 08 99 01 1a 04 00 00 80 3f 92 01 04 08 12 10 02 ... >
```

**Comment by seishun** [comment]
GC can send messages on its own without being prompted. [This file](https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/dota/gcsystemmsgs.proto) suggests that 24 is "k_ESOMsg_CacheSubscribed".

**Comment by TJRoger** [comment]
Oh, I see. thanks
