### ISSUE TITLE
Missing webTradeEligibility in cookie

### ISSUE THREAD

**Issue by saifbechan** [seishun/node-steam#228]
Hello, first of all thanks for the great work. I am using this module for about two years now without any problems, kudos!

One thing that would come in handy for me is if it would be possible to get the value of webTradeEligibility in my cookie when I use the webLogOn functionality. Now I know the module is now split up under the project node-steam-weblogon but I think the source of getting the cookies still resides node-steam. If this is better handled by the developer of node-steam-weblogon I will raise a request there.

The way I fix this is my application is just by adding my own  + '; webTradeEligibility=' to the cookies, which I generate in the browser, but if this could be done automatically it would be amazing.

**Comment by scholtzm** [comment]
> I think the source of getting the cookies still resides node-steam. If this is better handled by the developer of node-steam-weblogon I will raise a request there.

You will have to post your issue there. `node-steam` only provides the [nonce](https://github.com/seishun/node-steam/tree/master/lib/handlers/user#requestwebapiauthenticateusernoncecallback) which is used for logging in.

**Comment by seishun** [comment]
A look at the node-steam-weblogon source code shows that all the cookies come from WebAPI. You should post your request there.

**Comment by scholtzm** [comment]
I checked the response and it only contains those 2 cookies and nothing else.
