### ISSUE TITLE
CMsgClientEmoticonList not implemented

### ISSUE THREAD

**Issue by meepdarknessmeep** [seishun/node-steam#229]
https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/steamclient/steammessages_clientserver_2.proto#L1133-L1140

would be great to make a chat relay

**Comment by scholtzm** [comment]
?Have you tried https://github.com/seishun/node-steam#messagesend ?

**Comment by meepdarknessmeep** [comment]
I've no clue how any of that works, sorry.

**Comment by seishun** [comment]
See [#40 (comment)](https://github.com/seishun/node-steam/issues/40#issuecomment-148388895). If you have trouble understanding 'message'/send, try looking at the bundled handlers and see how they use the low-level API. If you have any follow-up questions, feel free to post them in this issue.
