### ISSUE TITLE
Steam Trade Bot Error

### ISSUE THREAD

**Issue by serega990306** [seishun/node-steam#233]
I made a Steam Tread Bot for cs go site. But when I send trade offer to the bot, I see this in the console
![e925944653fb3e112c94af80522f64bd663ab35c772078b8a9 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/9691428/9428190/4808bc9a-49e6-11e5-9aea-29c09268ed3b.jpg)
What means web authentication 403 retrying, and whant i must do?

**Comment by seishun** [comment]
This is not a help desk.
