### ISSUE TITLE
logon fail: 18

### ISSUE THREAD

**Issue by doged** [seishun/node-steam#235]
where can i find a list of fail codes?

suddenly a bot that i've had running on steam for months logged off, and is giving me a logon error 18.

**Comment by buddhapest** [comment]
i find this useful: https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd

18 is "AccountNotFound" - prolly 'cause steam just had a massive outage.

**Comment by doged** [comment]
ah ok, thanks for the quick response @buddhapest i think you are right, and that list is EXACTLY what i was looking for =]

**Comment by seishun** [comment]
There's a link to it [here](https://github.com/seishun/node-steam#enums).
