### ISSUE TITLE
Error: Disconnected (EResult 5)

### ISSUE THREAD

**Issue by mantux5** [seishun/node-steam#236]
I have no idea what has happened. I launched the bot normally and it worked just fine. After I restarted it, for some reason it always Disconnects wit the reason: Invalid Password. I have tested and copy-pasted the correct login information. I can login myself with that username and password. However, it throws that Error 5 (Eresult) whenever I try to login using node-steam.
```
{ eresult: 5,
  eresult_extended: 5,
  client_supplied_steamid: 'HIDDEN FOR PRIVACY',
  count_loginfailures_to_migrate: 0,
  count_disconnects_to_migrate: 0 }
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Disconnected
    at SteamClient._disconnected (/var/steam/node_modules/steam/lib/steam_client.js:196:24)
    at Connection.emit (events.js:107:17)
    at TCP.close (net.js:476:12)

```

**Comment by mantux5** [comment]
Nevermind. It seems Steam had some issues or something. Some time has passed and I'm able to log in again.

**Comment by tephro** [comment]
FYI. It is not a Steam issue. Just setup ntpd (or another time sync mechanism) on your machine and synchronize your server's time. It is 100% approved, that wrong server time cause "Invalid password" issue.
