### ISSUE TITLE
steamUser.logOn

### ISSUE THREAD

**Issue by TopicDEV** [seishun/node-steam#237]
Can't auth, log:
27 Aug 12:54:09 - Starting bot...
socket timed out
socket closed
connecting to 72.165.61.185:27018
socket timed out
socket closed
connecting to 146.66.152.14:27019
socket timed out
socket closed
connecting to 146.66.152.13:27019
socket timed out
socket closed
connecting to 146.66.152.12:27017
socket timed out
socket closed
connecting to 146.66.152.15:27019
socket timed out
socket closed
connecting to 146.66.152.14:27018
socket timed out
socket closed
connecting to 209.197.29.196:27017
connected
encrypt request
socket ended
socket closed
events.js:85
      throw er; // Unhandled 'error' event
            ^

Code: 
util.log("Starting bot...");
steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: username,
    password: password
  });
});

steamClient.on('debug', console.log);

**Comment by seishun** [comment]
It seems you're missing a few lines in your log. There should be a line stating the actual error and a stack trace.

**Comment by TopicDEV** [comment]
I'm add this:
steamClient.on('error', function(e) {
    console.log(e);
});

Log: 
27 Aug 13:07:37 - Starting bot...
socket timed out
socket closed
connecting to 72.165.61.174:27018
connected
encrypt request
socket ended
socket closed
[Error: Disconnected]

**Comment by seishun** [comment]
So Steam disconnected you, causing SteamClient to emit 'error', that's normal operation of the library. You might want to handle 'logOnResponse'.
