### ISSUE TITLE
Error: Illegal value for [object Object] of type message: number (object expected)

### ISSUE THREAD

**Issue by brenolf** [seishun/node-steam#239]
I'm trying `steamUser.gamesPlayed([207650]);` but I get this error. What should the format of the contents be? I couldn't find on your documentation.

**Comment by scholtzm** [comment]
Docs are [pretty clear](https://github.com/seishun/node-steam/tree/master/lib/handlers/user#gamesplayedgamesplayed) on this.

**Comment by brenolf** [comment]
I got it working by sending a json.
