### ISSUE TITLE
SteamGameCoordinator not opening game

### ISSUE THREAD

**Issue by fletchette** [seishun/node-steam#240]
Running `var game = new Steam.SteamGameCoordinator(client, 440);` however the game is not being launched.
Running after user is logged in. Client is a valid instance of Steam.SteamClient()

**Comment by seishun** [comment]
Creating a SteamGameCoordinator instance isn't supposed to launch the game. What gave you that idea?

**Comment by fletchette** [comment]
Misread documentation. I'm a tard.
Thanks for the response.
