### ISSUE TITLE
Why is SteamTrading constructor takes steamClient instead SteamUser?

### ISSUE THREAD

**Issue by baimurzin** [seishun/node-steam#243]
As I inderstood I may create several SteamUser based on only one SteamClient instance, right?
for example:
```javascript
    var steam = new Steam.SteamClient(); 
    var user = new Steam.SteamUser(steam); 
    var use2 = new Steam.SteamUser(steam); 
    user.logOn({login: USER1, password: PASS1}); 
    user2.logOn({login: USER2, password: PASS2}); 
```

and for each created user I can get a trade offer? 
where am I wrong?

**Comment by scholtzm** [comment]
You'll need multiple Steam client instances as each client can only handle a single account.

**Comment by Lynxaa** [comment]
the best way that i've found to handle multiple users is to loop over an array of the login credentials.

```javascript
var accounts = [
	{
		username: "example",
		password: "example",
	}
];
```

Loop over the accounts array and then do all your logging in and instances, etc.

**Comment by seishun** [comment]
What @scholtzm said.
