### ISSUE TITLE
Access Denied.

### ISSUE THREAD

**Issue by darklordyang** [seishun/node-steam#245]
Hello guys, how can i fix this?
![epnkfyi](https://cloud.githubusercontent.com/assets/14205825/9773167/a4cb6e7a-56f5-11e5-8d5b-f050080cf1d9.png)

**Comment by andrewda** [comment]
Can we see your code? More specifically, the code on line 181?

**Comment by darklordyang** [comment]
yes sure here
![screenshot_1](https://cloud.githubusercontent.com/assets/14205825/9786525/86db36b4-576f-11e5-85dc-4399822d0d33.png)

**Comment by seishun** [comment]
This is not a help desk.
