### ISSUE TITLE
Understanding `Connection.prototype._readPacket`

### ISSUE THREAD

**Issue by filsmick** [seishun/node-steam#246]
Hi, I'm working on a Rust port of `node-steam`. A section of the code bugs me: https://github.com/seishun/node-steam/blob/master/lib/connection.js#L28-L34

You read 8 bytes, but only 4 are used to get the length. What does Steam use the other four for?

I'm not sure an issue is the best place to ask this, but I couldn't find another way to contact you.
Thanks in advance.

**Comment by scholtzm** [comment]
[It's all magic. :wink:](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Networking/Steam3/TcpConnection.cs#L294)

**Comment by filsmick** [comment]
Okay, so all packet headers are made of a little-endian unsigned length and the 'magic' VT01... I guess this is used to ensure both parties speak the same protocol?

**Comment by scholtzm** [comment]
I don't think it has any special meaning other than it's there and you can use it to identify the data if you wish. `node-steam` skips it completely as you can see.

**Comment by filsmick** [comment]
Alright. Thanks for the explanation! :)
