### ISSUE TITLE
example.js does not run

### ISSUE THREAD

**Issue by Oromus** [seishun/node-steam#252]
As far as I can tell, I have properly installed everything, but I am still getting this error:

http://pastebin.com/HzdRpjfh

I have not changed example.js at ALL.

**Comment by seishun** [comment]
That's #222, caused by dcodeIO/ProtoBuf.js#310. See [my comment](https://github.com/seishun/node-steam/issues/222#issuecomment-126909869) for a workaround.

**Comment by Oromus** [comment]
I'm not using node-csgo, though. I don't see what I need to fix.

**Comment by seishun** [comment]
It's not related to node-csgo. You probably just need to delete bytebuffer under steam/node_modules/protobufjs/node_modules.

**Comment by Oromus** [comment]
I don't have protobufjs in my steam/node_modules folder. I have "adm-zip", "buffer-crc32", "bytebuffer", "steam-crypto", and "steam-resources". If I delete the "bytebuffer" folder, example.js just crashes becase it can't find module "bytebuffer".

**Comment by seishun** [comment]
Oh, you installed from master. There should be protobufjs under steam-resources then.

**Comment by Oromus** [comment]
Sorry for seeming stupud, but I found the folder and there's no node_modules or bytebuffer folder anywhere. There's just a bunch of folders named after Steam games (i.e. csgo and portal2).

**Comment by seishun** [comment]
Run `node` inside the node-steam directory and type `require.resolve('protobufjs')`. This will show you where it is.

**Comment by Oromus** [comment]
Got an error, says it can't find the module.

http://pastebin.com/R2CdtRG1

**Comment by seishun** [comment]
From your previous paste:

>    at cloneRaw (C:\Program Files\nodejs\node_modules\steam\node_modules\steam-resources\node_modules\protobufjs\dist\ProtoBuf.js:2949:97)

That implies protobufjs exists under steam-resources/node_modules. Did you delete it?

**Comment by Oromus** [comment]
>I found the protobufjs folder under steam-resources, but there's no node_modules or bytebuffer folder anywhere. There's just a bunch of folders named after Steam games (i.e. csgo and portal2).

I don't know why require.resolve crashed, but the protobufjs folder does indeed exist. There's no bytebuffer folder as far as I can tell, however.

**Comment by seishun** [comment]
There is no bytebuffer directory under protobufjs/node_modules?

**Comment by Oromus** [comment]
There's not even a node_modules folder. http://i.imgur.com/AJxVRI8.png

**Comment by seishun** [comment]
Not "protobufs". Look under steam_resources/node_module/protobufjs.

**Comment by Oromus** [comment]
Found it. bufferbytes is in the same folder with it. If I delete that, I get this error instead:

http://pastebin.com/1RDLJtGf

bufferbytes is not in protovufjs/node_modules.

**Comment by seishun** [comment]
You fixed it. The error is correct behavior, see ['error'](https://github.com/seishun/node-steam#error) and ['logOnResponse'](https://github.com/seishun/node-steam#logonresponse).

**Comment by Oromus** [comment]
Oh, sweet! Thanks for taking the time to help me! Also, amazing response time!
