### ISSUE TITLE
Encryption Failure

### ISSUE THREAD

**Issue by WeeSkilz** [seishun/node-steam#253]
When trying to send a trade offer I get EResult 23 encryption failure. Could you advise as to any possible solutions?

**Comment by jabbink** [comment]
How are you sending your trade offer?

**Comment by WeeSkilz** [comment]
This is the dependency it boils down to, that's why I'm here.

This is the library with the EResult enums so it must be explained here somewhere.

I'll provide the snippet when home.

**Comment by seishun** [comment]
The EResult values come from Valve, so I can't help you. You might get help in #opensteamworks on irc.gamesurge.net.
