### ISSUE TITLE
Rich Presence request seems broken

### ISSUE THREAD

**Issue by TrueCarry** [seishun/node-steam#257]
I'm trying to implement request for rich presence. Code that I put to friends/index.js:
```javascript
SteamFriends.prototype.richPresenceRequest = function(steamids, callback){
  this._client.send({
        msg: EMsg.ClientRichPresenceRequest,
        proto: {}
      },
      new schema.CMsgClientRichPresenceRequest({
        steamid_request: steamids
      }).toBuffer(), callback);
};
```
```javascript
handlers[EMsg.ClientRichPresenceInfo] = function(data) {
  var response_kv = schema.CMsgClientRichPresenceInfo.decode(data);
  var buff = response_kv.rich_presence[0].rich_presence_kv;
  console.log(buff.buffer.toString('utf8'));
  var output = require('../../VDF').decode(response_kv.rich_presence[0].rich_presence_kv);
  this.emit('richPresenceInfo', { steamid: response_kv.rich_presence[0].steamid_user, status: output });
}
```
Handler works fine when rich presence info coming from steam automatically, but when I'm requesting it by myself only part of data is transfered, so vdf decoding fails.
Example of response:
```
	�Yb
  
```
Example of auto rich presence response:
```
�	�Yb
 � RP status Community Casual ze_jurassicpark_c1v4_p2 [ 0 : 3 ] version 13503 time 5576.756745 game:act community game:mode casual game:mapgroupname mg_bomb game:map ze_jurassicpark_c1v4_p2 game:score [ 0 : 3 ] game:server community 
```
I guess info coming in multiple packets, but how I should handle it?

**Comment by seishun** [comment]
I have no idea how rich presence works. Since your question is about Steam protocol rather than the library, #opensteamworks on irc.gamesurge.net would be a better place to discuss it.

**Comment by scholtzm** [comment]
Why are you even modifying the library?

https://github.com/seishun/node-steam#messagesend

**Comment by TrueCarry** [comment]
Well I've found a problem, this message requires routing_appid in header. Do you think rich presence dont belongs to steamFriends? I guess it could be implemented there because it's friends status related information.

**Comment by seishun** [comment]
SteamFriends is already huge, so I would prefer to avoid adding more stuff to it. Also, rich presence is somewhat special since it only works in-game. I think RP-related functionality (I see at least ClientRichPresenceInfo, ClientRichPresenceRequest and ClientRichPresenceUpload) should belong in a separate module.

**Comment by paralin** [comment]
We're going to implement it in node-dota2 soon, probably. I think individual game modules should implement it. It's very specific to what you're actually doing in the game.

**Comment by paralin** [comment]
Maybe the generic code for setting rich presence and building those objects belongs in this repository.

**Comment by seishun** [comment]
I could add a handler with dumb wrappers for those three messages, but my concern was that they wouldn't be very useful. But if you say that game-specific handlers could use them to implement higher-level functionality, then it's a different story. What other games besides Dota 2 use RP?

**Comment by TrueCarry** [comment]
In CS:GO you can get server type and score for player, in Dota just map/hero level. I think rich presence could be used in any game that supports friend interactions, but I dont think it's being used by someone besides valve. And rich presence is very unreliable. You can set any status you want with richPresenceUpload.
Also I don't know if it's already done, but when I searched I didn't find VDF encode function, so https://github.com/joshuaferrara/node-csgo/blob/master/VDF.js#L81 if you need. Works for basic messages atleast.

**Comment by paralin** [comment]
In dota it is very extensive, and they add more every day. There are embedded links to custom game modes, messages for queuing for a match, playing a game with hero, main menu, queuing for custom game, playing against bots.

**Comment by seishun** [comment]
@paralin would a handler with `upload` and `request` methods and an 'info' event that accept/provide `CMsgClientRichPresenceUpload`, `CMsgClientRichPresenceRequest` and `CMsgClientRichPresenceInfo` objects respectively be useful to node-dota2?

**Comment by TrueCarry** [comment]
Not sure if many people can find a way to use it, but we already did.
@seishun not sure if I should start new topic, maybe we can discuss it here. To use RP you need to be ingame(gamesPlayed), so when I tried to use csgo and dota2 simultaneously it turned out troublesome. I'm not sure if it's right thing to do but I just started to send
```
gamesPlayed({ games_played: [ { game_id: 730 }, { game_id: 570 } ] });
```
Maybe you can change gamesPlayed method, so when node-dota sending 570 first and then node-csgo sending 730 actual message contains both of them. It's the only thing that making node-csgo and node-dota2 unable to run simultaneously. Also csgo id should go first but it's valve magic. Also game related functions requiring game to be played too...

**Comment by seishun** [comment]
>Maybe you can change gamesPlayed method, so when node-dota sending 570 first and then node-csgo sending 730 actual message contains both of them.

No, `gamesPlayed` is just a wrapper around the ClientGamesPlayed message. Personally, I think game-related handlers should only wrap GC and leave things like starting and exiting games to the user.

**Comment by paralin** [comment]
@seishun I think so. That should be enough to de-duplicate code required for handling those events.

**Comment by seishun** [comment]
@paralin @TrueCarry I just remembered that `routing_appid` needs to be set in the header for ClientRichPresenceRequest. Does anyone know if the same applies to other RP functionality?

I'm thinking of having the SteamRichPresence constructor accept an AppID, just like SteamGameCoordinator.

**Comment by TrueCarry** [comment]
@seishun yes, it is.

**Comment by seishun** [comment]
@paralin @TrueCarry I implemented SteamRichPresence [here](https://github.com/seishun/node-steam/tree/rp). Let me know if there are any fatal issues.
