### ISSUE TITLE
Handlers scoping

### ISSUE THREAD

**Issue by shqke** [seishun/node-steam#258]
Why there's suddenly so many new constructors (SteamFriends, SteamUser)? Especially when SteamUser contains only few functions.
"handlers" object is local now in the namespace of each of their sources file which means new handlers cannot be added outside.
Why is this made like that?

**Comment by scholtzm** [comment]
This approach is much better - `node-steam` is now modular. Anyone can make their own handler without abusing the private `_send` method.

The scoping of handlers seems to be copying SteamKit's scoping: https://github.com/SteamRE/SteamKit/tree/master/SteamKit2/SteamKit2/Steam/Handlers

> "handlers" object is local now in the namespace of each of their sources file which means new handlers cannot be added outside

What do you mean by this?

**Comment by seishun** [comment]
>What do you mean by this?

Probably the fact that `_handlers` used to be a property on `SteamClient` that could be modified by user code.

>which means new handlers cannot be added outside.

On the contrary, it's now possible to create new handlers without using undocumented methods and properties. See ['mesage'/send](https://github.com/seishun/node-steam#messagesend).

**Comment by shqke** [comment]
Ok, seems like I figured the idea but why not keep handlers as events instead of making another constructor for each steam operations subtype? At this point they might be modified.
> On the contrary, it's now possible to create new handlers without using undocumented methods and properties. See 'mesage'/send.
Yeh, just figured, thanks.
