### ISSUE TITLE
Error help plz

### ISSUE THREAD

**Issue by bagda391** [seishun/node-steam#260]
I get this error sometimes: 
https://gyazo.com/876acf3f60cf1e332146d414ba29746e

I manage to get rid of it by deleting some rows in the database but it still happens now and then. Also, the largest win is not updated properly on my jackpot website (showing $4 instead of $40).

**Comment by bagda391** [comment]
It happens when the bot sends the trade offer (so I guess somehow he doesn't introduce in the database the right things when people send items to my bot)

**Comment by andrewda** [comment]
MySQL issue. Not related to node-steam.

**Comment by jabbink** [comment]
Unrelated to this issue, but why does this repo get so many invalid issues, often accompanied by a f*eaking gyazo screenshot of some stacktrace (instead of pasting the screenshot in here and auto-upload to github; or even better: copypaste the stacktrace)?

**Comment by andrewda** [comment]
@jabbink My guess is that they are using either using the leaked CSGOFast bot and don't understand the code at all, or they're using a bot that someone sold to them and they can't figure out how to set it up.
