### ISSUE TITLE
Steam Market Transactions

### ISSUE THREAD

**Issue by overheader** [seishun/node-steam#261]
Is it possible with node-steam to buy the keys to the cases in cs:go (not marketplace)?

**Comment by seishun** [comment]
No, it's done via the website.

**Comment by jabbink** [comment]
AFAIK you can only buy keys from the marketplace via the website only.

if you want to buy them directly from Valve it requires an interaction from both (send request from in game; I assume this uses protobuf, server wants confirmation and redirects you to the default website to confirm transactions).
