### ISSUE TITLE
Can connect but can't log in?

### ISSUE THREAD

**Issue by potato20** [seishun/node-steam#263]
Basically following example.js, entering my account name and password correctly, I am able to connect but logging in yields:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Disconnected
    at SteamClient._disconnected (/Users/potato20/nodesteamtest/node_modules/steam/lib/steam_client.js:186:24)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

My `server.js` is you're curious

```
var fs = require('fs');
var Steam = require('steam');

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);

steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: '[username]',
    password: '[pass]'
  });
});

steamClient.on('logOnResponse', function(logonResp) {
  if (logonResp.eresult == Steam.EResult.OK) {
    console.log('Logged in!');
  }
});
```

**Comment by scholtzm** [comment]
This is correct behaviour. You get disconnected and you receive SteamGuard code - check your e-mail.

Also, `logonResp.eresult` will be equal to `Steam.EResult.AccountLogonDenied`.

Docs:
https://github.com/seishun/node-steam#error

**Comment by seishun** [comment]
^

**Comment by adaptivedev** [comment]
I have the same issue. In email, I keep getting the steam code over and over again.

One a different account it worked, but not this one. Both were verified, both should be active, other then the node console being a "new device" (7 days) rule. But then it shouldn't have worked on either machine if this is the reason. Any debugging tips?

**Comment by adaptivedev** [comment]
I keep getting the email with same code over and over again, with same error on line 186.

Previously I had 1 account working on local, and 1 on server, out of my many test accounts. I didn't have to wait 7 days. 1 bot per terminal/machine worked right away.

I figured it might be that only 1 account can be "logged in", and the first 1 that worked sticks, and all other fail.

But then I lost the code that was sent for my server bot that was working, so I tried the disconnect method. This did cause steam to once again send codes for that bot, but then it had the same problem of just getting emails over and over. Maybe now I have to wait 7 days on that terminal/machine for any other bot to work?

It's all very cryptic and confusing, but I think that's Steam API's fault.

Any ideas?

**Comment by seishun** [comment]
@adaptivedev since you're having a problem with Steam rather than node-steam, you are unlikely to get help here. Try the [SteamRE group](http://steamcommunity.com/groups/SteamRE/discussions) or #opensteamworks on irc.gamesurge.net.

**Comment by adaptivedev** [comment]
@seishun besides moving the sentry file, can you think of what else i'd need to do to properly log in using a different account when using the api example storehouse.js from the same directory? what about from another copy of the project in the same machine? any stored files or values anywhere that need to be cleared, besides authCode?

**Comment by adaptivedev** [comment]
Problem Solved. This answer: http://steamcommunity.com/groups/SteamRE/discussions/1/

Helped me find this no-hassle addition which worked like a charm: https://github.com/DoctorMcKay/node-steam-tradeoffer-manager

**Comment by aztrack** [comment]
Hello
@adaptivedev how did you fix? im stuck just like this :(
