### ISSUE TITLE
logOn returns eresult: 5 (invalid password), but password is 100% correct

### ISSUE THREAD

**Issue by tephro** [seishun/node-steam#264]
I am able to login with the same account credentials and ssfn through Valve's steam client, but can't login with node-steam. No verification codes on related email. Yesterday it worked just fine, no changes in my source code were made.

The logon response is:
{ eresult: 5,
  eresult_extended: 5,
  client_supplied_steamid: 'xxxxxxxxxxxxxxxxxxxx',
  count_loginfailures_to_migrate: 0,
  count_disconnects_to_migrate: 0 
}

Any changes on Valve side?

**Comment by tephro** [comment]
Now the problem disappeared. Looks like an issue with steam network.

**Comment by seishun** [comment]
This is not a node-steam issue, so I couldn't help you anyway.
