### ISSUE TITLE
Show as not playing on mobile steam

### ISSUE THREAD

**Issue by Ishi-k2** [seishun/node-steam#266]
Seishun can you make it shows as playing on mobile steam client?
It only shows playing on dasktop client :/

![hg](https://cloud.githubusercontent.com/assets/9837539/10419805/35eaff04-702f-11e5-84cd-c6e1709da643.png)

**Comment by andrewda** [comment]
Not sure why this would be, but it seems like it's a Steam issue. Never seen this happen before.

**Comment by seishun** [comment]
The `gamesPlayed` method is just a wrapper around the ClientGamesPlayed message. What happens on Steam side is outside of my control.
