### ISSUE TITLE
Invalid Password - But everything is correct

### ISSUE THREAD

**Issue by borianm** [seishun/node-steam#267]
I have already seen someone posted the same thing. Unfortunately for 1 hour, I still haven't fixed it. In first I thought it was Steam down, and it was. But Steam is up for more than half an hour, and I still can't login.

~~When I run an older version of the script (with steam@0.6.8) I don't get any errors, but when I test the example of steam@1.2.0 I get invalid password for all of my accounts.~~
I get the same error on my old script, just checked.

I guess the code is correct, but does anyone else get the same problem, since I get it now on all of my scripts actually.
Looks like this (on the 1.2.0 version):

{ eresult: 5,
  eresult_extended: 5,
  client_supplied_steamid: 'XXXXXXXXXXXXXX',
  count_loginfailures_to_migrate: 0,
  count_disconnects_to_migrate: 0 }

var logOnOptions = {
  account_name: 'XXXXXXX',
  password: 'XXXXXX'
};

Login part: http://pastebin.com/FAGtc2iQ

Any ideas?

**Comment by scholtzm** [comment]
Actually, Steam will *sometimes* respond with `eresult` 5 when their servers are working incorrectly even if your password is correct.

**Comment by seishun** [comment]
Like I've already said like a hundred times, what Steam does is outside of my control. Is it that hard to understand that the issue tracker is for library issues and not a replacement for Steam support?
