### ISSUE TITLE
Login Fail (Dont understand why)

### ISSUE THREAD

**Issue by badbreaker** [seishun/node-steam#268]
I have this error:
-------------------------------------------------------------------------------------------------------------------------------
C:\Users\Administrator\Desktop\Bot>node tradebot.js
socket timed out
socket closed
connecting to 72.165.61.174:27017
connected
encrypt request
handshake complete
logon fail: 65, sessionID: 491969
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Logon fail: 65
    at SteamClient.handlers.(anonymous function) (C:\Users\Administrator\Desktop
\Bot\node_modules\steam\lib\handlers\user.js:178:11)
    at SteamClient._netMsgReceived (C:\Users\Administrator\Desktop\Bot\node_modu
les\steam\lib\steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (C:\Users\Administrator\Desktop
\Bot\node_modules\steam\lib\steam_client.js:192:10)
    at SteamClient._netMsgReceived (C:\Users\Administrator\Desktop\Bot\node_modu
les\steam\lib\steam_client.js:106:26)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection._readPacket (C:\Users\Administrator\Desktop\Bot\node_modules\s
team\lib\connection.js:50:8)
    at emitNone (events.js:67:13)
    at Connection.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:411:10)

C:\Users\Administrator\Desktop\Bot>pause
Press any key to continue . . .

-------------------------------------------------------------------------------------------------------------------------------

I was looking to fix it but I already put the Authcode that Steam send to my email, whan I am doing wrong?

Code of bot.js
---------------------------------------------------------------------------------------------------------------------------
var admin = 'Censored';

var logOnOptions = {
	accountName: 'Censored',
	password: 'Censored'
};
var GameTime = 120;

////

var authCode = 'VHKNW'; 

var globalSessionID;

if (require('fs').existsSync('sentry_'+logOnOptions['accountName']+'.hash')) {
	logOnOptions['shaSentryfile'] = require('fs').readFileSync('sentry_'+logOnOptions['accountName']+'.hash');
} else if (authCode != '') {
	logOnOptions['authCode'] = authCode;
}
---------------------------------------------------------------------------------------------------------------------------

**Comment by badbreaker** [comment]
You dont know to solved it? Could you pls send me a link where I can post it to get an answer?

**Comment by scholtzm** [comment]
`var authCode = 'VHKNW';`

This SteamGuard code changes, it's not static. You can't use the same over and over, hence the error. Reading the docs would certainly help you. :+1:

**Comment by andrewda** [comment]
Along with what @scholtzm said, understanding the code would also help. Just writing your credentials in the stolen CSGOFast bot won't do much when you have to fix it.
