### ISSUE TITLE
How to get bot steam ID and bot's friends' steam IDS?

### ISSUE THREAD

**Issue by iamcsharper** [seishun/node-steam#275]
I'm playing with your lib and trying to implement a bot. I gotta have in memory after `webLogOn` array of objects like that: 
```javascript
{
  nick: userNick,
  id: 76561198121640559
}
```
It would be good to load these objects async, but I need to handle it when the load complete. I need your help!

**Comment by scholtzm** [comment]
This isn't help desk. Also, all your questions are answered in the README and/or wiki.

**Comment by iamcsharper** [comment]
I just have read documentaion and got it. The solution was calling `Steam.SteamFrinds(client).friends`.
