### ISSUE TITLE
Is it possible to get what app a friend is currently playing?

### ISSUE THREAD

**Issue by Gacnt** [seishun/node-steam#279]
Thanks just don't see any methods to check what game a friend is playing.

**Comment by scholtzm** [comment]
Have you tried this? https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#requestfrienddatasteamids-requesteddata

**Comment by Gacnt** [comment]
@scholtzm Is there any way to do it synchronously and not by using an event?

**Comment by scholtzm** [comment]
Unless you use some sort of 3rd party lib, I don't think so.

**Comment by seishun** [comment]
If it's an online friend, then you will likely find information about them in the [friends object](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#personastates). The game_name field seems to be what you need.
