### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by JLBGold** [seishun/node-steam#28]
I'm on Windows Vista SP2 (64 bits).

When i run example.js, I got error : Login failed : 5
![nodesteam](https://f.cloud.github.com/assets/4575918/749565/a163029e-e4af-11e2-958c-29ef40211b8d.jpg)

When i run example.js (changing username and password), i got error : Login failed 63
![nodesteam2](https://f.cloud.github.com/assets/4575918/749649/c963f6fc-e4b1-11e2-8772-d26278a58772.jpg)

Thanks for helping me to resolve this issue...

**Comment by AniMud** [comment]
Hate to revive a 2 year old topic, but as i came here from Google i'll let you know how i fixed this:

While receiving this logon failed message, i just pasted the steam guard code inside putty and it logged me in, no need to modify example.js

**Comment by justinvforvendetta** [comment]
@animud im having a weird issue similar. i have a script to get my hex sentry, and it works, but then when i plug it in, i get a login fail, and another 5 digit code emailed. its becoming a vicious cycle.. i run the script with my 5 digit, get my sentry, then put in my sentry n get a login fail. any ideas?
