### ISSUE TITLE
Upcoming update with mobile auth

### ISSUE THREAD

**Issue by 1e4** [seishun/node-steam#280]
Hey,

Does anyone know if the API will be changing if you have the mobile auth? As far as I know Steam hasn't updated the API for ETradeOfferState, so also not sure how you will be able to get the steam trades that are in 'escrow' though that's another matter.

**Comment by seishun** [comment]
Two factor authorization has been possible since v1.0.0, see https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon

Regarding trade offers and escrow, those are irrelevant to this repo.
