### ISSUE TITLE
Steam mobile guard

### ISSUE THREAD

**Issue by naksuasd** [seishun/node-steam#282]
Hi, i just added steam mobile guard to my account, and now i'm getting logon fail 85.
Is there any upcoming updates or DIY fixes for this issue?

**Comment by Alex7Kom** [comment]
Try to provide `two_factor_code` from your app on log in, see https://github.com/seishun/node-steam/wiki/Protobufs

**Comment by naksuasd** [comment]
Thanks for super fast reply. I tried to do that, and got this error in return:

C:\Users\user\Desktop\bot\node_modules\steam\node_modules\protobufjs\dis
t\ProtoBuf.js:2536
 throw Error(this+"#"+keyOrObj+" is not a field: undefined");

Error: .CMsgClientLogon#two_factor_code is not a field: undefined

**Comment by Alex7Kom** [comment]
Post your code, you should do something like:

```js
steamUser.logOn({
  account_name: 'your_username',
  password: 'your_password',
  two_factor_code: 'CODE_FROM_APP'
});
```

**Comment by naksuasd** [comment]
Thats is code witch exactly gives me that error i posted :cry:

**Comment by scholtzm** [comment]
Are you using latest node-steam?

You can also check the `CMsgClientLogon` protobuf in your node-steam folder.

**Comment by naksuasd** [comment]
Yeah, i just updated my node-steam to latest and still got same error.

**Comment by naksuasd** [comment]
Oh, got it solved. It was 
```javascript
"twoFactorCode"        : "",
```

Not:
```javascript
"two_factor_code"        : "",
```

**Comment by seishun** [comment]
Because you're using an old and unsupported version of node-steam.

**Comment by tambu22** [comment]
how can i get shared_secret to get the code?
