### ISSUE TITLE
Error: Disconnected

### ISSUE THREAD

**Issue by naksuasd** [seishun/node-steam#284]
Hi. I'm sorry about posting this without better knowledge about this issue, i'm pretty sure i'm doing something wrong, but:

When i'm trying to run even example, i got this:

encrypt request
socket ended
socket closed
Error: Disconnected

It wont give me login error or enter "logOnResponse"

**Comment by seishun** [comment]
The example doesn't handle failed logon attempts, you'll have to add code for that yourself.
