### ISSUE TITLE
webSessionID

### ISSUE THREAD

**Issue by naksuasd** [seishun/node-steam#285]
Hi, this is maybe wrong project to ask, but isn't webSessionID supported anymore?
can't found it anywhere

**Comment by seishun** [comment]
It was removed [4 months ago](https://github.com/seishun/node-steam/releases/tag/v1.0.0).

**Comment by scholtzm** [comment]
Alternatively, you can use  [node-steam-weblogon](https://github.com/Alex7Kom/node-steam-weblogon).
