### ISSUE TITLE
Failed install via npm install steam

### ISSUE THREAD

**Issue by panp858** [seishun/node-steam#286]
Hello!

I used a very old version of node-steam before and after updating to the latest node version I tried to reinstall node-steam. But whatever I try it always failed.

D:\<path>npm install steam
npm WARN install:window-size@0.1.2 ENOENT: no such file or directory, chmod 'D:\<path>\node_modules\steam\node_modules\protobufjs\node_modules\yargs\node_modules\window-size\cli.js'

Bot@0.0.1 D:\<path>
├── bufferview@1.0.1  extraneous
└─┬ steam-tradeoffers@2.0.2
  └── long@2.4.0

npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\steam\node_modules\protobufjs with new installed version

I installed steam-ressources before and also did npm install there. But it doesn't change anything.

**Comment by Alex7Kom** [comment]
It is a known npm bug, see https://github.com/seishun/node-steam/issues/281 and https://github.com/npm/npm/issues/9633

**Comment by panp858** [comment]
So I used the command "" and updated to npm versoin 3.5.0 which fixed that problem. After changing all the names for the login options I receive the following error:

connected
encrypt request
socket ended
socket closed
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Disconnected
    at SteamClient._disconnected (D:\<path>\node_modules\steam\lib\steam_client.js:186:24)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)

**Comment by seishun** [comment]
This "issue" has been brought up multiple times here, please learn to search.
