### ISSUE TITLE
twoFactorCode

### ISSUE THREAD

**Issue by feedarz** [seishun/node-steam#287]
Will i able to push generated twoFactorCode to logOnOptions obj like:
logOnOptions{
"accountName" : login,
"password" : pass,
"twoFactorCode" : code
}

?

**Comment by seishun** [comment]
https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon

**Comment by feedarz** [comment]
i am wondering if has the same name as twoFactorCode. Is it?

**Comment by seishun** [comment]
It's all described [here](https://github.com/seishun/node-steam#protobufs). So it's `two_factor_code`, same as the field name.

**Comment by feedarz** [comment]
But logOnOptions is different obj for your module. For e.x. account_name is accountName in obj. And i need to know the same thing for two_factor_code.

**Comment by seishun** [comment]
>For e.x. account_name is accountName in obj.

This is no longer the case since [v1.0.0](https://github.com/seishun/node-steam/releases/tag/v1.0.0).

**Comment by feedarz** [comment]
thank you so much!

**Comment by tambu22** [comment]
how can i get shared_secret ?

**Comment by seishun** [comment]
@tambu22 "shared_secret" isn't part of node-steam's API, please discuss it elsewhere.

**Comment by tambu22** [comment]
but other libs (node-steamcommunity) get a method to get it. :(
