### ISSUE TITLE
Get server info

### ISSUE THREAD

**Issue by demipixel** [seishun/node-steam#288]
I've been trying to get the server info of the server a user is playing on, however this doesn't work with the normal steam API if the person's profile is private. However, I was hoping to use this library , since it's more focussed on friends (profile is private to public but not friends). I've been trying requestFriendData with "GameExtraInfo".

Is it possible to get a player's server IP? If so, how?

P.S. Nice job with 0 open issues

**Comment by seishun** [comment]
I _assume_ `game_server_ip` is the field you're looking for in [`personaStates`](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#personastates). If you can confirm its purpose, you're welcome to add that information to the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs#friend).

AFAIK Steam sends very little user data when requesting it manually, so requestFriendData might not help you. But if it's an online friend, Steam should send you that information automatically (see ['personaState'](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#personastate)).
