### ISSUE TITLE
Could you implement mobile trade confirmation?

### ISSUE THREAD

**Issue by lopataz** [seishun/node-steam#293]
I know there is node-steamcommunity that handle this already but I can't login to both using the same 2FA code...
 so it would be nice if it was implemented in node-steam
or a way to login to 2 different steam users client using the same two factor code?

**Comment by buddhapest** [comment]
you don't have to log into both.  log into one and `setCookies` on the other.

the 2 different users logging in using the same 2 factor code makes zero sense...

**Comment by seishun** [comment]
It's part of the mobile protocol, not Steam client protocol.
