### ISSUE TITLE
sourceJobID != '18446744073709551615'

### ISSUE THREAD

**Issue by sturadnidge** [seishun/node-steam#295]
Hey,

First of all, really awesome work.

I noticed a few places where you're eval'ing against the largest 64bit int, which will never work in JS... I haven't fully wrapped my head around why this is being done, but if it's just to ensure the use of a 'safe' JobID then you probably want to replace that with Number.MAX_SAFE_INTEGER or use a module like 'long' to handle it?

I didn't want to submit a PR as it might hit a few files and would probably be more mental overhead for you than reading this comment.

**Comment by seishun** [comment]
The default value of job IDs is 18446744073709551615 (i.e. the maximum uint64 value). It means the message is not a response/request. Since `sourceJobID` is a Long.js object, comparing it to a string would automatically call `toString()` on the former, so it works correctly.

**Comment by sturadnidge** [comment]
Nice one, thx.
