### ISSUE TITLE
Unhandled Error Event

### ISSUE THREAD

**Issue by remcova** [seishun/node-steam#296]
The bot that I created works but I receive a error from the steam module. Does anyone know what this problem is? or maybe the author can fix this?

http://i.imgur.com/0Gq2HN5.png

**Comment by scholtzm** [comment]
https://github.com/seishun/node-steam#error

**Comment by remcova** [comment]
What does this mean? Did I forget  something?

**Comment by remcova** [comment]
Because why got I kicked from the servers?

**Comment by seishun** [comment]
I can't know why Steam disconnected you. This is not Steam support. Maybe the server went offline, or you got logged off, or something else.
