### ISSUE TITLE
Mobile authentication

### ISSUE THREAD

**Issue by Jallvar** [seishun/node-steam#298]
Dear author. Please add these two methods. for authentication and code generation.
enable2fa and finalize2fa
Your library uses 90% of developers. Help us.
Your library is the best, but I need a shared secret
Please, see
https://github.com/GaletskyIvan/steamcommunity-mobile-confirmations/issues/1#issuecomment-161651774

**Comment by seishun** [comment]
I can't add them because enabling 2fa is done through Steam Community, not through Steam client. You can use for example [node-steamcommunity](https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#enabletwofactorcallback) for that.

**Comment by RoanDev** [comment]
Dear Nikolai! Would you like to provide a 2fa functionality? A lot of websites using your module. The only problem is that your steam client is no more actual, because there 2fa is not provided... 

Personally I(and I'm not alone here) dont want use node-steamcommunity instead of node-steam, simply because we have some clients that have some applications that already working on your code.

**Comment by scholtzm** [comment]
@seishun Unified messages actually support [two factor](https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/steamclient/steammessages_twofactor.steamclient.proto) btw.

**Comment by Jallvar** [comment]
I can not give up your library. because there Sentry files

**Comment by scholtzm** [comment]
@Jallvar You can still use node-steam. What's the problem?

**Comment by Jallvar** [comment]
I need to automate the process.
Authorisation and sending the exchange offers.
Innovations that did not prevent it.

steam-community supports the generation of codes (there are desired methods).
node-steam supports Sentry-files

**Comment by scholtzm** [comment]
> node-steam supports Sentry-files

node-steam supports anything related to Steam network protocol, including logging in with 2FA code.

**Comment by Jallvar** [comment]
me need to generate 2fa code.
node-steam not allow it.

**Comment by scholtzm** [comment]
> node-steam not allow it.

[I have generated the codes using node-steam.](https://github.com/seishun/node-steam/issues/298#issuecomment-163465273) Magic? Why do you even keep arguing is beyond me, i'm out.
