### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by RoanDev** [seishun/node-steam#299]
Dear Nikolai! Would you like to provide a 2fa functionality? A lot of websites using your module. The only problem is that your steam client is no more actual, because there 2fa is not provided...

Personally I(and I'm not alone here) dont want use node-steamcommunity instead of node-steam, simply because I have some clients that have some applications that already working on your code.

**Comment by andrewda** [comment]
You can login fine using Node-Steam (see [`two_factor_code`](https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon)). As for generating codes, that's completely out of the scope of this module, which is meant to emulate the Steam client. It's trivial to implement Node-Steam-TOTP to generate the codes, and Node-Steamcommunity to confirm trades.

**Comment by Dozorov** [comment]
Dear Nikolai! Pls add 2FA.

**Comment by seishun** [comment]
What @andrewda said.
