### ISSUE TITLE
logOn fail 85

### ISSUE THREAD

**Issue by Secretmars** [seishun/node-steam#301]
Hello, i have couple of questions

I used steam desktop authhenticator to get  "identity_secret","device_id" then i added those to my config..  but at the and im getting 85 logon fail.. and our code was working before steam mobile guard.

"authCode"        : "", <-- we leave this empty
"steamid"      : "XXXXXXXXXXXXXX",
"secretuser"      : "K+XXXXXXXXXXX=",
"deviceid"		  : "3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",	

function reWebLogOn(steam, callback) {
	steam.webLogOn(function(newCookie){
		helper.msg('webLogOn ok');

		offers.setup({
			sessionID: currentSessionId,
			webCookie: newCookie 
		}, function(){
			if (typeof callback == "function") {
				callback();
			}
		});
		var steamcommunityMobileConfirmations = new SteamcommunityMobileConfirmations(
			{
			  steamid:         config.steamid,
			  identity_secret: config.identitySecret,
			  device_id:       config.deviceId,
			  webCookie:       newCookie,
			});

			steamcommunityMobileConfirmations.FetchConfirmations((function (err, confirmations)
		{
			if (err)
			{
				console.log(err);
				return;
			}
			console.log('steamcommunityMobileConfirmations.FetchConfirmations received ' + confirmations.length + ' confirmations');
			if ( ! confirmations.length)
			{
				return;
			}
			steamcommunityMobileConfirmations.AcceptConfirmation(confirmations[0], (function (err, result)
			{
				if (err)
				{
					console.log(err);
					return;
				}
				console.log('steamcommunityMobileConfirmations.AcceptConfirmation result: ' + result);
			}).bind(this));
		}).bind(this));

		});  
}

**Comment by seishun** [comment]
I have no idea how "steam mobile guard" works. Also I don't see any usage of node-steam API in your snippet, so you're probably posting to the wrong repo anyway.
