### ISSUE TITLE
Problems installing node-steam

### ISSUE THREAD

**Issue by Jallvar** [seishun/node-steam#302]
1.Established node-steam through npm:
npm install steam
Installed library assistants. but the node-steam not established
Download and install manually github.com
2. Make connections:
require('steam');
error:
Cannot find module 'steam-resources'
3. Download and install manually github.com (steam-resources)
Error: Cannot find module 'protobufjs'
npm install protobufjs

4. Error: ENOENT: no such file or directory, open 'C:\Windows\system32\node_modules\steam\lib\steam_client.js'

Repeat the manual installation of node-steam

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (C:\Windows\system32\node_modules\steam-resources\stea
m_language_parser\index.js:8:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Windows\system32\node_modules\steam-resources\inde
x.js:81:1)
    at Module._compile (module.js:425:26)

What to do?

**Comment by seishun** [comment]
You aren't making much sense TBH.

> Installed library assistants. but the node-steam not established

What does that even mean?

> Download and install manually github.com

Did you follow the extra step required for installation from git as described in the README?

> Cannot find module 'steam-resources'

Apparently you didn't.

> Error: Cannot find module 'protobufjs'

Obviously you didn't follow the steps provided in the node-steam-resources README either.

>   Error: ENOENT: no such file or directory, open 'C:\Windows\system32\node_modules\steam\lib\steam_client.js'

You're doing something really wrong if you ended up with node_modules inside system32...

**Comment by Jallvar** [comment]
Thanks for the answer!
My English is poor.
I'll read the README and answer you

**Comment by Jallvar** [comment]
I reinstalled according to the README

C:\Users\Jallvar\Desktop\SteamBot>node C:\Users\Jallvar\Desktop\SteamBot\public\
nbauth.js
C:\Users\Jallvar\Desktop\SteamBot\node_modules\steam\node_modules\steam-resource
s\steam_language_parser\index.js:8
process.chdir(languagePath);
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (C:\Users\Jallvar\Desktop\SteamBot\node_modules\steam\
node_modules\steam-resources\steam_language_parser\index.js:8:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Jallvar\Desktop\SteamBot\node_modules\steam\
node_modules\steam-resources\index.js:81:1)
    at Module._compile (module.js:425:26)

**Comment by seishun** [comment]
```
process.chdir(languagePath);
^

Error: ENOENT: no such file or directory, uv_chdir
```

Either you didn't run `npm install` inside `steam/node_modules/steam-resources`, or it failed. I suggest that you install from npm instead.

**Comment by Jallvar** [comment]
Really. creepy infuriates Windows.
node js works without problems on linux.
I downloaded from the repository node-steam. and in catalogs execute the command. npm install, works flawlessly.

**Comment by chiiledgamer1985** [comment]
hello seishun im sorry to be a pain but how would i fix the same bug on a windows vps

**Comment by jwigley** [comment]
> hello seishun im sorry to be a pain but how would i fix the same bug on a windows vps

Should be no different. Install from npm or run `npm install` from within `steam/node_modules/steam-resources`.
