### ISSUE TITLE
Pass custom game to property

### ISSUE THREAD

**Issue by Committing** [seishun/node-steam#303]
Hi

Is is possible to pass a custom 'Non-Steam' game to the gamesPlayed property? Or is there any other such property?

So it's possible to do custom titles like this: https://i.gyazo.com/fd34f1fc57cb7dbe0152dc9786cf9bb9.png

Thanks

**Comment by seishun** [comment]
It seems so. What's known so far is described [here](https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientgamesplayed).

**Comment by Committing** [comment]
Oh wow; the trickery. Well noticed!

Cheers :)
