### ISSUE TITLE
[Fixed] I'm having trouble with sentry hash.

### ISSUE THREAD

**Issue by KingFluffyXVI** [seishun/node-steam#306]
function MakeSha(bytes) {
    var hash = crypto.createHash('sha1');
    hash.update(bytes);
    return hash.digest();
}

sentryfile = fs.readFileSync( sentryFilePath );
sentryhash = MakeSha(sentryfile)
console.log(sentryhash)

steamClient.connect();

steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: 'fluffy bot username',
    password: |REDACTED|,
	sha_sentryfile: sentryhash
  });
});

steamUser.on('updateMachineAuth', function(sentry, callback) {
    fs.writeFileSync(sentryFilePath, sentry.bytes);
    callback({ sha_file: MakeSha(sentry.bytes) });
});

This code gives me 'Error: Disconnected' as if I was using an invalid steam guard code.
I've looked at the wiki, but I'm still having trouble.

**Comment by scholtzm** [comment]
Listen to [`logOnResponse`](https://github.com/seishun/node-steam#logonresponse) to know what's going on. There are several reasons why you might be getting disconnected.

Also, I think you just posted your login details.

**Comment by KingFluffyXVI** [comment]
That was dumb of me. It's only a bot anyway, basic password.
Would just using console.log on the logOnReponse work?
Does my sentry saving part seem to work (especially the callback I'm not sure about)

**Comment by scholtzm** [comment]
The code looks correct.

**Comment by KingFluffyXVI** [comment]
Right. Does the variable in the callback matter? I'd change things more myself but I'm away from the computer until morning

**Comment by KingFluffyXVI** [comment]
I'm getting login error 65 which seems to be suggesting that my sentry file isn't being used.

**Comment by KingFluffyXVI** [comment]
Issue fixed. Not sure what I did.
