### ISSUE TITLE
is there any way to start steam client when steam mobile authenticator is on?

### ISSUE THREAD

**Issue by lparamonov** [seishun/node-steam#308]
Recently, I turned on steam mobile authenticator. When I try to log in to steam by node-steam I got the steam error 85.  
is there any way to start steam client when steam mobile authenticator is on?
my code looks like this:
// Initialize the Steam client and our trading library
var client = new steam.SteamClient();
var trade  = new steamtrade();

var sentryfile;
if(fs.existsSync('sentryfile.' + username + '.hash')) {
    sentryfile = fs.readFileSync('sentryfile.' + username + '.hash');
}
//  Let's try logging in.
client.logOn({
    accountName: username, 
    password: password, 
    shaSentryfile: sentryfile // If null, a new Steam Guard code will be requested
});

**Comment by seishun** [comment]
You're using an old and unsupported version of node-steam, and your question has been already asked many times here, please learn to search.
