### ISSUE TITLE
Can't install module..

### ISSUE THREAD

**Issue by elitek** [seishun/node-steam#309]
root@Bot:~/bot# npm install steam
npm WARN install:window-size@0.1.2 ENOENT: no such file or directory, chmod '/root/bot/node_modules/steam/node_modules/steam-resources/node_modules/protobufjs/node_modules/yargs/node_modules/window-size/cli.js'
bot@1.0.0 /root/bot
└── (empty)

npm WARN EBUNDLEOVERRIDE Replacing bundled steam > steam-resources with new installed version
npm ERR! code 1

**Comment by seishun** [comment]
This has been asked many times, please learn to search.
