### ISSUE TITLE
Bot doesn't login

### ISSUE THREAD

**Issue by Dezash** [seishun/node-steam#320]
I have setup 2FA and everything but the bot doesn't seem to login.
loggedOn event doesn't trigger and logOnResponse eresult is 1. Why is the bot shown as offline and loggedOn event doesn't trigger if eresult is OK?

**Comment by scholtzm** [comment]
There's no `loggedOn` event.

[Enums are mentioned in the README.](https://github.com/seishun/node-steam#enums)

**Comment by Dezash** [comment]
Oh, my bad. Thanks :)
