### ISSUE TITLE
steamID to steamID64 string

### ISSUE THREAD

**Issue by Dezash** [seishun/node-steam#322]
Is there a way to convert steamID to steamID64 string?

**Comment by scholtzm** [comment]
https://github.com/seishun/node-steam#steamid

**Comment by Dezash** [comment]
What does it "mean wrap the number in quotes"?
steamID outputs: { low: 214107458, high: 17825793, unsigned: true }

**Comment by seishun** [comment]
What do you mean by "steamID"? If you mean the property on SteamClient, then it should be a string. Are you using the latest version of node-steam?

**Comment by scholtzm** [comment]
He probably means something like this:

```js
var response = Steam.Internal.CMsgTrading_InitiateTradeRequest.decode(body);
// response.other_steamid is Long
```

You can simply turn these values into string by calling `toString` method on them.

```js
// prints 64bit SteamID string
console.log(response.other_steamid.toString());
```

**Comment by Dezash** [comment]
I am using the latest node-steam but the node_modules inside node-steam are from an older version. I am talking about steamFriends property at the moment.
steamFriends.on('friendMsg', function(steamID, message, type) {
console.log(steamID) //Output: { low: 214107458, high: 17825793, unsigned: true }
}

**Comment by seishun** [comment]
>node_modules inside node-steam are from an older version

Well that's probably the reason.

**Comment by Dezash** [comment]
steam-resources is 1.0.0
protobufjs is 4.0.0
steam-crypto 0.0.1
buffer-crc32 is 0.2.5
bytebuffer is 4.0.0
adm-zip is 0.4.7

Still same output

**Comment by seishun** [comment]
https://github.com/seishun/node-steam/blob/master/package.json#L14

Your bytebuffer version is still old.

**Comment by Dezash** [comment]
Now it works. Thank you.
