### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by Pitu-pl** [seishun/node-steam#323]
Hello

I want to write this on gitter but cant find repo. Gitter says that repo is private maybe.
Im using steam 1.1.x because node csgo need this version.

Its my part of code:
```javascript
bot.connect();
bot.on('connected', function() {
  steamUser.logOn({ account_name: secrets.username, password: secrets.password, auth_code: secrets.guardCode, sha_sentryfile: sentry });
});

// Continuously try to connect if disconnected
setInterval(function() { 
	if (!bot.loggedOn) {
		steamUser.logOn(secrets.username, secrets.password, sentry, secrets.guardCode);
	}
}, 60*1000);

bot.on('logOnResponse', function(logonResp) { 
		winston.error(logonResp);
	if (logonResp.eresult == steam.EResult.OK) {
		winston.info("Logged on");
		steamFriends.setPersonaState(steam.EPersonaState.Online);
		csgoInit();
	}
});

bot.on('error', function(error) { 
	winston.error("Caught Steam error", error);
});
```

In logOnResponse I have response:
eresult=65, eresult_extended=71, client_supplied_steamid=76561198194059322, count_loginfailures_to_migrate=0, count_disconnects_to_migrate=0

In error, error is empty but event error is called.

This code worked find 1-2 months, i restarted my server and when want to start bot have errors.

**Comment by andrewda** [comment]
You need to be using your mobile `two_factor_code` now.

**Comment by Pitu-pl** [comment]
Now code above working and bot is online.

@andrewda on my bot i have enabled standard email guard.

**Comment by seishun** [comment]
I assume the issue is resolved.
