### ISSUE TITLE
GC.send never fire callback

### ISSUE THREAD

**Issue by TarasDev** [seishun/node-steam#324]
It didn't work for me on any method
```
gc.send(header, body, callback);
```

**Comment by seishun** [comment]
The callback is only fired when GC sends a JobID-based response. Not all GC messages use JobIDs. You can check using NetHook2 – see if the message the client sends has source_job_id set and whether there is an incoming message with a matching target_job_id.

**Comment by Apercu** [comment]
I might be wrong, but can also reproduce this on some messages that should work using JobIDs for example the proto `CMsgGCCStrike15_v2_Client2GCEconPreviewDataBlockRequest` which is a `Client2GCEconPreviewDataBlockRequest` and should respond with the `Client2GCEconPreviewDataBlockResponse`, the request correctly send the `job_id_source` in the header, the response is correctly received but the JobID still is `18446744073709551615` which means it is not a response/request.

Do you have any idea if it's an intended behavior or no? Thanks.

**Comment by seishun** [comment]
>should work using JobIDs

Have you tried using NetHook to see if it's actually the case?

**Comment by Apercu** [comment]
I unfortunately don't have a Windows right now, but as you stated in a [previous message](https://github.com/seishun/node-steam/issues/295#issuecomment-162226983), I assumed messages following the `Request` `Response` naming should work this way.

Do you know any way I can test this?

**Comment by seishun** [comment]
>I assumed messages following the Request Response naming should work this way.

AFAIK it's not always the case.

>Do you know any way I can test this?

I'm not aware of any way that doesn't involve using NetHook and consequently Windows.

**Comment by Apercu** [comment]
Okay thanks for the clarification.
