### ISSUE TITLE
ProtoBuf crash

### ISSUE THREAD

**Issue by seria2** [seishun/node-steam#325]
![image](https://cloud.githubusercontent.com/assets/1989823/12175878/a3d5248c-b575-11e5-8840-4c6645c70f23.png)
This is from windows. Node.js 5.4.0
----
![image](https://cloud.githubusercontent.com/assets/1989823/12175926/ea2b715c-b575-11e5-975d-257eed714227.png)
This is from ubuntu. Node.js 0.12.9

**Comment by seishun** [comment]
How are you calling `gamesPlayed`?

**Comment by seria2** [comment]
steamUser.gamesPlayed([730]);

**Comment by seishun** [comment]
That's not how it works. Read the documentation.
