### ISSUE TITLE
Error 141

### ISSUE THREAD

**Issue by Quickcoding** [seishun/node-steam#330]
C:\laragon\www\Bot>node app.js
                                            Steam Guard Code: YXW9W
                                            Steam Guard Code: YXW9W
[SteamBotShop]                              ??? ??????????? W8WJ2
[SteamBotShop]                              ??? ??????????? W8WJ2
                                            Server started on 162.212.255.154:80
80:7777
[Game]                                      Current Game #2312

[SteamBot]                                  socket closed
[SteamBot]                                  connecting to 72.165.61.185:27017
[SteamBot]                                  connected
[SteamBot]                                  encrypt request
[SteamBot]                                  socket ended
[SteamBot]                                  socket closed
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Disconnected
    at SteamClient._disconnected (C:\laragon\www\Bot\node_modules\steam\lib\stea
m_client.js:186:24)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)

C:\laragon\www\Bot>

**Comment by scholtzm** [comment]
As per README, you'll need to handle `error` event.
