### ISSUE TITLE
2FA authentication support ?

### ISSUE THREAD

**Issue by roser137** [seishun/node-steam#332]
Hi, Is there support for new 2FA authentication, I spent lots of time but couldn't figure it out. Sorry for basic question I am quite confused with lots of node.js steam libraries

**Comment by jwigley** [comment]
Check out the 'technical info' section of https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/

**Comment by seishun** [comment]
https://github.com/seishun/node-steam/search?q=2fa&type=Issues&utf8=%E2%9C%93
