### ISSUE TITLE
TypeError: Not a buffer

### ISSUE THREAD

**Issue by BlackOnix** [seishun/node-steam#333]
Hello.When I try to send a weapon I get the error
http://prntscr.com/9so7tw

**Comment by seishun** [comment]
I have no idea what "send a weapon" means. And the error is in another module.

**Comment by jabbink** [comment]
> MFW `bot.js:86`: function named `confirmfuckingtrades`

![](https://media.giphy.com/media/f3Mf34d21LKMg/giphy.gif)

**Comment by andrewda** [comment]
@jabbink From now on, this is what I'm calling my confirm method.
