### ISSUE TITLE
question : Is proxy support available? Is it necessary to use it with multiple steam bots?

### ISSUE THREAD

**Issue by Krash-ua** [seishun/node-steam#334]
I am wondering what will happen if I will run for example 10 bots at the same time with one IP adress for sending and accepting trades? Is it possible to get banned for that? Should I use Proxy and if I should, how can I do that? Also I would like to ask: do I have to connect every bot to the individual mobile phone numbers and pay 5$ for each bot from different credit cards if I don`t want my bots to get banned?

**Comment by seishun** [comment]
>I am wondering what will happen if I will run for example 10 bots at the same time with one IP adress for sending and accepting trades? Is it possible to get banned for that? Should I use Proxy and if I should, how can I do that?

I'm not Steam Support so I have no idea about running multiple bots on the same IP address. However, the Steam Subscriber Agreement does explicitly prohibit the usage of proxies.

Also, this is an issue tracker for the library, not a forum.
