### ISSUE TITLE
Can't get web cookie, just returning "undefined".

### ISSUE THREAD

**Issue by Huskehhh** [seishun/node-steam#335]
Not sure why, have tried almost everything under the sun.

https://gist.github.com/Huskehhh/5c8c255844915b497cc3

Output:
Logon result: 1
Logged in!
Cookies for mobile = undefined
SessionID for mobile = undefined
APIKey = undefined

Any ideas?

**Comment by andrewda** [comment]
You're not using callbacks correctly. 

```javascript
console.log("Cookies for mobile = " + cookieformobile);
console.log("SessionID for mobile = " + sessionID);
console.log("APIKey = " + APIKey);
```

is being called before

```javascript
steamWebLogOn.webLogOn(function (sessionID, newCookie) {
    getSteamAPIKey({
        sessionID: sessionID,
        webCookie: newCookie
    }, function (err, APIKey) {
        cookieformobile = newCookie;
        this.sessionID = sessionID;
        this.APIKey = APIKey;
    });
});
```

finishes running.

Pro tip: put your `console.log()`s inside `getSteamAPIKey()`'s callback.

**Comment by Huskehhh** [comment]
@andrewda You're a bloody legend, haha, thanks for helping a newbie to Node +1
