### ISSUE TITLE
I know the likely hoods are probably something irrational like... 1e-99%

### ISSUE THREAD

**Issue by NavyCo** [seishun/node-steam#336]
I know the likely hoods are probably something irrational like... [*_1e-99_*]%
But could it be possible to have a bot play music through a "virtual" microphone?

**Comment by andrewda** [comment]
This would have **nothing** to do with node-steam. I'm sure that with enough engineering an programming you could get it done, but I think it would be quite a challenging task.

**Comment by seishun** [comment]
I'm pretty sure the voice protocol is completely separate from CM and is therefore outside the scope of node-steam.
