### ISSUE TITLE
Login fail: 56

### ISSUE THREAD

**Issue by Mgr-d** [seishun/node-steam#337]
An error is occurred when i login with node-steam.
Error code is it.
http://pastebin.com/WewDVHis

**Comment by shaunidiot** [comment]
Password not set
```
PasswordNotSet = 56; obsolete "renamed to PasswordUnset"
PasswordUnset = 56;
```

https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd#L59

**Comment by seishun** [comment]
1. Old and unsupported node-steam version.
2. You probably didn't set the password, as pointed out by @shaunidiot
