### ISSUE TITLE
Logon Failed: 5

### ISSUE THREAD

**Issue by farazappy** [seishun/node-steam#338]
Hello, 
I'm getting an logon failed 5 in my trade bot script! 
please help me!

Thanks

**Comment by scholtzm** [comment]
`5 = InvalidPassword`

Also, read the docs.

**Comment by farazappy** [comment]
But I'm supplying the correct password!

**Comment by seishun** [comment]
I'm not Steam Support, so I can't help you regarding Steam not accepting your correct password.
