### ISSUE TITLE
Login Failed Issue

### ISSUE THREAD

**Issue by farazappy** [seishun/node-steam#339]
Hello, 
I'm getting an logon failed 5 in my trade bot script! 
please help me!

5 = InvalidPassword

But the same password is being accepted by different script and web/steam app login.

Thanks

**Comment by seishun** [comment]
You were already given an answer in #338. This is not a help desk. If you can come up with a minimal test case that consistently results in InvalidPassword despite the password being correct, feel free to submit a bug report.
