### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by Hashifier** [seishun/node-steam#340]
My bot worked perfectly for a couple of hours but suddently it stopped working and told me:
`{ eresult: 5,
  eresult_extended: 5,
  client_supplied_steamid: 'XXXXXXXXXXXXX',
  count_loginfailures_to_migrate: 0,
  count_disconnects_to_migrate: 0 }
`

I tried the same setup from another server with an different ip address with and it started working perfectly again. But then after another couple of hours it stopped working again...

Would appreciate help!

**Comment by andrewda** [comment]
We can't help you with Steam issues. The same question has been asked many times in the past couple days: https://github.com/seishun/node-steam/issues?q=is%3Aissue+is%3Aclosed

**Comment by seishun** [comment]
^
