### ISSUE TITLE
Cannot install steam :((((

### ISSUE THREAD

**Issue by Xeroner** [seishun/node-steam#342]
`root@ns396748:/var/www/csboxpl# npm install steam
npm WARN install:window-size@0.1.2 ENOENT: no such file or directory, chmod '/var/www/csboxpl/node_modules/steam/node_modules/steam-resources/node_modules/protobufjs/node_modules/yargs/node_modules/window-size/cli.js'
- ascli@1.0.0 node_modules/ascli
- balanced-match@0.3.0 node_modules/balanced-match
- camelcase@2.1.0 node_modules/camelcase
- concat-map@0.0.1 node_modules/concat-map
- brace-expansion@1.1.2 node_modules/brace-expansion
- decamelize@1.1.2 node_modules/decamelize
- invert-kv@1.0.0 node_modules/invert-kv
- lcid@1.0.0 node_modules/lcid
- minimatch@3.0.0 node_modules/minimatch
- number-is-nan@1.0.0 node_modules/number-is-nan
- is-fullwidth-code-point@1.0.0 node_modules/is-fullwidth-code-point
- code-point-at@1.0.0 node_modules/code-point-at
- os-locale@1.4.0 node_modules/os-locale
- path-is-absolute@1.0.0 node_modules/path-is-absolute
colour@0.7.1 node_modules/colour -> node_modules/steam/node_modules/steam-resources/node_modules/protobufjs/node_modules/ascli/node_modules/colour
optjs@3.2.2 node_modules/optjs -> node_modules/steam/node_modules/steam-resources/node_modules/protobufjs/node_modules/ascli/node_modules/optjs
- string-width@1.0.1 node_modules/string-width
- window-size@0.1.4 node_modules/window-size
- wrap-ansi@1.0.0 node_modules/wrap-ansi
- cliui@3.1.0 node_modules/cliui
- wrappy@1.0.1 node_modules/wrappy
- once@1.3.3 node_modules/once
- inflight@1.0.4 node_modules/inflight
- glob@5.0.15 node_modules/glob
- y18n@3.2.0 node_modules/y18n
- yargs@3.32.0 node_modules/yargs
- protobufjs@5.0.1 node_modules/protobufjs
npm WARN EBUNDLEOVERRIDE Replacing bundled steam > steam-resources with new installed version
root@ns396748:/var/www/csboxpl#`

Help me please

**Comment by seishun** [comment]
#307
