### ISSUE TITLE
Auto-accept steam invites and gamesPlayed problem

### ISSUE THREAD

**Issue by MrKoijk** [seishun/node-steam#343]
Hi!
Today I launched my steam messages bot. But two parts of my js aren't working:
```
// accept users that added you when you were offline.
steamClient.on('relationships', function() {
  for (var friend in steamClient.friends) {
    if (steamClient.friends[friend] == 2) {
      steamClient.addFriend(friend);
      console.log('SteamID ' + friend + ' added!')
    }
  }
});

// accept users that add's you while you're online.
steamClient.on('friend', function(SteamID, Relation) {
  if (Relation == 2) {
    steamClient.addFriend(SteamID);
    console.log(SteamID + " Accepted")
  }
});
```
and
`steamClient.gamesPlayed([220, 440, 570, 730]);`

What am I doing wrong? Can someone help me?

**Comment by MrKoijk** [comment]
To explain I paste console problem-info:
```
    steamClient.gamesPlayed([220, 440, 570, 730]);
                ^

TypeError: steamClient.gamesPlayed is not a function
```
when I remove `steamClient.gamesPlayed([220, 440, 570, 730]);` from js everything works just fine and console prints standard `Logged in!` but program isn't accepting any invites on steam :/

**Comment by mnzt** [comment]
Create a steam user from the client. It's in the main help docs, along with here. https://github.com/seishun/node-steam/tree/master/lib/handlers/user

`steamClient` != `steamUser`.

**Comment by seishun** [comment]
^

**Comment by MrKoijk** [comment]
Okay I changed `steamClient.gamesPlayed([220, 440, 570, 730]);` to `steamUser.gamesPlayed([220, 440, 570, 730]);` and I have `var steamUser = new Steam.SteamUser(steamClient);` in js file but console prints this error:
```
                throw Error("Illegal value for "+this.toString(true)+" of type "
+this.type.name+": "+val+" ("+msg+")");
                ^

Error: Illegal value for [object Object] of type message: number (object expected)
```

**Comment by seishun** [comment]
Please read the [documentation](https://github.com/seishun/node-steam/tree/master/lib/handlers/user#gamesplayedgamesplayed). This is not a help desk.
