### ISSUE TITLE
Creating sentryfile ("callback" of "updateMachineAuth")

### ISSUE THREAD

**Issue by fheinrich** [seishun/node-steam#344]
Hi, so I got a question.

Full code:
http://pastebin.com/d27G5TiB

So its creating the sentry file but its getting stucked there like the process is not responding, I cant even jump out of the program with ^C.

Hope you can help. Thanks

**Comment by seishun** [comment]
The issue tracker is for library issues. Unless the hang happens inside a node-steam function, I can't help you. And I don't even see a callback for 'updateMachineAuth' in your code.

**Comment by Jefftopia** [comment]
Can we get some better documentation on how to login? I see some tutorials showing `shaSentryFile` but I get an invalid field error. I'm just not sure what I need other than username and pass.

**Comment by M-usamashahid** [comment]
@Jefftopia  i am also facing same issue

**Comment by seishun** [comment]
@Jefftopia meanings of Protobuf fields are described [here](https://github.com/seishun/node-steam/wiki/Protobufs). Feel free to contribute if you feel that the descriptions are lacking.

**Comment by jabbink** [comment]
I never had an issue connecting with this library.

Some basic copypaste code from a random project:

    var util = require('util');
    var SteamTotp = require('steam-totp');
    var Steam = require('steam');

    var steamClient = new Steam.SteamClient();
    var steamUser = new Steam.SteamUser(steamClient);

    var SteamRegistrar = new SteamKeys.SteamRegistrar(steamUser, steamClient, false);

    steamClient.connect();
    steamClient.on('connected', function() {
      steamUser.logOn({
    	account_name: STEAM_USER,
    	password: STEAM_PASSWORD,
    	sha_sentryfile: SENTRY_SHA,
    	two_factor_code: SteamTotp.generateAuthCode(TOTP_SECRET)
      });
    });
    steamClient.on('logOnResponse', function(logonResp) {
    	if (logonResp.eresult == Steam.EResult.OK) {
    		util.log('logged in on steam');
    	} else {
    		util.log('Failed to login', logonResp);
    	}
    });

**Comment by Jefftopia** [comment]
@seishun Thanks, that doc is very helpful. Somehow missed it last night. 
@jabbink I'm a big fan of concrete examples on top of documentation. Thanks for that.

**Comment by Jefftopia** [comment]
I successfully login with steam guard code, and use the following to keep my sentry file current. 

```
        client.steamUser.on('updateMachineAuth', function(e) {
            fs.writeFileSync('sentry', e.bytes);
        });        
```

But I fail to login in successive attempts. I have to continue requesting guard codes. What am I doing wrong?

**Comment by andrewda** [comment]
Sentry files are obsolete while using your mobile Steam Guard code. You will have to generate a new one using SteamTOTP.

**Comment by Jefftopia** [comment]
@andrewda How?

@jabbink's example uses `two_factor_code: SteamTotp.generateAuthCode(TOTP_SECRET)`

What is TOTP_SECRET and how do I generate that?

**Comment by andrewda** [comment]
```javascript
two_factor_code: SteamTotp.generateAuthCode(shared_secret)
```

You need your shared_secret to generate the auth code.

**Comment by Jefftopia** [comment]
@andrewda Does node-steam provide an interface for acquiring one's shared_secret?

**Comment by andrewda** [comment]
No.

> DoctorMcKay
You get it after enabling 2FA: https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#enabletwofactorcallback
>

**Comment by seishun** [comment]
Closing due to lack of follow up by OP.
