### ISSUE TITLE
Is there oAuth?

### ISSUE THREAD

**Issue by dandart** [seishun/node-steam#346]
After using passport-steam, can I use the tokens obtained to log into this?

**Comment by scholtzm** [comment]
Of course not.

**Comment by dandart** [comment]
Why of course not? It wasn't obvious, I just couldn't find mention.

I'd love to see it added, if they support using the APIs through it, which should be available for security purposes, I'd be using it by default.

I'll see what they say and see if I can make a PR if so.

**Comment by jabbink** [comment]
>Why of course not? It wasn't obvious, I just couldn't find mention.

It is obvious. This library is used to interact with full access to Steam accounts (Chat, Trade, "play games"). Obviously you *cannot* take over a Steam Account after some random user logs in on your website over OAuth, which Valve made available to verify a Steam user to your service, not to give away the entire account to you (the webmaster)...

**Comment by mnzt** [comment]
I'm a maintainer of passport-steam. This isn't possible. You need a username, password, and 2fa code to log in and use node-steam as a bot. OAuth/OpenID doesn't work like this. It relies on a 3rd party service to 'OK' the user. There is never an exchange of log in details.

**Comment by dandart** [comment]
Ah, I assumed you were using their open APIs made available after a token was valid.

So you're using the same calls as the browser/client makes, rather than those approved by steam for third party applications? Or have I understood that wrong?

I realise there's no login details sent using oauth, which is part of what makes it secure. I'm guessing from your response that Steam just wouldn't act upon requests to the same endpoints if just using the token?

Or is it that they don't fully support tokens yet and all passport-steam does is verify your account exists?

**Comment by mnzt** [comment]
At the moment passport-steam hits Steam's auth servers, gets an 'okay this person is real' response, and then pulls in some public-facing data about the user, ie: avatar, display name, steamid.

As I'm aware, there's nothing on the roadmap for updating this, as it works.

**Comment by dandart** [comment]
Ah okay thanks

**Comment by scholtzm** [comment]
The only thing Valve provides is user's verified 64-bit SteamID, that's it. They also use OpenID protocol, not OAuth. (They do have OAuth endpoints, but not available for public use AFAIK.)
