### ISSUE TITLE
How to deal with an Unhandled 'error' event?

### ISSUE THREAD

**Issue by iJamesPHP** [seishun/node-steam#348]
I'm in the process I've trying to create a bot that will just accept all trade offers.

I have this code so far:

```
var Steam = require('steam');
var SteamWebLogOn = require('steam-weblogon');
var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamWebLogOn = new SteamWebLogOn(steamClient, steamUser);
steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: 'us',
    password: 'ps'
  });
});
steamClient.on('logOnResponse', function(logonResp) {
  if (logonResp.eresult == Steam.EResult.OK) {
    steamWebLogOn.webLogOn(function(webSessionID, cookies){
      console.log('connected');
    });
  }
});

```

I always get the same error from my terminal:

```
 events.js:141
      throw er; // Unhandled 'error' event
```

I've posted about this before with a more vague question and got a very negative response so I'm trying again with a more specific question, how do I deal with this error and get on to actually getting a successful logon using node-steam.

Any help is very much appreciated, before you ask I have read all the documentation on this repo and the weblogon repo but still stuck.

Much appreciated,

James

**Comment by mnzt** [comment]
You evidently have not read the documentation, because it tells you the error events.

```
steamClient.on('error', (err) => console.log(err))
```
You're welcome.

**Comment by iJamesPHP** [comment]
I've just realised that this issue section is for library issues and not help. Is there any way I can ask for help outside the issues section?

**Comment by iJamesPHP** [comment]
Thank you mnzt

**Comment by seishun** [comment]
You already got two answers in the previous issue saying that you need to handle the 'error' event.
