### ISSUE TITLE
Error: Disconnected at SteamClient._disconnected

### ISSUE THREAD

**Issue by istoro** [seishun/node-steam#353]
Hello. I have a problem.
In about 7-8 hours afer starting the node steam client I get this message "Error: Disconnected at SteamClient._disconnected". If I am right, this problem occurs because the session was dead.
How can I decide this problem? Reconnection? If the solution of this problem is reconnection, can you take me code? Thank you very much.
P.S. Sorry for my english.

**Comment by jabbink** [comment]
Is there any reason why you got logged out? For example logging in on Steam on another computer?

Or was there (scheduled) maintenance on Valve's end?

Also subscribe to the `'error'` event. It fires when this happens, and `node-steam` should try to automatically reconnect: https://github.com/seishun/node-steam#error

**Comment by istoro** [comment]
I use steam-trade-offers and some time later it's not working (steam trade offers is not return any answer), then in about 1 hour I get this message: "events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: Disconnected
    at SteamClient._disconnected (/srv/steam/node_modules/steam/lib/steam_client.js:186:24)
    at emitOne (events.js:90:13)
    at Connection.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12)"

**Comment by scholtzm** [comment]
That's expected behaviour. Check the README, especially the `error` event.

**Comment by istoro** [comment]
What i must do in this case?
