### ISSUE TITLE
Multiple bots wont login - only the first

### ISSUE THREAD

**Issue by bahagiga** [seishun/node-steam#355]
Hi,

I haven't had success trying to login with multiple bots and it might be a duplicate or similar issue to #319. My application uses the express.js framework however below I have tried to provide a simple example. I haven't been able to get around it but what happens is that only the first bot manages to login.

A minimal sample

    // app.js    
    var Bot = require('./bot');

    var bot1= new Bot();
    bot1('bot1', 'pw123');

    var bot2 = new Bot();
    bot2('bot2', 'pw456');

And the bot

    // bot.js
    var Steam = require('steam');
    var steamClient = new Steam.SteamClient();
    var steamUser = new Steam.SteamUser(steamClient);
    var steamFriends = new Steam.SteamFriends(steamClient);

    module.exports = function() {
        return function (username, pw) {
            steamClient.connect();
            steamClient.on('connected', function() {
                steamUser.logOn({
                    account_name: username,
                    password: pw
                });
            });

            steamClient.on('logOnResponse', function(logonResp) {
                if (logonResp.eresult == Steam.EResult.OK) {
                    steamFriends.setPersonaState(Steam.EPersonaState.Online);
                    console.log('logged in as: ', username);
                }
            });

            steamClient.on('debug', function(msg) {
                console.log('debug:', msg);
            });

            steamClient.on('error', function(err) {
                console.log('error:', err);
            });
        };
    };

Here the log output after running `node.exe app.js`

    debug: connecting to 72.165.61.176:27017
    debug: socket timed out                 
    debug: socket timed out                 
    debug: socket closed                    
    debug: socket closed                    
    debug: connecting to 146.66.152.15:27017
    debug: connecting to 146.66.152.15:27017
    debug: socket timed out                 
    debug: socket timed out                 
    debug: socket closed                    
    debug: socket closed                    
    debug: connecting to 72.165.61.185:27017
    debug: connecting to 72.165.61.185:27017
    debug: connected                        
    debug: connected                        
    debug: encrypt request                  
    debug: encrypt request                  
    logged in as:  bot1
    logged in as:  bot2

I appreciate any directions on this.
//Baha

**Comment by seishun** [comment]
From looking at the log output, it looks like both bots logged in?

**Comment by bahagiga** [comment]
Only the first one actually manages to login. After further logging it seems that they are getting the same client instance id, nonce and so on which I assume causes the mishap.

Extracting the `steamClient`, `steamUser` and `steamFriends` into the constructor function solved it.

    // bot.js
    var Steam = require('steam');
    
    module.exports = function() {
    
    var steamClient = new Steam.SteamClient();
    var steamUser = new Steam.SteamUser(steamClient);
    var steamFriends = new Steam.SteamFriends(steamClient);

        return function (username, pw) {
            steamClient.connect();
            steamClient.on(............

Thanks for node-steam @seishun 

//Baha
