### ISSUE TITLE
SteamID returning zero when Steam Community is down

### ISSUE THREAD

**Issue by kondax** [seishun/node-steam#356]
When the Steam Community was down earlier, for some unknown reason node-steam returned the account as 76561197960265728. Of course this is the 64-bit int, plus the account id - but the account id was zero, so it just returned 76561197960265728 instead of the actual steam id.

Sorry for the minimal message, github is screwed for me right now - no styling or scripts are loading.

**Comment by seishun** [comment]
Was the SteamClient logged on at the time?

**Comment by kondax** [comment]
I believe it was logged on, although no sure way of checking. I'd assume
so, otherwise I would've expected an error rather than a 0 for the account
id.

**Comment by seishun** [comment]
It probably wasn't. '76561197960265728' is the initial SteamID value that's automatically set when calling `logOn`.

**Comment by kondax** [comment]
Au right. Hmm, not sure why it didn't error that the account never logged
in - strange.
