### ISSUE TITLE
Disconnecting from Steam

### ISSUE THREAD

**Issue by NBNGaming** [seishun/node-steam#358]
Sometimes my application randomly disconnects from the Steam. All login data are correct. Steam client is turned off.
`app-2 (err): Error: Disconnected
app-2 (err):     at SteamClient._disconnected (/bot/node_modules/steam/lib/steam_client.js:186:24)
app-2 (err):     at Connection.emit (events.js:107:17)
app-2 (err):     at TCP.close (net.js:484:11)`
Node.js v0.12.14
npm 2.15.1

**Comment by seishun** [comment]
https://github.com/seishun/node-steam/search?q=disconnected&type=Issues&utf8=%E2%9C%93
