### ISSUE TITLE
Error 88 - Mobile Auth

### ISSUE THREAD

**Issue by error88** [seishun/node-steam#362]
Hi

When I use email authentication it all works absolutely fine and my bot stays logged in for long periods of time.

When I use mobile authentication it logs in fine and works fine for a while. Then at midnight it just shuts off at exactly 12PM with **ERROR 88**. It's not every night as far as I'm aware but every few days it happens.

What is the cause of this? How can I fix this?

I've tried setting the clock to sync with Google and other timezones but that hasn't fixed it.

Any help is much appreciated, cheers

Jack

**Comment by shaunidiot** [comment]
https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd#L96

TwoFactorCodeMismatch

Probably got logged out by Steam itself. Just relogin when such things happen.

**Comment by error88** [comment]
I am aware of what the error stands for but that is not really a fix. It cannot be expected that everyone must relogin again at midnight every night.

**Comment by scholtzm** [comment]
> it just shuts off

What does this even mean? Do you get disconnected?

> at exactly 12PM

Looks like your internet provider is doing this.

> with ERROR 88

What happens if you retry?

**Comment by error88** [comment]
Hi Scholtzm

> What does this even mean? Do you get disconnected?

It runs on my Digital Ocean server. Simply it errors with error 88 and that's that. The node session ends.

> Looks like your internet provider is doing this.

I have doubts that it is my ISP as it runs externally through DO.

> What happens if you retry?

This error has been a recurring issue for the last 1-2 months. Everytime in the past I have been forced to just retry but that hasn't sorted the issue. Before this never was a problem.

I'm happy to share more information if need be.

Cheers

**Comment by error88** [comment]
Here are logs of my bots getting the error:

https://i.gyazo.com/39358d6659126093e0b16a9cd904dbe1.png

**Comment by shaunidiot** [comment]
@scholtzm Pretty sure it's just normal Steam problem where it logs the user out after X hours.

**Comment by scholtzm** [comment]
Well, it certainly isn't library issue so I guess you should redirect your question elsewhere, e.g. /r/SteamBot.

> Pretty sure it's just normal Steam problem where it logs the user out after X hours.

@shaunidiot Logs the user out? Why? Haven't seen this error happen ever, other than getting disconnected by Steam going down occasionally.

**Comment by seishun** [comment]
>Simply it errors with error 88 and that's that.

That doesn't make sense. If you mean the 'error' event, then that doesn't have an error code.

**Comment by error88** [comment]
> That doesn't make sense. If you mean the 'error' event, then that doesn't have an error code.

What other information would you like me to provide? It logs out of the user and returns error 88 TwoFactorCodeMismatch. I don't understand your confusion? As far as I am aware the error event does have an error code.

**Comment by scholtzm** [comment]
Well, it doesn't. 😄

**Comment by error88** [comment]
event.eresult

**Comment by scholtzm** [comment]
In that case that's not an `error` event.

**Comment by error88** [comment]
Regardless, is there any fix for this? Any ideas?

/r/SteamBot state it as the timezone which it isn't.

**Comment by seishun** [comment]
>event.eresult

There is no such thing in node-steam. Perhaps you're using an old version.

>Regardless, is there any fix for this?

This doesn't seem to be a library issue, so you won't get help here. I guess your best bet would be to just reconnect.

**Comment by error88** [comment]
For what reasons does it not appear to be a library issue? How can you tell if you've never even heard or seen it before?

**Comment by scholtzm** [comment]
> /r/SteamBot state it as the timezone which it isn't.

So why haven't you posted there yet?

**Comment by seishun** [comment]
>For what reasons does it not appear to be a library issue? How can you tell if you've never even heard or seen it before?

Because EResult comes from Steam. node-steam passes it on, just like it's supposed to. Unless you think that Steam doesn't actually send EResult 88 or that node-steam should behave differently when receiving it, there's nothing to discuss here.

**Comment by Aareksio** [comment]
I'm just guessing - you got disconnected because of the weekly maintenance, as the last one was this night, then your application tried to log in back, but as you didn't supply a new steamguard code you got 88 in response.

If that's the story, the problem is in your code, not the library.

**Comment by Committing** [comment]
@Aareksio I believe you get error 85 for invalid code on mobile auth. Also I get this error too.

**Comment by scholtzm** [comment]
85 is if you don't provide a code at all.
