### ISSUE TITLE
Can't seem to call gamesPlayed

### ISSUE THREAD

**Issue by HybridFox** [seishun/node-steam#364]
I might be stupid and doing this completely wrong, but i can't seem to figure this out:

> steamUser.gamesPlayed({games_played: {
      GamePlayed: {
        game_id: 238090
      }
    }});

> Error: .CMsgClientGamesPlayed.GamePlayed#GamePlayed is not a field: undefined

**Comment by seishun** [comment]
1. `games_played` is a repeated field, so the `games_played` property must be an array.
2. Messages are represented as simple objects in JS. The message type is inferred, so "GamePlayed" shouldn't be anywhere.
3. `fixed64` are represented as strings.

```js
steamUser.gamesPlayed({games_played: [
  {
    game_id: '238090'
  }
}});
```

**Comment by HybridFox** [comment]
Thanks alot!
