### ISSUE TITLE
Losing connection on SteamUser object after a while

### ISSUE THREAD

**Issue by HybridFox** [seishun/node-steam#369]
I'm using the object SteamUser every 5 minutes with setInterval, but after i couple of hours i get this error:
```
this._connection.send(Buffer.concat([header.toBuffer(), body]));
                  ^
TypeError: Cannot read property 'send' of undefined`
    at SteamClient._send (C:\emu\node_modules\steam\lib\steam_client.js:114:19)
    at SteamClient.send (C:\emu\node_modules\steam\lib\steam_client.js:123:8)
```
Is there anyway to keep the connection alive?

**Comment by seishun** [comment]
No, you can't prevent Steam from going down. All you can do is reconnect on disconnections and not call SteamUser methods while logged off.

**Comment by HybridFox** [comment]
Oh, this is just steam servers going offline?

**Comment by seishun** [comment]
That's one possible reason.

**Comment by HybridFox** [comment]
Okay thanks!
