### ISSUE TITLE
Can't login when using sentry hash

### ISSUE THREAD

**Issue by serge1peshcoff** [seishun/node-steam#370]
So, I am trying to write a bot using this module. I want to login use 2FA. It works, when I provide an `two_factor_code`, but fails if I provide only `sha_sentryfile` with error_code 85. Here is my code:

    var authCode = '<code>'; // code received by email
    var logOnOptions = {
      account_name: '<account_name>',
      password: '<password>'
    };

    try
    {
      logOnOptions.sha_sentryfile = getSHA1(fs.readFileSync('sentry'));
    }
    catch (e) {
      logOnOptions.two_factor_code = authCode;
    }
    console.log(logOnOptions);

    var steamClient = new Steam.SteamClient();
    var steamUser = new Steam.SteamUser(steamClient);
    var steamFriends = new Steam.SteamFriends(steamClient);
    var steamWebLogOn = new SteamWebLogOn(steamClient, steamUser);

    ....

    steamClient.on('logOnResponse', function(logonResp) {
      console.log(xinspect(logonResp));
      if (logonResp.eresult === Steam.EResult.OK) {
        console.log('Logged in!');
        steamFriends.setPersonaState(Steam.EPersonaState.Online);
      }
    });

    steamClient.on('error', function(res1, res) {

    });

    steamUser.on('updateMachineAuth', function(sentry, callback) {
      fs.writeFileSync('sentry', sentry.bytes);
      callback({ sha_file: getSHA1(sentry.bytes) });
    });

    function getSHA1(bytes) {
      var hash = crypto.createHash('sha1');
      hash.update(bytes);
      return hash.digest();
    }

When I use geniune two_factor_code, here is the output:

    "eresult" (number) => 1
    "out_of_game_heartbeat_seconds" (number) => 9
    "in_game_heartbeat_seconds" (number) => 9
    "public_ip" (number) => 3642354822
    "rtime32_server_time" (number) => 1466950413
    "account_flags" (number) => 2637957
    "cell_id" (number) => 7
    "webapi_authenticate_user_nonce" (string) => pTWPAwyCxYPKYhVrIYg
    "cell_id_ping_threshold" (number) => 11
    "use_pics" (boolean) => true
    "vanity_url" (string) => 
    "client_supplied_steamid" (string) => <steam_id_here>
    "ip_country_code" (string) => RU
    "count_loginfailures_to_migrate" (number) => 0
    "count_disconnects_to_migrate" (number) => 0
    "client_instance_id" (string) => <instance_id_here>

But when sentry file is present, here is what I am getting:

    "eresult" (number) => 85
    "eresult_extended" (number) => 85
    "client_supplied_steamid" (string) => <steam_id_here>
    "count_loginfailures_to_migrate" (number) => 0
    "count_disconnects_to_migrate" (number) => 0

What am I doing wrong, if so?

**Comment by seishun** [comment]
AFAIK you need to provide two_factor_code every time. EResult values can be found [here](https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd).

**Comment by scholtzm** [comment]
Just fyi, once you switch to 2FA, sentry file serves no purpose and is basically ignored.

**Comment by seishun** [comment]
@scholtzm Perhaps you would be interested in adding this information to the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs)?

**Comment by scholtzm** [comment]
Added a short note.

**Comment by yesworld** [comment]
> AFAIK you need to provide two_factor_code every time. EResult values can be found [here](https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd).

Is it possible to somehow save 2FA on the server?

**Comment by scholtzm** [comment]
@yesworld You can generate 2FA codes programatically with `steam-totp`.

**Comment by yesworld** [comment]
Thanks for the answer!
Last question, how can I get **shared_secret** to generate through the **steam-totp**?
