### ISSUE TITLE
Avalible fields for steamRP.upload?

### ISSUE THREAD

**Issue by mindcrimes** [seishun/node-steam#372]
hi,
I'm trying to use steamRP but i cant seem to find what field i should use for uploading, 
    steamRP.upload( {
        body: {
		status: "Competitive Inferno [ 3 : 10 ]",
		version: "13503",
		time: "4411.216601",
		"game:mode": "competitive",
		"game:mapgroupname": "mg_de_inferno",
		"game:map": "random",
		"game:server": "kv",
		"watch": "1",
		"game:score": "[ 3 : 1]"
		}
	})
  ive already tried body and RP but i get an error about an unknown field

**Comment by seishun** [comment]
[body is a CMsgClientRichPresenceUpload object.](https://github.com/seishun/node-steam/tree/master/lib/handlers/rich_presence#uploadbody)

You'll need to serialize the RP body yourself and put it in `rich_presence_kv`. I couldn't find a library that supports serializing binary VDF, but you can look how it's done [here](https://github.com/joshuaferrara/node-csgo/blob/master/helpers/VDF.js).
