### ISSUE TITLE
Alternative to disconnect a bot 

### ISSUE THREAD

**Issue by bahagiga** [seishun/node-steam#374]
Hi,

While building an API I have stumbled into this issue where I can't seem to disconnect a specific bot. I have searched the closed issues but no luck and going through the docs it seems I can only disconnect a bot if I have the [SteamClient](https://github.com/seishun/node-steam#steamclient). I have tried to create a new SteamClient and assign it the steamID and other crazy things in despair trying to obtain the SteamClient.

I feel like I am overlooking something trivial whilst trying to obtain the SteamClient.
Any help or hint is appreciated.

//Baha

**Comment by seishun** [comment]
That doesn't make sense. How are you connecting to Steam without a SteamClient instance?

**Comment by bahagiga** [comment]
Hi,

Thanks for the fast response. Please let me clarify, I do have a SteamClient instance when connecting. That works perfectly fine. I have something similar to this:

    // BotController: connect endpoint which logs in..
    const botConfig = {
      userName: steamId,
      password: password,
    };

    const bot = new SteamBot();
    bot.run(botConfig);

SteamBot is something like this:

    // SteamBot
    const SteamBot = function SteamBot() {
      const steamClient = new Steam.SteamClient();
      const steamUser = new Steam.SteamUser(steamClient);
      const steamFriends = new Steam.SteamFriends(steamClient);

     this.run = (options) => {...};
     // etc..

This all works and connects. 
My current issue however is when a request comes in for i.e. `url/disconnect/:botId` I have to obtain a SteamClient to call `disconnect()` on it, but how? My last attempt was storing some data in redis and create a new SteamClient and disconnect it.

    // BotController: disconnect endpoint..
    redisClient.hgetall(steamId, (err, bot) => {
      if (err) {
        // stuff..
      } else {
        const steamClient = new Steam.SteamClient();
        steamClient.steamID = bot.steamID;
        steamClient.sessionID = bot.sessionID;
        steamClient.disconnect();
        // ...

Crazy, I know :/ 

// Baha

**Comment by scholtzm** [comment]
You need to retrieve that client instance you initially created and call `disconnect` on it.

```js
const SteamBot = function SteamBot() {
  const steamClient = new Steam.SteamClient(); // this one
```

**Comment by seishun** [comment]
What @scholtzm said. You can only disconnect using the same instance you used to connect. How you store and retrieve them is up to you.

**Comment by bahagiga** [comment]
I see, thanks guys.
