### ISSUE TITLE
crypto.publicEncrypt Error

### ISSUE THREAD

**Issue by ReidPritchard** [seishun/node-steam#375]
When ever I try to run any program I write I get this error:

```
TypeError: Object #<Object> has no method of 'publicEncrypt'
// (index.js line 6)
```
I'm assuming I installed the wrong way or am missing a step in the installation.
Nearly positive this will end up being some silly mistake on my part.

Anyway love what you guys have done, just have to get it working :+1: 
Thanks,
Reid

**Comment by buddhapest** [comment]
you're using the wrong version of node

**Comment by scholtzm** [comment]
https://github.com/seishun/node-steam/blob/master/package.json#L22
