### ISSUE TITLE
Steam Groups

### ISSUE THREAD

**Issue by zephylac** [seishun/node-steam#377]
Hi, I found this sample in your code
[https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L273-L288]

And I didn't found any commands attached to it. I would like to use this to retrieve members's steam IDs for a given group. And it would return something like this
steam group id (optionnal) {
     steam ID #1 member
     steam ID #2  member
     steam ID #3 member
     ........
}
The order of the members or their group permission is not important to know

**Comment by seishun** [comment]
You can edit your issues. No need to spam.

This message is for friend tags (visible only to you), not for Steam groups.

**Comment by zephylac** [comment]
didn't want to spam the issue, It submitted an issue when I type enter. But I didn't mean that I just wanted to skip a line.

But my issue is still unsolved
