### ISSUE TITLE
steam group

### ISSUE THREAD

**Issue by zephylac** [seishun/node-steam#378]
This sample of code is not use, I would like to use it. i tried to create an event myFriendGroup which contains the groupID and the steam ID  of the members. I'ld liketo be formatted like that:
group{
          groupID{}
          membersID{}
}
[https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L273-L288]

`handlers[CMsgClientFriendsGroupsList] = function(data) {
schema.CMsgClientFriendsGroupsList.decode(data).FriendGroupsMembership.forEach(function(group){
group = Steam._processProto(group);   

this.emit('myFriendGroup', group);

}.bind(this));
};`

**Comment by seishun** [comment]
Again, you're aware that this is for friend tags, not for Steam groups, right?

**Comment by zephylac** [comment]
oh, ok sorry. Do you know about something steam groups, where I could retrive the members.There is one event in properties but it's fired at the beginning. If the group changes I'll not be able  to see it

**Comment by seishun** [comment]
AFAIK Steam client doesn't receive information about Steam group members at all. You have to use the WebAPI for that.

**Comment by zephylac** [comment]
So I guess that https://github.com/DoctorMcKay/node-steamcommunity is a web API?
