### ISSUE TITLE
gamesPlayed format

### ISSUE THREAD

**Issue by rafalolszewskii** [seishun/node-steam#381]
I can guess that `gamesPlayed` is an array, but it is not described anywhere what is the format of that array, if I want to use it for CS:GO for example, if I use:

``` js
   steamUser.gamesPlayed({
      "game_id": "730"
    });
```
It doesn't work. It gives error:
```
.CMsgClientGamesPlayed#game_id is not a field: undefined
```

**Comment by Efreak** [comment]
So far as I know, I'm using:

```
steamUser.gamesPlayer({
        'games_played':[
                {'game_id':440}
        ]
});
```

Unfortunately, I somehow have a confusing way of parsing what I'm doing (currently I'm passing an array of ints to [this](https://github.com/Steam-Chat-Bot/node-steam-chat-bot/blob/master/lib/chatBot.js#L435)...). Somehow, one of those is working with `bot.setGames(['440',[214610,282800]);`.

I should probably be figuring out/fixing my own code before advising someone else...

**Comment by jwigley** [comment]
It's an array of game_id key/pair objects:

 ```js 
steamUser.gamesPlayed([{
      "game_id": "730"
 }]);
```

 ```js 
steamUser.gamesPlayed([{
      "game_id": "730"
 },{
      "game_id": "731"
 }]);
```

**Comment by seishun** [comment]
[gamesPlayed](https://github.com/seishun/node-steam/tree/master/lib/handlers/user#gamesplayedgamesplayed) takes a [CMsgClientGamesPlayed](https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/steamclient/steammessages_clientserver.proto) object.

The structure of protobuf objects as passed and received by node-steam is described [here](https://github.com/seishun/node-steam#protobufs).

So you could call `gamesPlayed` like this:

```js
user.gamesPlayed({
  games_played: [{
    game_id: '731',
    game_flags: 1234134 // god knows what this is
  }, {
    // other games
  }],
  client_os_type: 123123 // god knows what this is
});
```

Of course you can skip fields that are `optional`.

Suggestions on how the docs could be made clearer are welcome.
