### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Gacnt** [seishun/node-steam#386]
Everything still works fine, but haven't seen a commit since last year. Just wondering if this project is still maintained or if @seishun  has moved on. Thanks!

**Comment by scholtzm** [comment]
The only thing I can think of that should be updated are the outdated bundled protobuf definitions. There have been quite a few updates since Dec 26th, 2015:

https://github.com/SteamRE/SteamKit/commits/master/Resources/Protobufs

There have been some `SteamLanguage` changes as well:

https://github.com/SteamRE/SteamKit/commits/master/Resources/SteamLanguage

**Comment by seishun** [comment]
@Gacnt 

Well, there isn't much to commit when everything works fine, is there? ;)

@scholtzm 

Resources are part of the npm package, not this repo. The package just contains whatever SteamRE had at the moment of publishing. I'd have to bump the version and re-publish to update them. Is there any node-steam functionality that would benefit from updated resources?

Either way, you can always update them manually by running `npm install` inside the module directory.

**Comment by Gacnt** [comment]
Nope not complaining at all, works fine for what I need it for, just didn't want to build something based around it then find out next big steam update you no longer have any interest in maintaining it them I'm up the river without a paddle

**Comment by scholtzm** [comment]
@seishun Yep, I know. But updating the package once every 3-6 months wouldn't hurt anyone and users would be provided with fresh resources.

I know it's possible to do manual update on user's end but running `npm install` in dependency folder to update it's resources is fairly clumsy and non-idiomatic for npm packages. Also, it's not even mentioned in the README.

**Comment by seishun** [comment]
>Also, it's not even mentioned in the README.

Right, I suppose the README could mention that the git installation step can be done at any time even if it's installed from npm. Do you have any suggestions on how it could be worded?

**Comment by dgdiablogist** [comment]
How come this is not on npm anymore?

**Comment by Gacnt** [comment]
It is, https://www.npmjs.com/package/steam

**Comment by Gacnt** [comment]
Just wondering if this is still maintained again, been 2 years since last commit.

**Comment by seishun** [comment]
Yes, it is.
