### ISSUE TITLE
What modules are needed?

### ISSUE THREAD

**Issue by yperz** [seishun/node-steam#388]
I need a list of modules that you need for the steam bot.

In cmd.exe, when I type node bot.js, it shows this:
![screenshot_20161121181950](https://cloud.githubusercontent.com/assets/19311942/20495003/3d8b4c5e-b017-11e6-9a54-167ef87e7cd6.png)

**Comment by seishun** [comment]
There is no file named "bot.js" in this repo.

**Comment by yperz** [comment]
That's the .js file I put the script into.

**Comment by seishun** [comment]
If you wrote the script, then surely you know which modules it `require`s.

**Comment by jabbink** [comment]
`npm install`ing or `yarn add`ing this library will automatically download anything this needs.

if you need more you have to install it separately and is unrelated to this library.
