### ISSUE TITLE
2 factor auth and sentry file

### ISSUE THREAD

**Issue by rtm516** [seishun/node-steam#390]
Hello i have modified the offerbot example to use 2 factor auth codes by changing the logon options to `logOnOptions.two_factor_code = SteamTotp.getAuthCode(sharedSecret);
this works but if i try and login using the sentry file after loging successfully it disconnects me. And from my knowledge, i can't trade for 1 week of authorising a machine.

Code: http://pastebin.com/gZpV9Dqv
Video: https://youtu.be/JPWXFsywCJE

Any help would be appreciated.

**Comment by scholtzm** [comment]
The sentry file is useless once you setup 2FA on your account.

**Comment by seishun** [comment]
⬆️
