### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by Electricboy7** [seishun/node-steam#393]
I keep getting an error when trying to "sudo npm install steam" on my vps. It is running Ubuntu 16.04 server and I doesn't seem to want to work. This is the error I am getting.

npm ERR! Linux 2.6.32-042stab120.11
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "steam"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install steam as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node-steam/npm-debug.log

**Comment by seishun** [comment]
1. Why are you using sudo?
2. In which directory are you running the command?

**Comment by Electricboy7** [comment]
1. I don't have permission to run the command properly, as I was not logged in as root
2. Inside of node-steam

**Comment by seishun** [comment]
...Then the issue is exactly what your error says: "Refusing to install steam as a dependency of itself"

I have no idea what you're trying to do, but either run `npm install steam` inside your own project's directory, or just `npm install` in node-steam's directory.
