### ISSUE TITLE
SteamFriends.prototype.ban not banning

### ISSUE THREAD

**Issue by G-ome** [seishun/node-steam#396]
Hi! First of all thanks for the great work.

I've come across an issue that I am not able to fix: I seem to be able to kick a person from a group chat, but not ban/unban, although the only thing that changes is the `chatAction` code AFAIK.

I made sure that the message is sent by console.logging `SteamClient.prototype._send`, and the only byte that differs between kick & ban are `02` turned into `03` in the body, but I guess you might already know that:
**Body of a kick:**
`<Buffer de 04 b2 00 00 00 88 01 c9 71 09 04 01 00 10 01 02 00 00 00>`
**Body of a ban:**
`<Buffer de 04 b2 00 00 00 88 01 c9 71 09 04 01 00 10 01 03 00 00 00>`

I have tried tinkering with the value of `chatAction`, but no luck.

Here's the related code:
https://github.com/seishun/node-steam/blob/master/lib/handlers/friends/index.js#L182
```javascript
SteamFriends.prototype.ban = function(steamIdChat, steamIdMember) {
  this._client.send({
    msg: EMsg.ClientChatAction
  }, new schema.MsgClientChatAction({
    steamIdChat: toChatID(steamIdChat),
    steamIdUserToActOn: steamIdMember,
    chatAction: Steam.EChatAction.Ban
  }).toBuffer());
};
```

Any idea what could be wrong? Thanks!

**Comment by seishun** [comment]
Does banning work when you log in using that account yourself? (with Steam.exe)

**Comment by G-ome** [comment]
Sigh, that was a group permission issue indeed, didn't even know that existed... Sorry for the trouble.

![image](https://cloud.githubusercontent.com/assets/12766310/21954377/ec2e2964-da4e-11e6-991d-ef3396c3acf0.png)

Cheers
