### ISSUE TITLE
Bot can't connect to the steam 

### ISSUE THREAD

**Issue by Prettyflackoscoundrel** [seishun/node-steam#403]
0|b        | USER SteamID is 76561198359xxxxx
0|b        | USER PAss is Qwerty123
0|b        | USER PAss is Qwerty123
0|b        | connecting to 72.165.61.175:27018
0|b        | connected
0|b        | encrypt request
0|b        | USER Login error: 5
0|b        | socket ended
0|b        | socket closed
0|b        | USER Catched steam error: {}

The password and account is 100% valid 
What can be the problem ?

**Comment by MajorErection** [comment]
If I'm not mistaken error 5 is invalid password.

**Comment by joelsouza** [comment]
Check if you account has Steam Guard activated in your [Steam account](https://store.steampowered.com/account/)

For test purposes, disable all Steam Guard options and try again.

**Comment by henricavalcante** [comment]
Don't work with steam guard?

**Comment by batizisanya** [comment]
Its work with steamguard, use steam-totp.
