### ISSUE TITLE
Steam Guard code always needed instead of sentry file

### ISSUE THREAD

**Issue by Dipricyn** [seishun/node-steam#404]
I have tried different approaches of using the sentry file in exchange for the Steam Guard code but I can't get it to work no matter what I try.
I created a test script but I always get EResult: 85 which is AccountLoginDeniedNeedTwoFactor.

```
var log = require("./log"), Steam = require("steam"), steamClient = new Steam.SteamClient(), steamUser = new Steam.SteamUser(
		steamClient), crypto = require("crypto"), steamGC = new Steam.SteamGameCoordinator(steamClient, 730);

function getSHA1(bytes) {
	var shasum = crypto.createHash('sha1');
	shasum.end(bytes);
	return shasum.read();
}

var logOnOptions = {
		account_name : 'USERNAME',
		password : 'PASSWORD',
		two_factor_code: null, //not needed for login using sentry file
	};
var sentry;
try {
	sentry = fs.readFileSync('sentry');
	if(sentry){
		logOnOptions.sha_sentryfile = getSHA1(sentry);
		log.log("sentry file loaded");
	}else{
		log.log("Empty sentry file.");
	}
} catch (e) {
	log.log("Error loading sentry: " + e);
}

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);

steamClient.connect();
steamClient.on('connected', function() {
	steamUser.logOn(logOnOptions);
});

steamClient.on('logOnResponse', function(logonResp) {
	if (logonResp.eresult === Steam.EResult.OK) {
		log.log('Logged in!');
	}else{
		log.log("Eresult: "+logonResp.eresult);
	}
});

steamClient.on('servers', function(servers) {
	fs.writeFile('servers', JSON.stringify(servers));
});

steamUser.on('updateMachineAuth', function(sentry, callback) {
	fs.writeFileSync('sentry', sentry.bytes);
	log.log("Updated machine auth.");
	callback({
		sha_file : getSHA1(sentry.bytes),
		eresult : Steam.EResult.OK,
	});
});
```
I can confirm that steam servers send the same sentry file at the updateMachineAuth event which I already have.
How can I log in using the sentry file?

**Comment by Alex7Kom** [comment]
Sentry file can't be used if 2FA is enabled. See also #390

**Comment by seishun** [comment]
What @Alex7Kom said.

You're welcome to add this information to the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs).

**Comment by scholtzm** [comment]
It's actually mentioned in there: https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon

**Comment by seishun** [comment]
Maybe it would be useful to mention the meanings of some `eresult` values under CMsgClientLogonResponse as well.

**Comment by Dipricyn** [comment]
Just out of curiousity: how does the Steam client login at my PC? I have 2FA enabled and I automatically get logged in on system startup. Seems like the sentry file is used there.

**Comment by seishun** [comment]
I'd _guess_ it uses `login_key`. You can use [NetHook2](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2) to find out.

**Comment by scholtzm** [comment]
Yep, valid `username` + `login_key` combo will bypass the need for 2FA code.

**Comment by yesworld** [comment]
> Yep, valid `username` + `login_key` combo will bypass the need for 2FA code.

Please give an example of how this can be used, thank you.

**Comment by scholtzm** [comment]
@yesworld I would suggest implementing automated logins using 2FA which you will need anyway if you want a truly automated bot.
