### ISSUE TITLE
Check level before accepting F/R possible?

### ISSUE THREAD

**Issue by greenmoney** [seishun/node-steam#406]
Hi

Is it possible to do as stated in the title?

The getSteamLevel() method is used with SteamFriends. Does that mean it doesn't work unless the user is added already? Can I get steam level before adding them so I can check beforehand?

Code:
```
    steamFriends.on('friend', function(source, type) {
        var u = steamFriends.getSteamLevel([source]);
        console.log(u);
        if(type == Steam.EFriendRelationship.RequestRecipient) {
            steamFriends.addFriend(source);
        }
    });
```

Is this code invalid? it errors any time I run it

thank you

**Comment by seishun** [comment]
What error are you getting?

`getSteamLevel` is an asynchronous function, you have to give it a callback.

**Comment by greenmoney** [comment]
I should go to sleep, I was being stupid not adding a callback

Thank you !

Updated:

```
        steamFriends.getSteamLevel([source], function(data) {
            console.log(data);
        });
```
