### ISSUE TITLE
Issue on 'message' event

### ISSUE THREAD

**Issue by SavaDaniel** [seishun/node-steam#409]
I am trying to create a log of messages received from users.
```
steamFriends.on('message', function (sender, message, type, chatRoom) {
    fs.appendFile('logs/messagesLog', sender + ': ' + message + '\n');
});
```
If I do it like this, the 'messagesLog' file will look like this:

> 76561196532756184: 
> 76561196532756184: test
> 76561196532756184: 
> 76561196532756184: testmessage
> 76561196532756184: 
> 76561196532756184: testagain

I don't understand why it is writing the sender's id followed by a new line and rewriting the sender's id before actually writing the message.

**Comment by seishun** [comment]
Because you're ignoring the `type` parameter. It's likely `EChatEntryType.Typing` when the message is empty.
