### ISSUE TITLE
[Suggestion] Add Family Sharing options

### ISSUE THREAD

**Issue by Royalgamer06** [seishun/node-steam#410]
I'd really like to see options to authorize and deauthorize accounts for steam family sharing via node.js. This way if you need to use license of an app, you don't have to use your main account. 

Also, I am not even sure if it is possible to "authorize" family sharing a node.js client bot manually. Can I just use steam client and then after libraries are shared, use node.js and expect it to still be shared? 

Anyway, I can tell you my idea for an application of this feature I have. I'd like to use it as donation option. Users can share their libraries with me without having to do this manually.

**Comment by seishun** [comment]
I'm not familiar with the technical details of Family Sharing, but I'd assume you can implement it using the ['message'/send interface](https://github.com/seishun/node-steam#messagesend). You can use [NetHook2](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2) and [NetHookAnalyzer2](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHookAnalyzer2) to find out what messages the Steam client sends and receives, and [node-steam-resources](https://github.com/seishun/node-steam-resources) to access the necessary `EMsg` values and Protobuf messages.

Let me know if anything necessary to implement it is missing in node-steam.

**Comment by Royalgamer06** [comment]
Well, I just tried to do it manually. Someone shared his library to my account on my SERVERPC. Then I closed steam and logged in to my account via SteamKit. Yet, his shared games were not available then. I didn't change the loginID, so it should be fine right?

**Comment by seishun** [comment]
Sorry, I don't really know how family sharing works. You might want to ask in #opensteamworks irc.gamesurge.net or in #steamdb on freenode.

**Comment by Royalgamer06** [comment]
I think steam family sharing relies much on the local configs.
