### ISSUE TITLE
Out of Steam - demo link

### ISSUE THREAD

**Issue by ahmetozalp** [seishun/node-steam#411]
example link: http://steamcommunity.com/id/ViwuAndYouKnow/

**Comment by ahmetozalp** [comment]
what do we like to do with this professor?

**Comment by seishun** [comment]
What is the issue, exactly?

**Comment by ahmetozalp** [comment]
I want to write this membership like the game play place (bad english sry)

**Comment by ahmetozalp** [comment]
https://pasteboard.co/GNHbtZ5.png

**Comment by seishun** [comment]
If you want to get your bot to play a non-Steam game then you can try [gamesPlayed](https://github.com/seishun/node-steam/tree/master/lib/handlers/user#gamesplayedgamesplayed) with values suggested in https://github.com/seishun/node-steam/tree/master/lib/handlers/user#gamesplayedgamesplayed.

**Comment by ahmetozalp** [comment]
i can not find this page but how can i give me an example

**Comment by seishun** [comment]
What page can't you find? This might work, didn't test:

```js
steamUser.gamesPlayed({
  games_played: [
    {game_id: '15444025664222527488', game_extra_info: 'whatever'}
  ]
});
```

**Comment by ahmetozalp** [comment]
bro i live you...
