### ISSUE TITLE
Error: Disconnected

### ISSUE THREAD

**Issue by Dyceman** [seishun/node-steam#416]
I am getting

`   at SteamClient._disconnected (C:\Users\danie\node_modules\steam\lib\steam_client.js:186:24)
    at emitOne (events.js:125:13)
    at Connection.emit (events.js:221:7)
    at TCP._handle.close [as _onclose] (net.js:558:12)`

**Comment by seishun** [comment]
Documented [here](https://github.com/seishun/node-steam#error).

**Comment by Dyceman** [comment]
I am still having the issue. I can login to one account but not the other. The information I am putting in for both are correct....

**Comment by seishun** [comment]
Use https://github.com/seishun/node-steam#logonresponse to find out why you can't log in. And use https://github.com/steam-forward/node-steam-forum/issues for further help questions.

**Comment by scholtzm** [comment]
Might be a SteamGuard request.
