### ISSUE TITLE
Play non-steam game AND normal games?

### ISSUE THREAD

**Issue by cgamewithnormalgames** [seishun/node-steam#419]
Hi

I can show I am playing a non-steam game by passing that long game id into games_played and adding the game_extra_info key with the non-steam game name to the array....

However, Is it possible to have that non-steam game displayed and play normal games as well? I've tried all manor of combinations in the gamesPlayed function but I can't seem to get it working.

Is it possible and if so, what format does the data need to be?

Thank you

Edit: Is this repo still supported?

**Comment by cgamewithnormalgames** [comment]
Hello?

**Comment by scholtzm** [comment]
`games_played` is an array, so technically it should be possible.

```
steamUser.gamesPlayed({
  games_played: [
    { game_id: '15444025664222527488', game_extra_info: 'Non-steam game' },
    { game_id: '440' } // TF2
  ]
});
```

**Comment by seishun** [comment]
If the Steam client can do that, then you can use [NetHook](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2) to see what it sends. Otherwise only Valve knows if it's possible or not.
