### ISSUE TITLE
I would get last van ban list using Steam API (node js)

### ISSUE THREAD

**Issue by willowTank** [seishun/node-steam#420]
Hello Sir.
I am a beginner of steam api.
So Can you help me?
Please let me know best Steam API document.
Then How can I get last vac ban list using Steam API in Node JS
Thanks

**Comment by batizisanya** [comment]
Hi, this is an old thread, but maybe it can help for someone.
If you want to get someone bans, you can use steam web api.
http://api.steampowered.com/ISteamUser/GetPlayerBans/v1/?key=XXXXXXXX&steamids=XXXX,YYYY
Documentation: https://developer.valvesoftware.com/wiki/Steam_Web_API

Or you can use some third party api (like: https://steamid.eu/vac-banned/page/1) and get the whole banlist from there.
