### ISSUE TITLE
Updating 'setPersonaState' to allow for new parameter

### ISSUE THREAD

**Issue by Committing** [seishun/node-steam#421]
no more

**Comment by seishun** [comment]
It doesn't get stripped out anywhere on node-steam's side, but perhaps Steam just doesn't support it. Have you tried using [NetHook2](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2) to see how Steam client uses this field?

**Comment by Committing** [comment]
Thanks for the response Seishun.

I have not tried using NetHook2. Correct me if I am wrong though, the `persona_state_flags` would only be used when not using the Steam client. For instance, using your phone or the browser versions of Steam. If you use the client there is no reason to use the parameter.

I do believe the field is still used as seen [here](https://github.com/DrakeWitt/steam-yellow/blob/master/index.js) albeit an entirely different library and not updated for a year but the same parameters do apply.

Maybe I am misunderstanding something... not entirely sure why it doesn't work.
