### ISSUE TITLE
game_name property in friend object is no longer populated on personaState event

### ISSUE THREAD

**Issue by rubyconn** [seishun/node-steam#422]
I noticed that game_name is no longer updated, and is left empty even when gameid is defined. Here's an excerpt from the friend object that is passed with the SteamFriends.personaState event.

```
{ 
  ...
  game_name: '',
  gameid: '6910',
  game_data_blob: <Buffer > }
```

Has Steam simply stopped using this property? I tried looking for any commits/issues regarding this on the SteamKit repo but couldn't find anything.

**Comment by seishun** [comment]
node-steam doesn't do anything special with the `CMsgClientPersonaState` objects. Have you tried using [NetHook2](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2) to see if it's present when communicating with a real Steam client? The `EMsg` you want to look for is `ClientPersonaState`.

**Comment by rubyconn** [comment]
Thanks for the quick answer! I tried using nethook2 with the analyzer, and it's the same case in the `ClientPersonaState` dumps. I guess I'll just have to use the Steam Web API or Store API to get the game name.

**Comment by scholtzm** [comment]
They still send it for some games, but from what I have seen so far, most personaState messages no longer include this information.
