### ISSUE TITLE
Question: reconnect

### ISSUE THREAD

**Issue by batizisanya** [seishun/node-steam#425]
Hi, I want some help. I wrote a steam bot with node-csgo, and sometimes randomly disconnect from steam, and crash. Can you help for me to handle this type of error and reconnect to steam and also restart? node-csgo.
Last log: 
2 May 01:06:35 - node-csgo unready.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Disconnected
    at SteamClient._disconnected (/xxx/node_modules/steam/lib/steam_client.js:186:24)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:509:12)

Can you help for me?

**Comment by Frederik123** [comment]
var steamClient = new Modules.steam.SteamClient();
steamClient.on('error', function(error) { 
	if (steamClient.loggedOn == false) steamClient.connect();
});

**Comment by seishun** [comment]
You handle it by adding an event handler for the ['error' event'](https://github.com/seishun/node-steam#error).
