### ISSUE TITLE
Third party licenses

### ISSUE THREAD

**Issue by Royalgamer06** [seishun/node-steam#431]
For ubisoft games on steam, you have to install them to activate on uplay. Maybe there is a way to aquire the license through node-steam and apply it to uplay? This way you can activate owned ubisoft games on steam on uplay, without having to install them.

**Comment by seishun** [comment]
It's probably possible if you can do it with Steam client, but you'll have to figure out yourself how to do it using [NetHook2](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2).
