### ISSUE TITLE
Support for new Steam chat

### ISSUE THREAD

**Issue by kraxarn** [seishun/node-steam#432]
Steam recently released a beta for a [new chat](https://steamcommunity.com/updates/chatupdate). This requires users to use the new beta in order to join group chats, and bots (using this library) are now unable to join those group chats.

**Comment by PixelGGamer** [comment]
+1,

**Comment by uosl** [comment]
I guess SteamKit supports the new client now? https://github.com/SteamRE/SteamKit/commit/aecb61a63fccb95bc6f8027e56d03bde68d7eac2
Looks like a lot of work though

**Comment by seishun** [comment]
The new chat is entirely based on unified messages. That means it can be relatively easily implemented using the [UnifiedMessages](https://github.com/seishun/node-steam/tree/master/lib/handlers/unified_messages) handler, and I believe any convenience wrappers around it belong in a separate module.

I've just tried this and it seems work:

```js
const friendMessages = new Steam.SteamUnifiedMessages(steamClient, 'FriendMessages');
friendMessages.send('SendMessage', {
  steamid: friend_id,
  chat_entry_type: 1,
  message: 'hello'
}, (eresult, resp) => { console.log(eresult, resp); });
```

You can use [NetHook2](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2) coupled with NetHookAnalyzer2 (get both [here](https://ci.appveyor.com/project/SteamRE/steamkit)) to find out the relevant service names and methods for things you want to do. For example, NetHookAnalyzer2 will say "FriendMessages.SendMessage#1" for the above example.

To receive notifications, you need to opt in by sending a message for which there is currently no method in node-steam (feel free to submit a separate issue if you would like it added):

```js
steamClient.send({
  msg: Steam.EMsg.ClientCurrentUIMode,
  proto: {}
}, new Steam.Internal.CMsgClientCurrentUIMode({ chat_mode: 2 }).toBuffer());

const friendMessagesClient = new Steam.SteamUnifiedMessages(steamClient, 'FriendMessagesClient');
friendMessagesClient.on('message', (methodName, body) => {
  if (methodName == 'IncomingMessage')
    console.log(body);
});
```

I haven't tried it with chat rooms, but it should be similar. Feel free to ask if anything is unclear or doesn't seem to work (but I can't help you with Steam's chat room or friend API itself).
