### ISSUE TITLE
Throw when accidentially passing SteamIDs as numbers

### ISSUE THREAD

**Issue by mk-pmb** [seishun/node-steam#433]
Since JS numbers are too small to convey SteamIDs, I'd expect all functions to throw if I accidentially pass a number instead of a string. The current behavior, silently carrying on with a rounded version of the number, is one of the worst strategies I could imagine.

**Comment by andrewda** [comment]
Yes, though it would be better to check to make sure it's _not_ a `number` instead of checking if it _is_ a `string`.

```javascript
if (typeof steamID === 'number') {
  throw('Dangerous use of number for steamID.')
}
```

This will ensure the use of a Long (from bytebuffer, which this library uses) is still allowed, in addition to a SteamID class.

**Comment by mk-pmb** [comment]
I'd be ok with the more strict type check as well. Catching the number mistake is just the minimum safeguard. :-)

**Comment by seishun** [comment]
It's not really possible to add checks in every method since most of them just pass objects to Protobuf.js.

**Comment by mk-pmb** [comment]
> It's not really possible to add checks in every method

Challenge accepted.
