### ISSUE TITLE
Steam login servers are timing out

### ISSUE THREAD

**Issue by angel200sdnot** [seishun/node-steam#434]
I am unable to login on steam since the attempt is timing out, the only server that is working at the moment is `{host: '103.28.54.11', port: 27017}` and its commented out

**Comment by gunnrcrakr** [comment]
Same problem.

**Comment by dalexhd** [comment]
Same problem.

**Comment by oskaroldorf** [comment]
@seishun whats the source of your list, so we can fix it ourselves in the future?

**Comment by seishun** [comment]
The ['servers' event](https://github.com/seishun/node-steam#servers-1). See example [here](https://github.com/seishun/node-steam/blob/de7391aa67a22bb1e9071665ad53ad770b51aa73/example.js#L30-L32).

**Comment by scholtzm** [comment]
Also, Steam has Web API for the list as well: https://api.steampowered.com/ISteamDirectory/GetCMList/v1/?format=json&cellid=0

It's better to use the `servers` event though.

**Comment by elboletaire** [comment]
If this is a steam api wrapper, why isn't there a method to retrieve the hosts list on start/init instead of being hardcoded in the code?

I'd suggest adding a new `asyncServers` method to be able to retrieve them dynamically.

**Comment by koalayby** [comment]
@seishun  I have uncommon the {host: '103.28.54.11', port: 27017}, while the bot still not work. Now not clear where is the problem? Do you know？ thanks！

**Comment by Triniayo** [comment]
Hey, I've updated the servers.json for you.

`module.exports = [
  // Washington, USA
  {host: '155.133.229.250', port: 27017},
  {host: '155.133.229.250', port: 27018},
  {host: '155.133.229.250', port: 27019},
  {host: '155.133.229.251', port: 27017},
  {host: '155.133.229.251', port: 27018},
  {host: '155.133.229.251', port: 27019},
  {host: '155.133.230.50', port: 27017},
  {host: '155.133.230.50', port: 27018},
  {host: '155.133.230.50', port: 27019},
  {host: '155.133.230.34', port: 27017},
  {host: '155.133.230.34', port: 27018},
  {host: '155.133.230.34', port: 27019},
  {host: '155.133.254.132', port: 27017},
  {host: '155.133.254.132', port: 27018},
  {host: '155.133.254.132', port: 27019},
  {host: '155.133.254.133', port: 27017},
  // Virginia, USA
  {host: '162.254.192.109', port: 27017},
  {host: '162.254.192.109', port: 27018},
  {host: '162.254.192.109', port: 27019},
  {host: '162.254.192.108', port: 27017},
  {host: '162.254.192.108', port: 27018},
  {host: '162.254.192.108', port: 27019},
  {host: '162.254.192.100', port: 27017},
  {host: '162.254.192.100', port: 27018},
  {host: '162.254.192.100', port: 27019},
  {host: '162.254.192.101', port: 27017},
  {host: '162.254.192.101', port: 27018},
  {host: '162.254.192.101', port: 27019},
  // Illinois, USA
  {host: '162.254.193.46', port: 27017},
  {host: '162.254.193.46', port: 27018},
  {host: '162.254.193.46', port: 27019},
  {host: '162.254.193.47', port: 27017},
  {host: '162.254.193.47', port: 27018},
  {host: '162.254.193.47', port: 27019},
  {host: '162.254.193.6', port: 27017},
  {host: '162.254.193.6', port: 27018},
  {host: '162.254.193.6', port: 27019},
  {host: '162.254.193.7', port: 27017},
  {host: '162.254.193.7', port: 27018},
  {host: '162.254.193.7', port: 27019},
  // Frankfurt, Germany
  {host: '162.254.197.40', port: 27017},
  {host: '162.254.197.40', port: 27018},
  {host: '162.254.197.40', port: 27019},
  {host: '162.254.197.42', port: 27017},
  {host: '162.254.197.42', port: 27018},
  {host: '162.254.197.42', port: 27019},
  {host: '162.254.197.180', port: 27017},
  {host: '162.254.197.180', port: 27018},
  {host: '162.254.197.180', port: 27019},
  {host: '162.254.197.181', port: 27017},
  {host: '162.254.197.181', port: 27018},
  {host: '162.254.197.181', port: 27019},
  // Amsterdam, Netherlands
  {host: '155.133.248.53', port: 27017},
  {host: '155.133.248.53', port: 27018},
  {host: '155.133.248.53', port: 27019},
  {host: '155.133.248.52', port: 27017},
  {host: '155.133.248.52', port: 27018},
  {host: '155.133.248.52', port: 27019},
  {host: '155.133.248.50', port: 27017},
  {host: '155.133.248.50', port: 27018},
  {host: '155.133.248.50', port: 27019},
  {host: '155.133.248.51', port: 27017},
  {host: '155.133.248.51', port: 27018},
  {host: '155.133.248.50', port: 27019},
  // Madrid, Spain
  {host: '155.133.246.69', port: 27017},
  {host: '155.133.246.69', port: 27018},
  {host: '155.133.246.69', port: 27019},
  {host: '155.133.246.68', port: 27019},
  {host: '155.133.246.68', port: 27019},
  {host: '155.133.246.68', port: 27019},
  // London, United Kingdom
  {host: '146.66.152.11', port: 27017},
  {host: '146.66.152.11', port: 27018},
  {host: '146.66.152.11', port: 27019},
  {host: '146.66.152.10', port: 27017},
  {host: '146.66.152.10', port: 27018},
  {host: '146.66.152.10', port: 27019},
  {host: '162.254.196.83', port: 27017},
  {host: '162.254.196.83', port: 27018},
  {host: '162.254.196.83', port: 27019},
  {host: '162.254.196.67', port: 27017},
  {host: '162.254.196.67', port: 27018},
  {host: '162.254.196.67', port: 27019},
  {host: '162.254.196.68', port: 27017},
  {host: '162.254.196.68', port: 27018},
  {host: '162.254.196.68', port: 27019},
  {host: '162.254.196.84', port: 27017},
  {host: '162.254.196.84', port: 27018},
  {host: '162.254.196.84', port: 27019},
  // Stockholm, Sweden
  {host: '155.133.242.9', port: 27017},
  {host: '155.133.242.9', port: 27018},
  {host: '155.133.242.9', port: 27019},
  {host: '185.25.180.15', port: 27017},
  {host: '185.25.180.15', port: 27018},
  {host: '185.25.180.15', port: 27019},
  {host: '155.133.242.8', port: 27017},
  {host: '155.133.242.8', port: 27018},
  {host: '155.133.242.8', port: 27019},
  {host: '185.25.180.14', port: 27017},
  {host: '185.25.180.14', port: 27018},
  {host: '185.25.180.14', port: 27019},
];`

**Comment by seishun** [comment]
Sorry for the wait - I've fixed it in https://github.com/seishun/node-steam/commit/8f0f68bc244bc02fd38c585bbe956b9546c562a0. I'll be grateful if you can give it a try before I publish a new release to npm (but beware that you need svn and curl to install from git).

**Comment by dalexhd** [comment]
In my case, every 6 hours by bots restart for security reasons, and on each starts the bot  download the newest serverlist and save it on nodemodules. So i dont have this error anytime.

**Comment by seishun** [comment]
You really don't need to do that because the 'servers' event provides you with the latest server list.

**Comment by dalexhd** [comment]
Yep, i use this event to get serverlist, and then i save the response.
