### ISSUE TITLE
stops

### ISSUE THREAD

**Issue by bitstuckhere** [seishun/node-steam#435]
Hi

I run two bots, one with email authentication and one with mobile authentication.

Over the last 3 days, around 5 times now my bots have gone offline with error 20 which I assume is steam updates. But when I look at bots other people have made, they don't stop and I think it's because they aren't using this API but a newer one.

Does this API not support reconnecting after steam updates? If so, how should I implement this for both of my bots? Thanks

**Comment by seishun** [comment]
20 is [ServiceUnavailable](https://github.com/SteamRE/SteamKit/blob/0d7b02487191d8403caaa404f84113391e90ceac/Resources/SteamLanguage/eresult.steamd#L23), which is normal. Just keep reconnecting.

**Comment by bitstuckhere** [comment]
Thanks for the fast reply. When you say, just keep reconnecting, I have been doing that but it's really frustrating when I wake up and they're offline and I have to get my auth code out again and restart it. Is there no way to keep it running automatically after error 20?

**Comment by seishun** [comment]
If you're using Steam Guard, you can specify `sha_sentryfile` when logging in to avoid having to specify `auth_code`, see https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon. No clue about two-factor auth, I don't use it in my bots.

**Comment by bitstuckhere** [comment]
Yes that is what I have been doing with my email bot, it's the mobile bot that is the problem because it loses its login session and dies on error 20 and then has no way to reconnect automatically because it requires the mobile two-factor auth code to re-log in. Other bots aren't affected by this though - they don't even go offline so they must use a different API that handles the event differently(?) Either that or I need to do something different which is where I wasn't sure

**Comment by seishun** [comment]
If the Steam server goes offline, the bot will go offline and will need to reconnect (manually or automatically), there's no way around it.

There's https://github.com/DoctorMcKay/node-steam-totp but I haven't used it. You might want to ask in https://github.com/steam-forward/node-steam-forum
