### ISSUE TITLE
Idles went offline

### ISSUE THREAD

**Issue by nodeidlesoffline** [seishun/node-steam#442]
Hi

My two bots went offline today. Has something happened to the node-steam api that it is now outdated?

I've been unable to relog in since. It seems to think forever after attempting to log in.

I've tried updating the 'servers' file in the node-steam dir with the list of new servers but that didn't fix it.

Is there something else I am missing?

Thank you!

Edit: My bots have been offline for 15+ hours now

**Comment by Triniayo** [comment]
The servers.js is just outdated. Take this one:

https://github.com/seishun/node-steam/pull/443

Should work for you.

**Comment by seishun** [comment]
Closing due to lack of response from the reporter.
