### ISSUE TITLE
Possible to login with shared_secret meanwhile?

### ISSUE THREAD

**Issue by Triniayo** [seishun/node-steam#444]
Hello,

is it possible to log into an account with the shared_secret meanwhile? Would be sick if that'd be possible. If not, I'll have to switch the library I guess. :(

**Comment by seishun** [comment]
Do you mean logging in with two-factor authentication? If so, yes: https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon

**Comment by Triniayo** [comment]
Yes, I mean logging in with two-factor, but not with the authcode itself. Would love to be able to sign in through the shared_secret itself, with which you can generate authcodes.

**Comment by seishun** [comment]
You will need a separate library to generate authcodes, try https://github.com/DoctorMcKay/node-steam-totp (I've never used it though).

**Comment by Triniayo** [comment]
I assume that I need the shared_secret, to generate a code, with which I'll be able to log in, right?

**Comment by seishun** [comment]
>I assume that I need the shared_secret, to generate a code, with which I'll be able to log in, right?

Seems so.

**Comment by scholtzm** [comment]
`shared_secret` only provdes the seed for 2FA code generator. You can't use it directly to login.

**Comment by Triniayo** [comment]
> `shared_secret` only provdes the seed for 2FA code generator. You can't use it directly to login.

I thought so. I got it working. x)

https://github.com/Triniayo/steam-hourboost-2fa-mysql

@seishun btw, please push the update for the servers.js at some point, I've committed it. You just need to merge :)
