### ISSUE TITLE
Is there any way to get app information on steam client?

### ISSUE THREAD

**Issue by AGDholo** [seishun/node-steam#445]
I noticed that the steamkit2 c# program used by steamdb can get the client information of the application. Is there the same method on node-steam?
Similar to typing app_info_print 440 on the steam console.
![20181008162153.png](https://i.loli.net/2018/10/08/5bbb157e651eb.png)

**Comment by seishun** [comment]
node-steam doesn't provide methods to request this information, but you can implement them yourself using ['message'/send](https://github.com/seishun/node-steam#messagesend). You can use [NetHook2](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2) coupled with NetHookAnalyzer2 (get both [here](https://ci.appveyor.com/project/SteamRE/steamkit)) to find out relevant `EMsg`s and protobuf classes. Feel free to ask if anything is unclear.
