### ISSUE TITLE
How to send ServiceMethod calls from client?

### ISSUE THREAD

**Issue by walamana** [seishun/node-steam#447]
I've been looking for a solution to gather the last played games of a user. I took a look at a steam nethook dump and found a outgoing message "ServiceMethodCallFromClient" with the target_job_name "Player.ClienGetLastPlayedTimes#1", but could not find a protobuf for it? 

![nethookanalyzer2_2018-11-07_19-32-14](https://user-images.githubusercontent.com/26465630/48152326-dbdd1780-e2c3-11e8-99d5-0d1e25ae099f.png)

How can I send such service method calls?

**Comment by seishun** [comment]
Is this not it? https://github.com/SteamRE/SteamKit/blob/c3f261d6c0a1543f3db7117ee8ab1bc6001a042f/Resources/Protobufs/steamclient/steammessages_player.steamclient.proto#L162

You should be able to construct a UnifiedMessages instance with `new Steam.SteamUnifiedMessages(steamClient, 'Player');` and then call [send](https://github.com/seishun/node-steam/tree/master/lib/handlers/unified_messages#sendmethod-body-callback) on it like this:

```js
player.send('ClientGetLastPlayedTimes', { min_last_played: whatever }, (result, resp) => {
  // handle result and resp as needed
});
```

I didn't try it, let me know if it works.

**Comment by walamana** [comment]
Ah, cool, this works, thanks 😄. I didn't know that I can create new instances of unified messages.
