### ISSUE TITLE
Bot never connect

### ISSUE THREAD

**Issue by wo0lien** [seishun/node-steam#457]
Hi,
I'm trying to make this code working  :
``` var Steam = require('steam');
var fs = require('fs');
var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);

Steam.servers = JSON.parse(fs.readFileSync('./serv.json').toString());

steamClient.connect();
steamClient.on('connected', function () {
        steamUser.logOn({
            account_name: 'secret',
            password: 'secret'
        });
});

steamClient.on('debug', function (response) {
        console.log(response);
});
    
steamClient.on('logOnResponse', function (response) {
        console.log(response);
});

steamClient.on('error', function () {
        console.log('[ERROR] '+error);
}); 
```

The output are indefinitly something like : 

connecting to <ipadress>
socket timed out
socket closed

I tried to import the host table with working servers you posted in the #434. I believe I have done something wrong but I can't find my mistake.

Thank you in advance for help :smile:

**Comment by seishun** [comment]
Which version of node-steam are you using?

**Comment by wo0lien** [comment]
1.4.0
I tried the 1.4.1 but it fail with an error
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/wo0lien/Documents/WebProject/csgoBot/node_modules/steam/node_modules/steam-resources/protogen/protos.csv'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/home/wo0lien/Documents/WebProject/csgoBot/node_modules/steam/node_modules/steam-resources/index.js:6:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by seishun** [comment]
Can you show the folder structure under `/home/wo0lien/Documents/WebProject/csgoBot/node_modules/steam`?

**Comment by wo0lien** [comment]
![steam_folder](https://user-images.githubusercontent.com/30974532/55074294-37038100-5090-11e9-999b-fb96bd5ed352.png)

**Comment by seishun** [comment]
What's inside steam-resources?

I suggest reinstalling the module.

**Comment by seishun** [comment]
What's inside steam-resources?

I suggest reinstalling the module.

**Comment by wo0lien** [comment]
I made an other folder, installed `node-steam` with 
`npm init`
`npm install steam --save`

And still get the same error

Inside the steam-ressources folder : 

![steam-ressources](https://user-images.githubusercontent.com/30974532/55090335-39c19e80-50af-11e9-9472-a90e8e958c95.png)

**Comment by seishun** [comment]
I guess there's an issue with your npm cache. Try clearing it.

**Comment by wo0lien** [comment]
`rm -rf ~/.npm`
`npm cache clear` in the folder.
Nothing changed. I also tried to `npm update` without more succes.

It is strange because there is no protogen folder in steam-ressources

**Comment by seishun** [comment]
There is in the tarball: https://registry.npmjs.org/steam/-/steam-1.4.1.tgz

So it's something in your installation. Try on a different machine.

**Comment by wo0lien** [comment]
I replaced the files in node_modules/steam with the tarball's one and the script run properly with node-steam 1.4.1.
At this moment it didn't connect but I made it work by swaping to an other network connection. Thank you very much for your time !  I let you close the thread if you think this is greatly solved :)
