### ISSUE TITLE
"requestFriendData" returns undefined

### ISSUE THREAD

**Issue by aytugdemir** [seishun/node-steam#461]
As the title says. Output in this code is undefined.
```js
steamFriends.on('message', function (steamID, message) {
    if (!message) return;
    var user = steamFriends.requestFriendData([steamID]);
    console.log(user);
});
```

**Comment by seishun** [comment]
[requestFriendData](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#requestfrienddatasteamids-requesteddata) doesn't return a value. As the documentation states:
>The response, if any, should arrive in the 'personaState' event.
