### ISSUE TITLE
auth_code ignored?

### ISSUE THREAD

**Issue by fensterhebel** [seishun/node-steam#470]
Hello there! Not sure, whether this is the right place for this.
In my app all of a sudden the parameter auth_code seems to be ignored. It always gives me error 85: 2 factor auth required.
Can anyone confirm this? Have there been recent changes with steam? Or is it just me?
Thx

**Comment by seishun** [comment]
`auth_code` is used only for email-based Steam Guard. Did you enable 2-factor auth for your account?

**Comment by ghost** [comment]
`two_factor_code` is needed if you are using 2-factor auth @fensterhebel -- sorry for bumping this if this already been resolved
