### ISSUE TITLE
error, how can i fix?

### ISSUE THREAD

**Issue by codsec** [seishun/node-steam#472]
![image](https://user-images.githubusercontent.com/44205014/89140173-3ba73780-d517-11ea-9468-266b69043ccd.png)

I'm trying to install it, but it happens, how to fix it?
if you can help me, thank you in advance

**Comment by seishun** [comment]
Looks like an npm issue. Try clearing your cache or a different machine.

**Comment by Gameghostify** [comment]
Got this fixed by deleting package-lock.json and then installing again. Happens regularly for some reason
