### ISSUE TITLE
Under what conditions the "servers" event is triggered?

### ISSUE THREAD

**Issue by dmetree01** [seishun/node-steam#474]
Please indicate in the readme that the "servers" event is triggered after successful execution of the "logOn" method. this information would have saved me time.

**Comment by seishun** [comment]
What were you doing that the specific timing of the 'servers' event made a difference?

**Comment by dmetree01** [comment]
I just needed a list of active steam server addresses. I expected this event to fire immediately after the "connected" event. In any case, I ended up with this list, only it was a bit non-obvious. Thanks :)

**Comment by seishun** [comment]
It's emitted when Steam sends you a server list. That seems to happen upon logging in, but it could change. Either way you shouldn't rely on this event to be emitted at all.
