### ISSUE TITLE
ClientPICSProductInfoRequest with 'message'/send (question)

### ISSUE THREAD

**Issue by xan105** [seishun/node-steam#475]
Following your answer in #445 I've used NetHook2 with NetHookAnalyzer2 to find out relevant EMsgs and protobuf classes used by `app_info_print` in Steam's console : 
- ClientPICSProductInfoRequest (8903)
- ClientPICSProductInfoResponse (8904)

![nethook](https://user-images.githubusercontent.com/14090532/93663069-341ffb80-fa8f-11ea-80c9-171ddfdbb49e.png)

I'm trying to send `ClientPICSProductInfoRequest` using .send() method. 
But I'm **stuck** with the buffer content ?
I saw this issue #363 where you say to use `node-steam-resources` to get protobuf definitions but I can't seem to find ClientPICSProductInfoRequest in it.

```js
const Steam = require('steam');
const schema = require('steam-resources');

/* ... */

Steam.send(
    {
      msg: Steam.EMsg.ClientPICSProductInfoRequest, //This exists okay
      proto: {} //I think I don't need to set any fields
    },
//body (buffer)   
//Following your src code and #363 I should do something like this I believe :
 new schema.Internal.ClientPICSProductInfoRequest({
        appid: 1113000,
        acces_token: 0
    }).toBuffer()
//But I have look around in what's returned by 'steam-resources' and can't seem to find it.
// Or is there a way for me to implement it myself ?
);
```
I know this is not an helpdesk ^^ I've looked through this repo and steam-resources's repo and after many hours I'm still completely stuck ! 😰
I feel like I'm really close to want I want to do and only need to figure out _what I am supposed to send as a buffer_ for this method.

After that I basically just need `sha` and `http_host` from the body response.
And I can get the file like so `http_host + appid + sha`
eg: http://clientconfig.akamai.steamstatic.com/appinfo/1113000/sha/C1D1469A3D62F922FC0055C8D3FD6E4B7C8669E8.txt.gz

Could you be so kind as to point me in the right direction to send the correct buffer for ClientPICSProductInfoRequest (8903) ?

**Comment by seishun** [comment]
I'm not sure why NetHookAnalyzer2 isn't showing the protobuf message name (I would submit an issue about it), but it's probably `CMsgClientPICSProductInfoRequest` defined in https://github.com/SteamDatabase/Protobufs/blob/master/steam/steammessages_clientserver.proto.

**Comment by xan105** [comment]
Ahhh !!! Thank you so much ❤️ I managed to do what I wanted 🚀
