### ISSUE TITLE
SteamGameCoordinator doesn't accept ClientHello

### ISSUE THREAD

**Issue by samyycX** [seishun/node-steam#479]
im trying to send ClientHello to my SteamGameCoordinator, but it never return. (message event listener never trigger)

I have connected to the steamClient and logon a steamuser, it returned Steam.EResult.OK.

**Comment by seishun** [comment]
Please provide a test case.

**Comment by samyycX** [comment]
> Please provide a test case.

actually, im using a node package called "csgo"...
i guess this is the send ClientHello code in this package:

```
steamGC.send(
          {
            msg: protos.GC.CSGO.Internal.EGCBaseClientMsg.k_EMsgGCClientHello, 
            proto: {}
          }, new protos.GC.CSGO.Internal.CMsgClientHello({}).toBuffer()
        );
```

and this is the steamGC:
`var steamGC = new Steam.SteamGameCoordinator(steamClient, 730);`

I have asked other people, they can successfully get the return of ClientHello

**Comment by seishun** [comment]
>I have asked other people, they can successfully get the return of ClientHello

Then I can't help you. Try asking the maintainer of the "csgo" package. Maybe you're not in-game, but it's just a guess since I've never worked with CSGO GC.

**Comment by samyycX** [comment]
> > I have asked other people, they can successfully get the return of ClientHello
> 
> Then I can't help you. Try asking the maintainer of the "csgo" package. Maybe you're not in-game, but it's just a guess since I've never worked with CSGO GC.

but i think the main issue is SteamGameCoordinator. Do you know any situations where SteamGameCoordinator can have problems?

**Comment by samyycX** [comment]
> > I have asked other people, they can successfully get the return of ClientHello
> 
> Then I can't help you. Try asking the maintainer of the "csgo" package. Maybe you're not in-game, but it's just a guess since I've never worked with CSGO GC.

ok, i solved this fking problem. It's because I don't own CSGO in my steam account.
