### ISSUE TITLE
Accept friend

### ISSUE THREAD

**Issue by maxibaby** [seishun/node-steam#53]
Hello, i dont understand something

'friend'

SteamID of the user
EFriendRelationship
Some activity in your friend list. For example, EFriendRelationship.PendingInvitee means you got a friend invite, EFriendRelationship.None means you got removed. The friends property is updated after this event is emitted.

I've done this : 

bot.on('friend', function (SteamID, Relation){
    if (Relation == 2){
        bot.addFriend(SteamID);
    console.log(SteamID + " Accepted")
}
});

Witch auto accept invites, but how do i see those EFriendRelationship.PendingInvitee
EFriendRelationship.None
or What's the sintax, i dont get it

**Comment by trader514** [comment]
sorry but the https://github.com/seishun/node-steam/blob/master/lib/generated/steam_language.js page is not found

**Comment by andrewda** [comment]
@trader514 [url=https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/enums.steamd]Here's the new list[/url]
