### ISSUE TITLE
ClientInviteUserToClan

### ISSUE THREAD

**Issue by thesupremecommander** [seishun/node-steam#55]
Is there a way to leverage EMsg.ClientInviteUserToClan so that group invites can be sent out by node-steam? I've been trying to look and see whether the message structure is in the schema but haven't had much luck so far.

**Comment by jabbink** [comment]
@scholtzm What is the reason to have a separate module for this instead of merging it into this module?

**Comment by scholtzm** [comment]
@jabbink `SteamKit2` doesn't contain definitions of protobuf messages used for group interaction and since `node-steam` relies on their protobufs, these group functions cannot be added easily.

**Comment by jabbink** [comment]
Ok.
