### ISSUE TITLE
Nonsteam games with names.

### ISSUE THREAD

**Issue by Efreak** [seishun/node-steam#69]
I've tried hacking in support for this, but I'm not really sure what I'm doing. You can see what I did on my fork, [here](https://github.com/Efreak/node-steam/commit/09bbcf7a7b6c04103af1143ea62d238d12bfd800). I also tried changing ClientGamesPlayed to ClientGamesPlayedWithDataBlob, but it seems that this isn't in your schema. I'm not entirely sure what this means or how to fix it. I do note that ClientGamesPlayedWithDataBlob isn't in that file.

Would this be an easy thing for you (or me, though I doubt it) to fix, or should I abandon it? The idea is to be able to have the bot display mute and other statuses (e.g. xx broken) by changing the game name.

**Comment by andrewda** [comment]
I agree that, if this is possible, it would be a great thing to add.

**Comment by seishun** [comment]
gamesPlayed now takes a CMsgGamesPlayed object, so it's now possible. I'm not sure how it works exactly, but the following works for me:

```js
steamUser.gamesPlayed({
  games_played: [{
    game_id: '15444025664222527488',
    game_extra_info:  '💩'
  }]
});
```

If you manage to figure out how Steam decides what `game_id` to use for non-Steam games, please add it to the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs).

**Comment by andrewda** [comment]
Hmm interesting. I'll be sure to take a look at it, @seishun !

**Comment by Efreak** [comment]
Would a packet capture from me adding a few nonsteam games, then renaming and playing them help? I can set that up if necessary...

Alternatively, does [this](https://godoc.org/github.com/manveru/go-steam/internal#CMsgClientGamesPlayed) help? it seems to have more available. I'm not sure what exactly String or Reset do, though I haven't looked at it too hard.

**Comment by seishun** [comment]
>Would a packet capture from me adding a few nonsteam games, then renaming and playing them help? I can set that up if necessary...

I can do that myself, that's how I found a possible value for `game_id`. Getting more data won't really help. You'd need to go deeper to find out where it's coming from, possibly by using a decompiler. And does it really matter anyway?

>Alternatively, does this help? it seems to have more available. I'm not sure what exactly String or Reset do, though I haven't looked at it too hard.

That's just generated Go code for the protobuf, so it's as helpful as the the [original protobuf](https://github.com/SteamRE/SteamKit/blob/6aa47f764c796a1373a047cd30540c206943fcae/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L205).

**Comment by Efreak** [comment]
Nah. doesn't really matter. I'd just like to put detailed information in there, like when a function is bugged or not working or some such, it would be more convenient than placing long statuses in the name. I'm in the middle of switching to 1.0.0, so hopefully it works when I'm done.

**Comment by seishun** [comment]
It already works using a hard-coded `game_id` as I showed in the snippet above. Just replace `'💩'` with another "game".
