### ISSUE TITLE
Add friend method is not working

### ISSUE THREAD

**Issue by BenHuiHui** [seishun/node-steam#73]
bot.addFriend(steamID);
I use this method to add friend and there is no effect.
Is my function call wrong as i notice i did not even specify the api key.

**Comment by paezao** [comment]
Hey @qinghe1992 did you get this working? I have the same problem. :(

**Comment by EduardoAC** [comment]
Me too, I am having the same problem currently. Can you put an example of the flow of adding a friend @seishun ?
