### ISSUE TITLE
Sentry hash logon problem

### ISSUE THREAD

**Issue by vchestnov** [seishun/node-steam#77]
So my code can login successfully with authCode, 'sentry' event works normally, but when it comes to registering that hash as explained [here](https://github.com/seishun/node-steam#logonlogondetails) I get 65 ([InvalidLoginAuthCode](https://github.com/seishun/node-steam/blob/master/lib/generated/steam_language.js#L1741)) if i reuse the authCode with my hash. I think I'm doing something wrong. How exactly should I register my sentry hash? Should I provide on with new authCode I got from the mail? Is sentry hash generated locally and how does it depend on the authCode I use? Sorry for newbie questions, I have no ideai what I'm doing.

``` javascript
var fs = require('fs');
var Steam = require('steam');
var JSON = require('JSON');

if (fs.existsSync('servers')) {
  Steam.servers = JSON.parse(fs.readFileSync('servers'));
};

var bot = new Steam.SteamClient();

bot.logOn({
  accountName: 'username',
  password: 'password',
  authCode: 'code',
  shaSentryFile: (fs.existsSync('sentryfile') ? fs.readFileSync('sentryfile') : undefined)
});

bot.on('sentry',function(sentryHash) {
  fs.writeFile('sentryfile',sentryHash,function(err) {
    if(err){
      console.log(err);
    } else {
      console.log('Saved sentry file hash as "sentryfile"');
    }
  });
});
```

**Comment by doged** [comment]
im still having the same issue as @sevasan. i have the sentryfile hex in place in my auth.json, but everytime i log in, i get an error 63, and another auth code sent to my mail.. not having an issue with cap sensitivity either.. =\

**Comment by doged** [comment]
its an insane loop, i get the sentry with the auth code, put the sentry into my auth.json, compile the .ts, run the js output in nodejs, and get another login error, then another auth code..

**Comment by doged** [comment]
this is what im using to get my sentry: 
var Steam = require("steam");
var bot = new Steam.SteamClient();
bot.logOn({
    accountName: "username",
    password: "password",
    authCode: "Steam Guard code that is sent to your email"
});
bot.on("sentry", function(sentry) {
    console.log("Sentry in hex form: " + sentry.toString("hex"));
});

**Comment by scholtzm** [comment]
You can't pass the hex values, `shaSentryfile` needs to be a binary buffer.
